### ISSUE TITLE
ionic platform add ios not working [used brew for install; used sudo to add cordova]

### ISSUE THREAD

**Issue by agastya26** [ionic-team/ionic-cli#1062]
Agastyas-MacBook-Air:BetaTest EnterTheAku$ ionic platform add ios
/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:53
                throw err;
                ^

Error: EACCES: permission denied, open '/Users/EnterTheAku/.config/configstore/insight-cordova.json'
You don't have access to this file.

```
at Error (native)
at Object.fs.openSync (fs.js:584:18)
at Object.fs.readFileSync (fs.js:431:33)
at Object.create.all.get (/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:34:26)
at Object.Configstore (/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:27:44)
at new Insight (/usr/local/lib/node_modules/cordova/node_modules/insight/lib/index.js:38:34)
at Object.<anonymous> (/usr/local/lib/node_modules/cordova/src/telemetry.js:37:15)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
```

Caught exception:
 undefined

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
