### ISSUE TITLE
ionic serve fails

### ISSUE THREAD

**Issue by peterchibunna** [ionic-team/ionic-cli#108]
If I run `ionic serve` from terminal, I get the following error, after the browser has opened. 

```
/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/node_modules/etag/index.js:55
    throw new TypeError('argument entity must be string or Buffer')
          ^
TypeError: argument entity must be string or Buffer
    at etag (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/node_modules/etag/index.js:55:11)
    at SendStream.setHeader (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:724:15)
    at SendStream.send (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:500:8)
    at onstat (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:585:10)
    at Object.oncomplete (fs.js:93:15)
```

The server has just crashed and nothing rendered on the browser output.

**Comment by lpsBetty** [comment]
I am not sure where I have this problem now on ``ionic serve``

````
[14:08:23] Starting 'sass'...
[14:08:24] Starting 'watch'...
[14:08:24] Finished 'watch' after 7.6 ms
/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/node_modules/etag/index.js:55
    throw new TypeError('argument entity must be string, Buffer, or fs.Stats')
          ^
TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/node_modules/etag/index.js:55:11)
    at SendStream.setHeader (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:724:15)
    at SendStream.send (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:500:8)
    at onstat (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:585:10)
    at FSReqWrap.oncomplete (fs.js:95:15)
````

ionic -v  ``1.6.1``
node -  ``v0.12.6``
cordova -v ``5.1.1``
