### ISSUE TITLE
err !when create app

### ISSUE THREAD

**Issue by q986872053** [ionic-team/ionic-cli#1103]
C:\Users\lenovo>ionic start myTestApp tabs --v2 --ts

Creating Ionic app in folder C:\Users\lenovo\myTestApp based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: connect ECONNREFUSED 204.13.251.16:443
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1080:14)
Error Initializing app: Error: connect ECONNREFUSED 204.13.251.16:443
 Error: connect ECONNREFUSED 204.13.251.16:443
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1080:14)
Caught exception:
 Error: connect ECONNREFUSED 204.13.251.16:443
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1080:14)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

npm  -- 3.9.5
node --v6.2.2
cordova --6..2.0
ionic --2.0.0-beta.31

**Comment by holdlg** [comment]
me too.    I do not know how to solve.

**Comment by jamiebarrow** [comment]
It sounds like you are having a connection issue, perhaps you are trying to connect behind a proxy?

Ionic doesn't seem to use the standard npm proxy settings, but does seem to pick up the PROXY environment variable.

If on git bash:

```
PROXY=http://proxyurl ionic start myTestApp tabs --v2 --ts
```

If on Windows command prompt:

```
set PROXY=http://proxyurl
ionic start myTestApp tabs --v2 --ts
```

See if that helps? I think I did see that there were issues when using the `--ts` flag, perhaps do a search of the issues for that if you still have problems.

**Comment by rakeshprakash91** [comment]
@jamiebarrow thanks it works :)
