### ISSUE TITLE
using typescript#2.0.0-beta

### ISSUE THREAD

**Issue by rolandjitsu** [ionic-team/ionic-cli#1184]
Would it be possible to use another versions of TS?
I'm using the `browserify-typescript` gulp task with the following options:

``` js
tsifyOptions: {
    typescript: require('typescript')
}
```

But it looks like the CLI does not like it:

``` bash
TypeError: Cannot read property 'useCaseSensitiveFileNames' of null
    at matchFileNames (/Users/rolandjitsu/Projects/infarm/operator/node_modules/typescript/lib/typescript.js:45868:29)
    at getFileNames (/Users/rolandjitsu/Projects/infarm/operator/node_modules/typescript/lib/typescript.js:45703:20)
    at parseJsonConfigFileContent (/Users/rolandjitsu/Projects/infarm/operator/node_modules/typescript/lib/typescript.js:45651:18)
    at parseOptions (/Users/rolandjitsu/Projects/infarm/operator/node_modules/tsify/lib/Tsifier.js:59:16)
    at new Tsifier (/Users/rolandjitsu/Projects/infarm/operator/node_modules/tsify/lib/Tsifier.js:92:15)
    at tsify (/Users/rolandjitsu/Projects/infarm/operator/node_modules/tsify/index.js:12:16)
    at Browserify.plugin (/Users/rolandjitsu/Projects/infarm/operator/node_modules/browserify/index.js:351:9)
    at module.exports (/Users/rolandjitsu/Projects/infarm/operator/node_modules/ionic-gulp-browserify-typescript/index.js:40:6)
    at runSequence (/Users/rolandjitsu/Projects/infarm/operator/gulpfile.js:71:16)
    at finish (/Users/rolandjitsu/Projects/infarm/operator/node_modules/run-sequence/index.js:60:5) 
```

**Comment by dwieeb** [comment]
I think this issue is no longer relevant, @rolandjitsu Correct? Closing for now.

**Comment by rolandjitsu** [comment]
@dwieeb definitely!
