### ISSUE TITLE
Exception thrown on "ionic serve" running 'before:serve' for the cutePuppyPics app

### ISSUE THREAD

**Issue by juanf9224** [ionic-team/ionic-cli#1209]
Running 'serve:before' gulp task before serve
[11:11:34] Starting 'clean'...
[11:11:34] Finished 'clean' after 29 ms
[11:11:34] Starting 'watch'...
[11:11:34] Starting 'sass'...
[11:11:34] Starting 'html'...
[11:11:34] Starting 'fonts'...
[11:11:34] Starting 'scripts'...
[11:11:34] Finished 'html' after 322 ms
[11:11:34] Finished 'scripts' after 378 ms
[11:11:34] Finished 'fonts' after 506 ms
[11:11:37] Finished 'sass' after 3.45 s
Caught exception:
 Error: watch null UNKNOWN
    at exports._errnoException (util.js:893:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)

---

_Ionic version -> 2.0.0-beta.33
npm version -> 3.8.6
Cordova version -> 6.3.0
Node version -> 5.12.0_

**PD: app is running with no problem despite the exception.**

**Comment by juanf9224** [comment]
I think this is caused due to npm failing to install fsevents on OS other than macOS. This is npm warn about failing to install fs events:

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

this info might help:
[https://github.com/nodejs/node/issues/7858](url)

**Comment by papotte** [comment]
I'm having the same error, and the link posted by @juanf9224 appears to be invalid, or at least I can't access it. What I'm getting on the console after 'ionic serve' is: 
`Running 'serve:before' gulp task before serve
[14:05:55] Starting 'clean'...
[14:05:56] Finished 'clean' after 988 ms
[14:05:56] Starting 'watch'...
[14:05:56] Starting 'sass'...
[14:05:56] Starting 'html'...
[14:05:56] Starting 'fonts'...
[14:05:56] Starting 'scripts'...
[14:05:58] Finished 'html' after 1.75 s
[14:05:58] Finished 'scripts' after 2.17 s
[14:05:59] Finished 'fonts' after 2.41 s
[14:06:11] Finished 'sass' after 14 s
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: watch null UNKNOWN
    at exports._errnoException (util.js:893:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21) `


The app runs (after many repetitions of the same error) but livereload doesn't seem to work.
For information, I'm on a Windows PC

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v5.12.0

**Comment by juanf9224** [comment]
indeed, the link is dead @papotte , at last i was able to avoid this error, i was using a network drive for my projects and was getting that error, but then i moved them to my local drive and the issue disappeared, maybe it's a problem with the network drive and not ionic's or npm's.
