### ISSUE TITLE
Ionic freezes on “installing npm packages”

### ISSUE THREAD

**Issue by wicketyCode** [ionic-team/ionic-cli#1239]
Am trying to create a new project:

ionic start MyIonic2Project tutorial --v2

But the project is never created, npm freezes as You can see on the screenshots:

![image](https://cloud.githubusercontent.com/assets/13802757/17391479/ba322c52-5a16-11e6-9baa-296c9ff5b080.png)

and later

![image](https://cloud.githubusercontent.com/assets/13802757/17391497/d09dad86-5a16-11e6-8da0-45af1b40fccc.png)

My setup:
C:\Users\aberec\ionic_projects\VERSION2>ionic info

Your system information:

Cordova CLI: 6.3.0
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
OS: Windows 7 SP1
Node Version: v6.3.1

**Comment by jgw96** [comment]
Hello! Would you mind running `ionic start <insert appname here> --v2` and seeing if you run into the same issue? Thanks for using Ionic!

**Comment by aslani75** [comment]
Hi thx for the interest but unfortunately it's the same:

![image](https://cloud.githubusercontent.com/assets/13802757/17455614/cf6caa40-5bbd-11e6-8a41-e26b81e68abf.png)

**Comment by tejit2004** [comment]
Hi guys, I also have an error while setting up new tutorial based project.
![capture1](https://cloud.githubusercontent.com/assets/4394037/17455822/c71f83f2-5be1-11e6-814c-dfedee62fb1f.PNG)

**Comment by jgw96** [comment]
Hello all! Would you all mind updating your ionic cli install by running `sudo npm install -g ionic@beta` and trying again ? Thanks for using Ionic!

**Comment by utsav-gupta** [comment]
I am facing the same issue. I tried the above command , I get this error:

Error with start Error: getaddrinfo EAI_AGAIN codeload.github.com:443
    at Object.exports._errnoException (util.js:870:11)
    at errnoException (dns.js:32:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
Error Initializing app: Error: getaddrinfo EAI_AGAIN codeload.github.com:443
 Error: getaddrinfo EAI_AGAIN codeload.github.com:443
    at Object.exports._errnoException (util.js:870:11)
    at errnoException (dns.js:32:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
Caught exception:
 Error: getaddrinfo EAI_AGAIN codeload.github.com:443
    at Object.exports._errnoException (util.js:870:11)
    at errnoException (dns.js:32:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
@utsav-gupta Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by metrospark** [comment]
It seems npminstall is being executed instead of 'npm install'

**Comment by nelsonkd** [comment]
I am running into a similar issue. When I get to the npm dedupe it just hangs.
<img width="1325" alt="screen shot 2017-07-30 at 2 30 04 pm" src="https://user-images.githubusercontent.com/5487817/28757274-a5c2291e-7533-11e7-85af-8a3d03b66cb0.png">

Running ionic info I get
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/ionic)

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.3.1
    Node              : v6.9.5
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    npm               : 3.10.10

**Comment by dwieeb** [comment]
@nelsonkd Can you do `npm dedupe --verbose` ?

**Comment by nelsonkd** [comment]
```npm info it worked if it ends with ok
npm verb cli [ '/Users/KenAtIBM/.nvm/versions/node/v6.9.5/bin/node',
npm verb cli   '/Users/KenAtIBM/.nvm/versions/node/v6.9.5/bin/npm',
npm verb cli   'dedupe',
npm verb cli   '--verbose' ]
npm info using npm@3.10.10
npm info using node@v6.9.5
npm verb correctMkdir /Users/KenAtIBM/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/KenAtIBM/.npm/_locks/staging-ba9e07856ffc6833.lock for /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/.staging
npm verb unbuild node_modules/fsevents/node_modules/verror
npm info lifecycle verror@1.3.6~preuninstall: verror@1.3.6
npm info lifecycle verror@1.3.6~uninstall: verror@1.3.6
npm verb unbuild rmStuff verror@1.3.6 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle verror@1.3.6~postuninstall: verror@1.3.6
npm verb gentlyRm don't care about contents; nuking /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/verror
npm verb unbuild node_modules/fsevents/node_modules/qs
npm info lifecycle qs@6.4.0~preuninstall: qs@6.4.0
npm info lifecycle qs@6.4.0~uninstall: qs@6.4.0
npm verb unbuild rmStuff qs@6.4.0 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle qs@6.4.0~postuninstall: qs@6.4.0
npm verb gentlyRm don't care about contents; nuking /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/qs
npm verb unbuild node_modules/fsevents/node_modules/ms
npm info lifecycle ms@2.0.0~preuninstall: ms@2.0.0
npm info lifecycle ms@2.0.0~uninstall: ms@2.0.0
npm verb unbuild rmStuff ms@2.0.0 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle ms@2.0.0~postuninstall: ms@2.0.0
npm verb gentlyRm don't care about contents; nuking /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/ms
npm verb unbuild node_modules/fsevents/node_modules/json-schema
npm info lifecycle json-schema@0.2.3~preuninstall: json-schema@0.2.3
npm info lifecycle json-schema@0.2.3~uninstall: json-schema@0.2.3
npm verb unbuild rmStuff json-schema@0.2.3 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle json-schema@0.2.3~postuninstall: json-schema@0.2.3
npm verb gentlyRm don't care about contents; nuking /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/json-schema
npm verb unbuild node_modules/fsevents/node_modules/extsprintf
npm info lifecycle extsprintf@1.0.2~preuninstall: extsprintf@1.0.2
npm info lifecycle extsprintf@1.0.2~uninstall: extsprintf@1.0.2
npm verb unbuild rmStuff extsprintf@1.0.2 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle extsprintf@1.0.2~postuninstall: extsprintf@1.0.2
npm verb gentlyRm don't care about contents; nuking /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/extsprintf
npm verb unbuild node_modules/fsevents/node_modules/concat-map
npm info lifecycle concat-map@0.0.1~preuninstall: concat-map@0.0.1
npm info lifecycle concat-map@0.0.1~uninstall: concat-map@0.0.1
npm verb unbuild rmStuff concat-map@0.0.1 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle concat-map@0.0.1~postuninstall: concat-map@0.0.1
npm verb gentlyRm don't care about contents; nuking /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/concat-map
npm info lifecycle buffer-shims@1.0.0~preuninstall: buffer-shims@1.0.0
npm info lifecycle buffer-shims@1.0.0~uninstall: buffer-shims@1.0.0
npm verb unbuild rmStuff buffer-shims@1.0.0 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle buffer-shims@1.0.0~postuninstall: buffer-shims@1.0.0
npm info lifecycle buffer-shims@1.0.0~preinstall: buffer-shims@1.0.0
npm info lifecycle deep-extend@0.4.2~preuninstall: deep-extend@0.4.2
npm info lifecycle deep-extend@0.4.2~uninstall: deep-extend@0.4.2
npm verb unbuild rmStuff deep-extend@0.4.2 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle deep-extend@0.4.2~postuninstall: deep-extend@0.4.2
npm info lifecycle deep-extend@0.4.2~preinstall: deep-extend@0.4.2
npm info lifecycle fstream-ignore@1.0.5~preuninstall: fstream-ignore@1.0.5
npm info lifecycle fstream-ignore@1.0.5~uninstall: fstream-ignore@1.0.5
npm verb unbuild rmStuff fstream-ignore@1.0.5 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle fstream-ignore@1.0.5~postuninstall: fstream-ignore@1.0.5
npm info lifecycle fstream-ignore@1.0.5~preinstall: fstream-ignore@1.0.5
npm info lifecycle ini@1.3.4~preuninstall: ini@1.3.4
npm info lifecycle ini@1.3.4~uninstall: ini@1.3.4
npm verb unbuild rmStuff ini@1.3.4 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle ini@1.3.4~postuninstall: ini@1.3.4
npm info lifecycle ini@1.3.4~preinstall: ini@1.3.4
npm info lifecycle jodid25519@1.0.2~preuninstall: jodid25519@1.0.2
npm info lifecycle jodid25519@1.0.2~uninstall: jodid25519@1.0.2
npm verb unbuild rmStuff jodid25519@1.0.2 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle jodid25519@1.0.2~postuninstall: jodid25519@1.0.2
npm info lifecycle jodid25519@1.0.2~preinstall: jodid25519@1.0.2
npm info lifecycle node-pre-gyp@0.6.36~preuninstall: node-pre-gyp@0.6.36
npm info lifecycle node-pre-gyp@0.6.36~uninstall: node-pre-gyp@0.6.36
npm verb unbuild rmStuff node-pre-gyp@0.6.36 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm verb gentlyRm Vacuuming /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/.bin/node-pre-gyp up to /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/.bin
npm verb gentlyRm Vacuuming /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/.bin up to /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle node-pre-gyp@0.6.36~postuninstall: node-pre-gyp@0.6.36
npm info lifecycle node-pre-gyp@0.6.36~preinstall: node-pre-gyp@0.6.36
npm info lifecycle rc@1.2.1~preuninstall: rc@1.2.1
npm info lifecycle rc@1.2.1~uninstall: rc@1.2.1
npm verb unbuild rmStuff rc@1.2.1 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm verb gentlyRm Vacuuming /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/.bin/rc up to /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/.bin
npm verb gentlyRm Vacuuming /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/.bin up to /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle rc@1.2.1~postuninstall: rc@1.2.1
npm info lifecycle rc@1.2.1~preinstall: rc@1.2.1
npm info lifecycle strip-json-comments@2.0.1~preuninstall: strip-json-comments@2.0.1
npm info lifecycle strip-json-comments@2.0.1~uninstall: strip-json-comments@2.0.1
npm verb unbuild rmStuff strip-json-comments@2.0.1 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle strip-json-comments@2.0.1~postuninstall: strip-json-comments@2.0.1
npm info lifecycle strip-json-comments@2.0.1~preinstall: strip-json-comments@2.0.1
npm info lifecycle tar-pack@3.4.0~preuninstall: tar-pack@3.4.0
npm info lifecycle tar-pack@3.4.0~uninstall: tar-pack@3.4.0
npm verb unbuild rmStuff tar-pack@3.4.0 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle tar-pack@3.4.0~postuninstall: tar-pack@3.4.0
npm info lifecycle tar-pack@3.4.0~preinstall: tar-pack@3.4.0
npm info lifecycle uid-number@0.0.6~preuninstall: uid-number@0.0.6
npm info lifecycle uid-number@0.0.6~uninstall: uid-number@0.0.6
npm verb unbuild rmStuff uid-number@0.0.6 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules
npm info lifecycle uid-number@0.0.6~postuninstall: uid-number@0.0.6
npm info lifecycle uid-number@0.0.6~preinstall: uid-number@0.0.6
npm info lifecycle minimist@1.2.0~preuninstall: minimist@1.2.0
npm info lifecycle minimist@1.2.0~uninstall: minimist@1.2.0
npm verb unbuild rmStuff minimist@1.2.0 from /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules
npm verb unbuild rmStuff in /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/fsevents/node_modules/rc/node_modules
npm info lifecycle minimist@1.2.0~postuninstall: minimist@1.2.0
npm info lifecycle minimist@1.2.0~preinstall: minimist@1.2.0
npm info linkStuff buffer-shims@1.0.0
npm verb linkBins buffer-shims@1.0.0
npm verb linkMans buffer-shims@1.0.0
npm info linkStuff deep-extend@0.4.2
npm verb linkBins deep-extend@0.4.2
npm verb linkMans deep-extend@0.4.2
npm info linkStuff fstream-ignore@1.0.5
npm verb linkBins fstream-ignore@1.0.5
npm verb linkMans fstream-ignore@1.0.5
npm info linkStuff ini@1.3.4
npm verb linkBins ini@1.3.4
npm verb linkMans ini@1.3.4
npm info linkStuff jodid25519@1.0.2
npm verb linkBins jodid25519@1.0.2
npm verb linkMans jodid25519@1.0.2
npm info linkStuff node-pre-gyp@0.6.36
npm verb linkBins node-pre-gyp@0.6.36
npm verb link bins [ { 'node-pre-gyp': './bin/node-pre-gyp' },
npm verb link bins   '/Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans node-pre-gyp@0.6.36
npm verb gentlyRm don't care about contents; nuking /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/.bin/node-pre-gyp
npm info linkStuff rc@1.2.1
npm verb linkBins rc@1.2.1
npm verb link bins [ { rc: './index.js' },
npm verb link bins   '/Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans rc@1.2.1
npm verb gentlyRm don't care about contents; nuking /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/.bin/rc
npm info linkStuff strip-json-comments@2.0.1
npm verb linkBins strip-json-comments@2.0.1
npm verb linkMans strip-json-comments@2.0.1
npm info linkStuff tar-pack@3.4.0
npm verb linkBins tar-pack@3.4.0
npm verb linkMans tar-pack@3.4.0
npm info linkStuff uid-number@0.0.6
npm verb linkBins uid-number@0.0.6
npm verb linkMans uid-number@0.0.6
npm info linkStuff minimist@1.2.0
npm verb linkBins minimist@1.2.0
npm verb linkMans minimist@1.2.0
npm info lifecycle buffer-shims@1.0.0~install: buffer-shims@1.0.0
npm info lifecycle deep-extend@0.4.2~install: deep-extend@0.4.2
npm info lifecycle fstream-ignore@1.0.5~install: fstream-ignore@1.0.5
npm info lifecycle ini@1.3.4~install: ini@1.3.4
npm info lifecycle jodid25519@1.0.2~install: jodid25519@1.0.2
npm info lifecycle node-pre-gyp@0.6.36~install: node-pre-gyp@0.6.36
npm info lifecycle rc@1.2.1~install: rc@1.2.1
npm info lifecycle strip-json-comments@2.0.1~install: strip-json-comments@2.0.1
npm info lifecycle tar-pack@3.4.0~install: tar-pack@3.4.0
npm info lifecycle uid-number@0.0.6~install: uid-number@0.0.6
npm info lifecycle minimist@1.2.0~install: minimist@1.2.0
npm info lifecycle buffer-shims@1.0.0~postinstall: buffer-shims@1.0.0
npm info lifecycle deep-extend@0.4.2~postinstall: deep-extend@0.4.2
npm info lifecycle fstream-ignore@1.0.5~postinstall: fstream-ignore@1.0.5
npm info lifecycle ini@1.3.4~postinstall: ini@1.3.4
npm info lifecycle jodid25519@1.0.2~postinstall: jodid25519@1.0.2
npm info lifecycle node-pre-gyp@0.6.36~postinstall: node-pre-gyp@0.6.36
npm info lifecycle rc@1.2.1~postinstall: rc@1.2.1
npm info lifecycle strip-json-comments@2.0.1~postinstall: strip-json-comments@2.0.1
npm info lifecycle tar-pack@3.4.0~postinstall: tar-pack@3.4.0
npm info lifecycle uid-number@0.0.6~postinstall: uid-number@0.0.6
npm info lifecycle minimist@1.2.0~postinstall: minimist@1.2.0
npm verb unlock done using /Users/KenAtIBM/.npm/_locks/staging-ba9e07856ffc6833.lock for /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/.staging
buffer-shims@1.0.0 node_modules/fsevents/node_modules/buffer-shims -> node_modules/buffer-shims
deep-extend@0.4.2 node_modules/fsevents/node_modules/deep-extend -> node_modules/deep-extend
fstream-ignore@1.0.5 node_modules/fsevents/node_modules/fstream-ignore -> node_modules/fstream-ignore
ini@1.3.4 node_modules/fsevents/node_modules/ini -> node_modules/ini
jodid25519@1.0.2 node_modules/fsevents/node_modules/jodid25519 -> node_modules/jodid25519
minimist@1.2.0 node_modules/fsevents/node_modules/rc/node_modules/minimist -> node_modules/rc/node_modules/minimist
strip-json-comments@2.0.1 node_modules/fsevents/node_modules/strip-json-comments -> node_modules/strip-json-comments
rc@1.2.1 node_modules/fsevents/node_modules/rc -> node_modules/rc
uid-number@0.0.6 node_modules/fsevents/node_modules/uid-number -> node_modules/uid-number
tar-pack@3.4.0 node_modules/fsevents/node_modules/tar-pack -> node_modules/tar-pack
node-pre-gyp@0.6.36 node_modules/fsevents/node_modules/node-pre-gyp -> node_modules/node-pre-gyp
- extsprintf@1.0.2 node_modules/fsevents/node_modules/extsprintf
- json-schema@0.2.3 node_modules/fsevents/node_modules/json-schema
- ms@2.0.0 node_modules/fsevents/node_modules/ms
- qs@6.4.0 node_modules/fsevents/node_modules/qs
- verror@1.3.6 node_modules/fsevents/node_modules/verror
- concat-map@0.0.1 node_modules/fsevents/node_modules/concat-map
npm verb exit [ 0, true ]
npm info ok ```

**Comment by nelsonkd** [comment]
Here is what I get when I have after reinstalling Ionic 3.6

```
npm info it worked if it ends with ok
npm verb cli [ '/Users/KenAtIBM/.nvm/versions/node/v6.9.5/bin/node',
npm verb cli   '/Users/KenAtIBM/.nvm/versions/node/v6.9.5/bin/npm',
npm verb cli   'dedupe',
npm verb cli   '--verbose' ]
npm info using npm@3.10.10
npm info using node@v6.9.5
npm verb correctMkdir /Users/KenAtIBM/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/KenAtIBM/.npm/_locks/staging-ba9e07856ffc6833.lock for /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/.staging
npm verb unlock done using /Users/KenAtIBM/.npm/_locks/staging-ba9e07856ffc6833.lock for /Users/KenAtIBM/Projects/userLogin/UserLoginApp/node_modules/.staging
npm verb exit [ 0, true ]
npm info ok 
```

**Comment by dwieeb** [comment]
`npm dedupe` doesn't behave differently when you change your ionic version... It may change if run in the same directory twice, however. Both of those outputs look good, but for some reason when ionic ran the command, it hanged.
