### ISSUE TITLE
ionic suddenly stop working after delete custom directives

### ISSUE THREAD

**Issue by lifeisfunny** [ionic-team/ionic-cli#1287]
Running 'serve:before' gulp task before serve
[02:34:01] Starting 'clean'...
[02:34:01] Finished 'clean' after 7.02 ms
[02:34:01] Starting 'watch'...
[02:34:01] Starting 'sass'...
[02:34:01] Starting 'html'...
[02:34:01] Starting 'fonts'...
[02:34:01] Starting 'scripts'...
[02:34:01] Starting 'images'...
[02:34:01] Finished 'images' after 1.32 ms
[02:34:01] Starting 'customfonts'...
[02:34:01] Finished 'customfonts' after 1.5 ms
[02:34:01] Finished 'scripts' after 130 ms
[02:34:01] Finished 'html' after 147 ms
[02:34:01] Finished 'fonts' after 150 ms
Caught exception:
 TypeError: Cannot read property 'value' of undefined
    at Gradient.newDirection (/Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/autoprefixer/lib/hacks/gradient.js:131:20)
    at Gradient.replace (/Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/autoprefixer/lib/hacks/gradient.js:37:29)
    at Gradient.Value.add (/Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/autoprefixer/lib/value.js:92:20)
    at Gradient.add (/Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/autoprefixer/lib/hacks/gradient.js:358:39)
    at Gradient.Prefixer.process (/Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/autoprefixer/lib/prefixer.js:104:18)
    at /Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/autoprefixer/lib/processor.js:138:19
    at /Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/postcss/lib/container.js:208:28
    at /Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/postcss/lib/container.js:164:26
    at Rule.each (/Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/postcss/lib/container.js:130:22)
    at Rule.walk (/Users/haoni/Desktop/o-schedule-app/cp2/o-schedule/node_modules/postcss/lib/container.js:163:21)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
