### ISSUE TITLE
npm i -g ionic on windows 10 fails

### ISSUE THREAD

**Issue by HansS** [ionic-team/ionic-cli#1288]
i wanted to upgrade from my ionic beta.x to ionic 2 with npm but got following error when running
ionic --version:

$ ionic
Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:5:12)
    at Object.<anonymous> (C:\Users\Hans\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:14:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by Kobzol** [comment]
Happens to me on OS X 10.11 (El Capitan) too.
