### ISSUE TITLE
unable to start ionic

### ISSUE THREAD

**Issue by goelmayank** [ionic-team/ionic-cli#1296]
If I run ionic serve from terminal, I get the following error, after the browser has opened.

/usr/local/lib/node_modules/ionic/node_modules/etag/index.js:55
    throw new TypeError('argument entity must be string, Buffer, or fs.Stats')
    ^

TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (/usr/local/lib/node_modules/ionic/node_modules/etag/index.js:55:11)
    at SendStream.setHeader (/usr/local/lib/node_modules/ionic/node_modules/send/index.js:724:15)
    at SendStream.send (/usr/local/lib/node_modules/ionic/node_modules/send/index.js:500:8)
    at onstat (/usr/local/lib/node_modules/ionic/node_modules/send/index.js:585:10)
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by luo772435545** [comment]
if i run ionic serve ,following error,
Caught exception:
 Error: Cannot find module 'ionic-app-lib'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:4:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
