### ISSUE TITLE
Cannot read property 'inputValues' of undefined

### ISSUE THREAD

**Issue by jgirdner** [ionic-team/ionic-cli#1298]
When I run:
`ionic push --production-mode=y`

I get:

```
Caught exception:
 TypeError: Cannot read property 'inputValues' of undefined
    at getCmdArgValue (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:431:11)
    at getCmdLineOptions (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:447:3)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:39:3)
    at Promise.apply (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11) 
```

Here is my plugin info:

```
cordova-custom-config 2.0.3 "cordova-custom-config"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-apprate 1.2 "AppRate"
cordova-plugin-badge 0.7.2 "Badges"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-crosswalk-webview 2.0.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-globalization 1.0.3 "Globalization"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.8.1 "PushPlugin"

```

Here is my ionic info:

```
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by casp0or** [comment]
+1
same problem mentioned a few days earlyer ...

**Comment by cmarin18** [comment]
+1

**Comment by matthewapps** [comment]
+1

**Comment by adancarrasco** [comment]
+1 Any luck on this?

**Comment by casp0or** [comment]
You don't need to use this anymore
