### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined at ChildProcess.<anonymous> 

### ISSUE THREAD

**Issue by Lehonti** [ionic-team/ionic-cli#1303]
Debug file:
[npm-debug.txt](https://github.com/driftyco/ionic-cli/files/431073/npm-debug.txt)

```
PS F:\somePath\chapter7\sass> ionic setup sass
npmnpm WARN package.json sass@1.0.0 No README data
npm WARN package.json sass@1.0.0 No license field.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update t
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> node-sass@0.9.6 install F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass
> node build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass>if not defined npm_config_n
ode_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
ebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not fin
d WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version
number. [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxp
roj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [F:\somePath\chapter7\sass\node_modul
es\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [F:\somePath\chapter7\sass\node_modul
es\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [F:\somePath\chapter7\sass\node_modul
es\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [F:\somePath\chapter7\sass\node_modul
es\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [F:\somePath\chapter7\sass\node_modul
es\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  binding.cpp
  sass_context_wrapper.cpp
  ast.cpp
  base64vlq.cpp
f:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\libsass\sass.h(3): fatal er
ror C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\sass_context_wrappe
r.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxpr
oj]
  bind.cpp
c:\users\lehonti\.node-gyp\4.4.5\include\node\uv-errno.h(25): fatal error C1083: Cannot open include file: 'errno.h': No
 such file or directory (compiling source file ..\binding.cpp) [F:\somePath\chapter7\sass\node_modu
les\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  constants.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\bind.cpp) [F:\somePath\
chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\ast.cpp) [F:\somePath\c
hapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\base64vlq.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  context.cpp
  contextualize.cpp
  copy_c_str.cpp
..\libsass\context.cpp(2): fatal error C1083: Cannot open include file: 'direct.h': No such file or directory [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\contextualize.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  error_handling.cpp
  eval.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\copy_c_str.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  expand.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\error_handling.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  extend.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\eval.cpp) [F:\somePath\
chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  file.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\file.cpp) [F:\somePath\
chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  functions.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\functions.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  inspect.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\inspect.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  output_compressed.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\extend.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\expand.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  output_nested.cpp
  parser.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\output_compressed.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  prelexer.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\output_nested.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\parser.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  sass.cpp
  sass_interface.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\sass.cpp) [F:\somePath\
chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
..\libsass\sass_interface.cpp(2): fatal error C1083: Cannot open include file: 'io.h': No such file or directory [F:\Len
ovoBakB4W10\IonicExercises\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  source_map.cpp
  to_c.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\prelexer.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  to_string.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\source_map.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  units.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\to_c.cpp) [F:\somePath\
chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  utf8_string.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\units.cpp) [F:\somePath
\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  util.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\utf8_string.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\to_string.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
  sass2scss.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\util.cpp) [F:\somePath\
chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include fil
e: 'corecrt.h': No such file or directory (compiling source file ..\libsass\sass2scss\sass2scss.cpp) [F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
76:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\somePath\chapter7\sass\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\somePath\chapter7\sass\npm-debug.log


Caught exception:
 TypeError: Cannot read property 'bold' of undefined
    at ChildProcess.<anonymous> (C:\Users\Lehonti\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\
setup.js:180:49)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

Some more details:
- This is a Windows computer
- I am trying to do the exercise in chapter 7, section 2, in the book _Ionic in Action_
- "gulp-sass" is a required package for the exercise, but npm could not install it, so I downloaded it manually and put it inside the node_modules folder.
- I was originally trying to install the packages using "gulp", with the following gulpfile:

```
var gulp = require('gulp');
var gutil = require('gulp-util');
var bower = require('bower');
var concat = require('gulp-concat');
var sass = require('gulp-sass');
var minifyCss = require('gulp-minify-css');
var rename = require('gulp-rename');
var sh = require('shelljs');

var paths = {
  sass: ['./scss/**/*.scss', './www/**/*.scss']
};

gulp.task('default', ['sass']);

gulp.task('sass', function(done) {
  gulp.src('./scss/ionic.app.scss')
    .pipe(sass())
    .pipe(gulp.dest('./www/css/'))
    .pipe(minifyCss({
      keepSpecialComments: 0
    }))
    .pipe(rename({ extname: '.min.css' }))
    .pipe(gulp.dest('./www/css/'))
    .on('end', done);
});

gulp.task('watch', function() {
  gulp.watch(paths.sass, ['sass']);
});

gulp.task('install', ['git-check'], function() {
  return bower.commands.install()
    .on('log', function(data) {
      gutil.log('bower', gutil.colors.cyan(data.id), data.message);
    });
});

gulp.task('git-check', function(done) {
  if (!sh.which('git')) {
    console.log(
      '  ' + gutil.colors.red('Git is not installed.'),
      '\n  Git, the version control system, is required to download Ionic.',
      '\n  Download git here:', gutil.colors.cyan('http://git-scm.com/downloads') + '.',
      '\n  Once git is installed, run \'' + gutil.colors.cyan('gulp install') + '\' again.'
    );
    process.exit(1);
  }
  done();
});

```

**Comment by ronal2do** [comment]
+1

**Comment by scottp** [comment]
+1

**Comment by evolverine** [comment]
+1 I was running `ionic setup sass --v2` on the project folder. I already had gulp installed globally.

**Comment by patrickhofer** [comment]
Any update?

**Comment by thebedivere** [comment]
I'm seeing this too.
