### ISSUE TITLE
Ionic start in an existing folder

### ISSUE THREAD

**Issue by domharrington** [ionic-team/ionic-cli#1307]
I setup a new repo using `npm init` then installed `ionic` via `npm i ionic@latest --save`. What's the best way to then run `ionic start` in this folder?

I tried `./node_modules/.bin/ionic start .` and i get:

```
Please name your Ionic project something meaningful other than '.'
```

So i went up a directory and tried to run `./project/node_modules/.bin/ionic start project`.

This outputs the following error and deleted my folder!

```
$ ./project/node_modules/.bin/ionic start project
Directory already exists: /Users/user/Sites/project
Would you like to overwrite the directory with this new project?
(yes/no): yes

Creating Ionic app in folder /Users/user/Sites/project based on tabs project
 Error: Cannot find module 'adm-zip'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.fetchArchive (/Users/user/Sites/project/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js:90:16)
    at Object.fetchWrapper (/Users/user/Sites/project/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:186:9)
    at Object.startApp (/Users/user/Sites/project/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:104:16)
    at /Users/user/Sites/project/node_modules/ionic/lib/ionic/start.js:91:18
    at _fulfilled (/Users/user/Sites/project/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/user/Sites/project/node_modules/ionic/node_modules/q/q.js:816:30)
Caught exception:
 Error: Cannot find module 'adm-zip'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.fetchArchive (/Users/user/Sites/project/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js:90:16)
    at Object.fetchWrapper (/Users/user/Sites/project/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:186:9)
    at Object.startApp (/Users/user/Sites/project/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:104:16)
    at /Users/user/Sites/project/node_modules/ionic/lib/ionic/start.js:91:18
    at _fulfilled (/Users/user/Sites/project/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/user/Sites/project/node_modules/ionic/node_modules/q/q.js:816:30)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

$ ls -la ./project
ls: ./project: No such file or directory
```

What's the proper way to do this?

**Comment by etsuo** [comment]
It seems that this was proposed and rejected in #3801.

The Angular2 CLI supports this.

Our use-case is pretty simple... we follow something close to git-flow. We start with a master branch that's just README, .gitignore, and LICENSE... from there we branch a develop branch and we init the project there. 

Because ionic cli doesn't support starting a project in an existing directory, we end up having to init in another directory then we copy over all the files... it's not the end of the world, but it's extra steps that seem unnecessary.

I propose we get a warning that we're initializing in an existing directory, and after we confirm that's what we really want to do, Ionic either overwrites what's there, or doesn't overwrite existing files, or prompts file by file... doesn't really matter to me.

We do this all the time with the Angular CLI and the world hasn't ended (though I have no way of confirming that I haven't actually triggered the apocalypse... I guess it's just a risk I'm willing to take). :)

**Comment by dwieeb** [comment]
This is a feature request we're hesitant to add. In Ionic 4, we're all-in on Angular tooling, so that may mean creating schematics for `ng add`, which I just made an issue for: https://github.com/ionic-team/ionic-cli/issues/3369

Closing this, as it's a feature request for v3.
