### ISSUE TITLE
"ionic start myApp tabs" fails, but "ionic start myApp sidemenu" works fine.

### ISSUE THREAD

**Issue by longminghong** [ionic-team/ionic-cli#1310]
Creating Ionic app in folder /Users/longminghong/Desktop/CLI/myApp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error with start Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:78:26)
Error Initializing app: Error: getaddrinfo ENOTFOUND github.com github.com:443
 Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:78:26)
Caught exception:
 Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:78:26)

**Comment by robertolabarca** [comment]
i have the same problem. How to get file to disk folder ?

**Comment by WJanbaz** [comment]
Having the same problem. Anyone solved it and how?

**Comment by WJanbaz** [comment]
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Error Initializing app: Error: getaddrinfo ENOTFOUND github.com github.com:443
 Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
