### ISSUE TITLE
installed npm ionic cordova and got this error when i tried to start a new project

### ISSUE THREAD

**Issue by ramcpp** [ionic-team/ionic-cli#1318]
ionic start KidsActivities sidemenu
Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

**Comment by moduld** [comment]
I have the same. I tried node 6.5 and 4.5 - no difference.

**Comment by areijngoudt** [comment]
I solved this using 
```
npm install -g lodash
```

and after getting the same kind of error for inherits
```
npm install -g inherits
```
