### ISSUE TITLE
Windows 10 - android app building error 

### ISSUE THREAD

**Issue by tuyendn** [ionic-team/ionic-cli#1322]
Just tried to build android app in Windows 10 but there are many errors occurred
Very strange and i could not understand at all. 

So, please tell me what's wrong or is this bug of ionic 2 ?

add to body class: platform-android

ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk

JAVA_HOME=C:\Program Files (x86)\Java\jdk1.7.0_79

Starting a new Gradle Daemon for this build (subsequent builds will be faster).

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules_defined.js:3:28)
    at createHTML (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules_string-html.js:7:19)
    at bold (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules\es6.string.bold.js:5:12)
    at cb (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:206:7)
    at done (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:167:19)
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:40:16
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:193:9
    at Console.log (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\transports\console.js:127:3)
    at emit (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:186:17)
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:157:13
    at _each (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:156:9)
    at Logger.log (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:214:9)
    at target.(anonymous function) [as error](C:UsersSanAppDataRoamingnpmnode_modulesionicnode_modulesionic-app-libnode_moduleswinstonlibwinstoncommon.js:54:18)
    at Socket.<anonymous> (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\lib\utils\cordova.js:83:11)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

BUILD FAILED

Total time: 3.392 secs

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules_defined.js:3:28)
    at createHTML (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules_string-html.js:7:19)
    at bold (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules\es6.string.bold.js:5:12)
    at cb (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:206:7)
    at done (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:167:19)
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:40:16
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:193:9
    at Console.log (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\transports\console.js:127:3)
    at emit (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:186:17)
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:157:13
    at _each (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:156:9)
    at Logger.log (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:214:9)
    at target.(anonymous function) [as error](C:UsersSanAppDataRoamingnpmnode_modulesionicnode_modulesionic-app-libnode_moduleswinstonlibwinstoncommon.js:54:18)
    at Socket.<anonymous> (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\lib\utils\cordova.js:83:11)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules_defined.js:3:28)
    at createHTML (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules_string-html.js:7:19)
    at bold (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules\es6.string.bold.js:5:12)
    at cb (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:206:7)
    at done (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:167:19)
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:40:16
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:193:9
    at Console.log (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\transports\console.js:127:3)
    at emit (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:186:17)
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:157:13
    at _each (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:156:9)
    at Logger.log (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:214:9)
    at target.(anonymous function) [as error](C:UsersSanAppDataRoamingnpmnode_modulesionicnode_modulesionic-app-libnode_moduleswinstonlibwinstoncommon.js:54:18)
    at Socket.<anonymous> (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\lib\utils\cordova.js:83:11)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules_defined.js:3:28)
    at createHTML (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules_string-html.js:7:19)
    at bold (D:\Todo\tsunagu\tsunagu-mobile\node_modules\core-js\modules\es6.string.bold.js:5:12)
    at cb (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:206:7)
    at done (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:167:19)
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:40:16
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:193:9
    at Console.log (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\transports\console.js:127:3)
    at emit (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:186:17)
    at C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:157:13
    at _each (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:156:9)
    at Logger.log (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:214:9)
    at target.(anonymous function) [as error](C:UsersSanAppDataRoamingnpmnode_modulesionicnode_modulesionic-app-libnode_moduleswinstonlibwinstoncommon.js:54:18)
    at Socket.<anonymous> (C:\Users\San\AppData\Roaming\npm\node_modules\ionic\lib\utils\cordova.js:83:11)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jaworskm** [comment]
Same issue. +1

```
$ ionic run android
Running command: /Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/hooks/after_prepare/010_add_platform_class.js /Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid


add to body class: platform-android

Running command: /Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/hooks/after_prepare/020_copy_android_icon.js /Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid


Running hook: 020_copy_android_icon.js

ANDROID_HOME=/usr/local/opt/android-sdk

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home

No target specified, deploying to device 'fadbca4b'.

embedded


org.xwalk:xwalk_core_library:15+


Observed package id '..;..;..;var;lib;android-sdk;samples;android-10' in inconsistent location '/usr/local/opt/android-sdk/samples/android-10' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-10')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-11' in inconsistent location '/usr/local/opt/android-sdk/samples/android-11' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-11')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-12' in inconsistent location '/usr/local/opt/android-sdk/samples/android-12' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-12')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-13' in inconsistent location '/usr/local/opt/android-sdk/samples/android-13' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-13')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-14' in inconsistent location '/usr/local/opt/android-sdk/samples/android-14' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-14')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-15' in inconsistent location '/usr/local/opt/android-sdk/samples/android-15' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-15')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-16' in inconsistent location '/usr/local/opt/android-sdk/samples/android-16' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-16')

Observed package id '..;..;..;var;lib;android-sdk;samples;android-17' in inconsistent location '/usr/local/opt/android-sdk/samples/android-17' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-17')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-18' in inconsistent location '/usr/local/opt/android-sdk/samples/android-18' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-18')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-19' in inconsistent location '/usr/local/opt/android-sdk/samples/android-19' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-19')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-20' in inconsistent location '/usr/local/opt/android-sdk/samples/android-20' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-20')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-21' in inconsistent location '/usr/local/opt/android-sdk/samples/android-21' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-21')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-22' in inconsistent location '/usr/local/opt/android-sdk/samples/android-22' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-22')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-23' in inconsistent location '/usr/local/opt/android-sdk/samples/android-23' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-23')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-7' in inconsistent location '/usr/local/opt/android-sdk/samples/android-7' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-7')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-8' in inconsistent location '/usr/local/opt/android-sdk/samples/android-8' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-8')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-9' in inconsistent location '/usr/local/opt/android-sdk/samples/android-9' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-9')


Observed package id '..;..;..;var;lib;android-sdk;samples;android-MNC' in inconsistent location '/usr/local/opt/android-sdk/samples/android-MNC' (Expected '/usr/local/opt/android-sdk/../../../var/lib/android-sdk/samples/android-MNC')


Incremental java compilation is an incubating feature.


:preBuild
 UP-TO-DATE


:preArmv7DebugBuild
 UP-TO-DATE

:checkArmv7DebugManifest


:preX86DebugBuild
 UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE

:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk
 UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
 
UP-TO-DATE
:CordovaLib:packageDebugRenderscript
 
UP-TO-DATE

:CordovaLib:checkDebugManifest


:CordovaLib:prepareDebugDependencies


:CordovaLib:compileDebugRenderscript
 
UP-TO-DATE
:CordovaLib:generateDebugResValues
 
UP-TO-DATE
:CordovaLib:generateDebugResources
 UP-TO-DATE

:CordovaLib:packageDebugResources
 
UP-TO-DATE
:CordovaLib:compileDebugAidl
 
UP-TO-DATE
:CordovaLib:generateDebugBuildConfig
 
UP-TO-DATE
:CordovaLib:mergeDebugShaders
 
UP-TO-DATE
:CordovaLib:compileDebugShaders
 
UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
 UP-TO-DATE

:CordovaLib:processDebugManifest
 UP-TO-DATE

:CordovaLib:processDebugResources
 
UP-TO-DATE
:CordovaLib:generateDebugSources
 UP-TO-DATE


:CordovaLib:incrementalDebugJavaCompilationSafeguard
 
UP-TO-DATE

:CordovaLib:compileDebugJavaWithJavac
 UP-TO-DATE

:CordovaLib:processDebugJavaRes
 
UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
 
UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
 UP-TO-DATE

:CordovaLib:mergeDebugJniLibFolders
 
UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
 
UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
 
UP-TO-DATE
:CordovaLib:bundleDebug
 
UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
 
UP-TO-DATE
:preArmv7ReleaseBuild UP-TO-DATE
:preX86ReleaseBuild 
UP-TO-DATE

:CordovaLib:preReleaseBuild 
UP-TO-DATE
:CordovaLib:compileReleaseNdk
 UP-TO-DATE

:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
 UP-TO-DATE

:CordovaLib:generateReleaseResValues
 
UP-TO-DATE

:CordovaLib:generateReleaseResources
 UP-TO-DATE
:CordovaLib:packageReleaseResources
 
UP-TO-DATE
:CordovaLib:compileReleaseAidl
 UP-TO-DATE

:CordovaLib:generateReleaseBuildConfig
 UP-TO-DATE

:CordovaLib:mergeReleaseShaders UP-TO-DATE
:CordovaLib:compileReleaseShaders
 
UP-TO-DATE
:CordovaLib:generateReleaseAssets 
UP-TO-DATE

:CordovaLib:mergeReleaseAssets
 
UP-TO-DATE
:CordovaLib:processReleaseManifest
 
UP-TO-DATE

:CordovaLib:processReleaseResources
 
UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE

:CordovaLib:incrementalReleaseJavaCompilationSafeguard
 
UP-TO-DATE

:CordovaLib:compileReleaseJavaWithJavac
 
UP-TO-DATE

:CordovaLib:processReleaseJavaRes
 UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
 UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
 UP-TO-DATE

:CordovaLib:mergeReleaseJniLibFolders
 
UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
 
UP-TO-DATE

:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
 
UP-TO-DATE
:CordovaLib:bundleRelease
 
UP-TO-DATE
:prepareComAndroidSupportCardviewV72340Library
 
UP-TO-DATE
:prepareComAndroidSupportSupportV132340Library
 
UP-TO-DATE
:prepareComAndroidSupportSupportV42340Library
 
UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase940Library
 UP-TO-DATE

:prepareComGoogleAndroidGmsPlayServicesBasement940Library
 
UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm940Library
 
UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesIid940Library
 
UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesLocation940Library
 
UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks940Library
 
UP-TO-DATE

:prepareComUrbanairshipAndroidUrbanairshipSdk720Library
 
UP-TO-DATE

:prepareMeLeolinShortcutBadger114Library
 
UP-TO-DATE
:prepareOrgXwalkXwalk_core_library154438413Library
 
UP-TO-DATE
:prepareArmv7DebugDependencies


:compileArmv7DebugAidl
 
UP-TO-DATE
:compileArmv7DebugRenderscript
 
UP-TO-DATE
:generateArmv7DebugBuildConfig


:mergeArmv7DebugShaders
 
UP-TO-DATE
:compileArmv7DebugShaders
 UP-TO-DATE

:generateArmv7DebugAssets
 UP-TO-DATE
:mergeArmv7DebugAssets


:createXwalkCommandLineFileArmv7Debug


:generateArmv7DebugResValues
 
UP-TO-DATE

:generateArmv7DebugResources UP-TO-DATE


:mergeArmv7DebugResources


:processArmv7DebugManifest


:processArmv7DebugResources


:generateArmv7DebugSources
:incrementalArmv7DebugJavaCompilationSafeguard


:compileArmv7DebugJavaWithJavac


:compileArmv7DebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).


Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as error] (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as error] (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

:compileArmv7DebugNdk
 
UP-TO-DATE
:compileArmv7DebugSources


:prePackageMarkerForArmv7Debug


:transformClassesWithDexForArmv7Debug


To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 910 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html

:mergeArmv7DebugJniLibFolders
 
UP-TO-DATE
:transformNative_libsWithMergeJniLibsForArmv7Debug
 UP-TO-DATE

:processArmv7DebugJavaRes
 UP-TO-DATE

:transformResourcesWithMergeJavaResForArmv7Debug
 UP-TO-DATE

:validateDebugSigning


:packageArmv7Debug


:zipalignArmv7Debug


:assembleArmv7Debug
:cdvBuildDebug




BUILD SUCCESSFUL


Total time: 13.167 secs

Built the following apk(s): 
        /Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/platforms/android/build/outputs/apk/android-armv7-debug.apk

Using apk: /Users/jaworskm/Development/EAB/tri-lambda-ui/hybrid/platforms/android/build/outputs/apk/android-armv7-debug.apk
```

**Comment by jaworskm** [comment]
+1 for `ionic platform add android` 

```
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.0 Build version 8A218a 
```
