### ISSUE TITLE
ionic start error 407: Tunneling socket could not be established

### ISSUE THREAD

**Issue by PC-Chan** [ionic-team/ionic-cli#1325]
Trying to run CLI command on Mac, `ionic start HelloWorld --v2', return below error which it related to proxy authentication failure. Is there any command to set proxy for ionic? 

Error lines:

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: tunneling socket could not be established, statusCode=407
    at ClientRequest.onConnect (/usr/local/lib/node_modules/ionic/node_modules/request/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
Error Initializing app: Error: tunneling socket could not be established, statusCode=407
 Error: tunneling socket could not be established, statusCode=407
    at ClientRequest.onConnect (/usr/local/lib/node_modules/ionic/node_modules/request/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
Caught exception:
 Error: tunneling socket could not be established, statusCode=407
    at ClientRequest.onConnect (/usr/local/lib/node_modules/ionic/node_modules/request/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by pkswasaran** [comment]
Just set proxy for your environment..

c:\>set http_proxy=http://yourproxyaddress:port

**Comment by bdbais** [comment]
thank you to @pkswasaran I just add another thing, I found a little error, very similar to this and the solution is the same :)


```
C:\projects\ionic>set http_proxy="http://proxy.university.net:8080"

C:\projects\ionic>ionic start ng
Creating Ionic app in folder C:\projects\ionic\ng based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error with start Error: tunneling socket could not be established, cause=Parse E
rror
    at ClientRequest.onError (C:\Users\user\AppData\Roaming\npm\node_modules\ion
ic\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnData (_http_client.js:366:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
Error Initializing app: Error: tunneling socket could not be established, cause=
Parse Error
 Error: tunneling socket could not be established, cause=Parse Error
    at ClientRequest.onError (C:\Users\user\AppData\Roaming\npm\node_modules\ion
ic\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnData (_http_client.js:366:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
Caught exception:
 Error: tunneling socket could not be established, cause=Parse Error
    at ClientRequest.onError (C:\Users\user\AppData\Roaming\npm\node_modules\ion
ic\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnData (_http_client.js:366:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

the error was  " " ... removed them and it works :) absurd but okay, world is beautyfull because is fill of surprises :)

C:\projects\ionic>set http_proxy=http://proxy.university.net:8080

C:\projects\ionic>ionic start ng
Creating Ionic app in folder C:\projects\ionic\ng based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...

**Comment by csvan** [comment]
The workaround suggested by @pkswasaran does not seem to work if the proxy requires a username and password.

**Comment by dwieeb** [comment]
@csvan But you can do this, right? `http_proxy=http://USERNAME:PASSWORD@PROXYIP:PROXYPORT`
