### ISSUE TITLE
ionic state save   NOT WORKING -  TypeError: Cannot read property 'LOG_LEVEL' of null    

### ISSUE THREAD

**Issue by endriazizi** [ionic-team/ionic-cli#1333]
Hi there, 
why is not working the command:
`ionc state save 
`
I got the following error:

```
`Restore platforms is complete                                                                                                                                                                       

Restoring Plugins                                                                                                                                                                                   

cordova plugin add cordova-plugin-device                                                                                                                                                            
cordova plugin add cordova-plugin-console                                                                                                                                                           
cordova plugin add cordova-plugin-whitelist                                                                                                                                                         
cordova plugin add cordova-plugin-splashscreen                                                                                                                                                      
cordova plugin add cordova-plugin-statusbar                                                                                                                                                         
cordova plugin add ionic-plugin-keyboard                                                                                                                                                            
cordova plugin add cordova-plugin-inappbrowser                                                                                                                                                      
cordova plugin add cordova-plugin-geolocation                                                                                                                                                       
cordova plugin add cordova-plugin-compat                                                                                                                                                            
cordova plugin add cordova-plugin-secure-storage                                                                                                                                                    
cordova plugin add cordova-plugin-crosswalk-webview                                                                                                                                                 
cordova plugin add cordova-plugin-network-information                                                                                                                                               
cordova plugin add cordova-plugin-x-socialsharing                                                                                                                                                   
cordova plugin add cordova-plugin-facebook4 --variable APP_ID="966508260075659" --variable APP_NAME:="VirginRevolutionSocialLogin"                                                                  
cordova plugin add pushwoosh-cordova-plugin                                                                                                                                                         
Restore plugins is complete                                                                                                                                                                         

Ionic state restore completed                                                                                                                                                                       


c:\Users\endriazizi\Desktop\cazzo\virginrevolutionapp>ionic state save                                                                                                                              
Saving your Ionic app state of platforms and plugins                                                                                                                                                
Saved platform                                                                                                                                                                                      
There was an error saving your current Ionic setup                                                                                                                                                  
 TypeError: Cannot read property 'LOG_LEVEL' of null                                                                                                                                                
    at C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\state.js:259:34                                                                                    
    at Array.forEach (native)                                                                                                                                                                       
    at Object.saveExistingPlugins (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\state.js:250:24)                                                       
    at Object.saveState (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\state.js:73:11)                                                                  
    at Object.run (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\lib\ionic\state.js:55:11)                                                                                             
    at Promise.apply (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1078:26)                                                                                       
    at Promise.promise.promiseDispatch (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:741:41)                                                                      
    at C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1304:14                                                                                                       
    at flush (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)                                                                                                
    at _combinedTickCallback (internal/process/next_tick.js:67:7)                                                                                                                                   

c:\Users\endriazizi\Desktop\cazzo\virginrevolutionapp>    `
```

**Comment by MathieuDuboy** [comment]
same issue ! And my package.json does not have plugins saved in it ...

**Comment by endriazizi** [comment]
You can put them into package.json 
ionic platform rm android
Ionic platform add android 
You will get all the plugin declared into package.json

Unfortunately ionic state save doesn't work for me

But doing as I said above
This restore all plugins into all the platform

Let me know if it works for you
