### ISSUE TITLE
 Error: Cannot find module 'inherits'

### ISSUE THREAD

**Issue by padrian** [ionic-team/ionic-cli#1354]
the command below fails and returns the error shown below.

sudo ionic run android -l -c --address 10.1.7.213

```Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/glob/glob.js:42:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17) 

Mind letting us know? 

 https://github.com/driftyco/ionic-cli/issues```

**Comment by ophedian** [comment]
I am experiencing the same issue. See error information below
**ionic start Mobile tutorial --v2**

_**Caught exception:**_
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Abbey\AppData\Roaming\npm\node_modules\ionic\node_modules\glob\glob.js:42:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by padrian** [comment]
Uninstalling and reinstalling the ionic framework helped me fix this.

For my case i had deleted some files, thats where the problem originated.
