### ISSUE TITLE
Error: ionic start myApp tabs

### ISSUE THREAD

**Issue by TaceyWong** [ionic-team/ionic-cli#1359]
``` bash
 $ ionic start myApp tabs
Creating Ionic app in folder /home/tacey/WebstormProjects/App/myApp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error with start Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Error Initializing app: Error: connect ECONNREFUSED
 Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Caught exception:
 Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19) 

```

*_There are some errors like this ,while I can download that ZIP file by browser/wget *_

**Comment by TimothyCuthbert** [comment]
I removed ionic and cordova and started over.
