### ISSUE TITLE
'inherits' error - tried everything (uninstall node, re-install, etc) - please help solve this

### ISSUE THREAD

**Issue by lisaiceland** [ionic-team/ionic-cli#1367]
Lisas-MacBook-Pro:~ lisakristinardottir$ node -v
v6.5.0
Lisas-MacBook-Pro:~ lisakristinardottir$ npm -v
3.10.3
Lisas-MacBook-Pro:~ lisakristinardottir$ ionic info
Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/glob/glob.js:42:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Lisas-MacBook-Pro:~ lisakristinardottir$ 

I can't intall ionic or run it or nothing! Please help in this. Much appreciated. Lis

**Comment by Jeyanthinath** [comment]
try reinstalling ionic using ionic@latest

**Comment by lisaiceland** [comment]
FIXED!
