### ISSUE TITLE
getting error while creating ionic app

### ISSUE THREAD

**Issue by 1188Prashant** [ionic-team/ionic-cli#1373]
Creating Ionic app in folder D:\prashant\App based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error with start Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:1008:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:79:26)
Error Initializing app: Error: getaddrinfo EAI_AGAIN github.com:443
 Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:1008:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:79:26)
Caught exception:
 Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:1008:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:79:26)

How can I get Solution for this?

**Comment by sibin-p** [comment]
I too got this error once today. I tried again and command worked without
