### ISSUE TITLE
Cannot find module 'inherits'

### ISSUE THREAD

**Issue by Kimliang** [ionic-team/ionic-cli#1404]
Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\kimli\AppData\Roaming\npm\node_modules\ionic\node_modules\glob\glob.js:42:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by btsiders** [comment]
I just had this issue when trying to start a new v2 project. Fixed it with:

```
npm uninstall ionic -g
npm install ionic -g
```

**Comment by msegers** [comment]
@jthoms1 
```
 ionic info
Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/glob/glob.js:42:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

```

This is my output I'm trying to update since I was still on Angular2 RC 4

**Comment by msegers** [comment]
That is interesting @btsiders 's solution seems to work for me as well.

Was not expecting so!

**Comment by zdsantos** [comment]
I'm having the same problem but with module 'extend'

 - ionic info:
Caught exception:
 Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/request/index.js:17:29)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jcoppieters** [comment]
Hello,

having the same problem, same error.
tried uninstall/install cordova and ionic -g, nothing helps... can't do ionic info

stuck with the first project.

node --version
v6.10.1
$ nvm --version
0.33.1
$ cordova --version
6.5.0
$ uname -v
Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64

Johan.
