### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by fuggfuggfugg** [ionic-team/ionic-cli#1434]
`ionic g provider birthday`

```
TypeError: undefined is not a function
    at /Users/xxxx/.node/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:23939:22
    at Array.filter (native)
    at filterAndCleanUpTemplates (/Users/xxxx/.node/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:23938:8)
    at Generator.renderAndWriteTemplates (/Users/xxxx/.node/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25310:133)
    at /Users/xxxx/.node/lib/node_modules/ionic/node_modules/@ionic/app-generators/index.js:25304:26


Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 7.3.1 Build version 7D1014

```

**Comment by Abhith** [comment]
same issue while running ionic g page somename

```
ionic g page dashboard                                                                                                      
                                                                                                                                                                                              
TypeError: undefined is not a function                                                                                                                                                        
    at C:\Users\xxxx\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\app-generators\index.js:23939:22                                                                            
    at Array.filter (native)                                                                                                                                                                  
    at filterAndCleanUpTemplates (C:\Users\xxxx\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\app-generators\index.js:23938:8)                                                 
    at Generator.renderAndWriteTemplates (C:\Users\xxxx\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\app-generators\index.js:25310:133)                                       
    at C:\Users\xxxx\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\app-generators\index.js:25304:26  
 undefined is not a function (CLI v2.1.0)                                                                                                                                                      
                                                                                                                                                                                              
Your system information:                                                                                                                                                                      
                                                                                                                                                                                              
Cordova CLI: 6.1.1                                                                                                                                                                            
Gulp version:  CLI version 3.9.1                                                                                                                                                              
Gulp local:                                                                                                                                                                                   
Ionic Framework Version: 2.0.0-rc.0                                                                                                                                                           
Ionic CLI Version: 2.1.0                                                                                                                                                                      
Ionic App Lib Version: 2.0.0-beta.20                                                                                                                                                          
OS: Windows 8.1                                                                                                                                                                               
Node Version: v0.12.2 
```

**Comment by elsawy269** [comment]
+1

**Comment by Abhith** [comment]
Updating npm to v3 by updating node from v4 to v6 solved my issue.
