### ISSUE TITLE
Error while creating starter App.

### ISSUE THREAD

**Issue by shriduttkothari** [ionic-team/ionic-cli#1437]
D:\Shridutt\My Work\ODMS\IONIC>ionic start myApp blank
Creating Ionic app in folder D:\Shridutt\My Work\ODMS\IONIC\myApp based on blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Error with start Error: ENOENT: no such file or directory, open 'C:\Users\shridutt.kothari\AppData\Local\Temp;D:\Development\Andorid_SDk_4_new\android-sdk-windows\tools\templates\gradle\wrapper\ionic-starter-1475228469082.zip'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Request._callback (D:\Development\nodejs\node_modules\ionic\node_modules\ionic-app-lib\lib\utils.js:121:10)
    at Request.self.callback (D:\Development\nodejs\node_modules\ionic\node_modules\request\request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (D:\Development\nodejs\node_modules\ionic\node_modules\request\request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
Error Initializing app: Error: ENOENT: no such file or directory, open 'C:\Users\shridutt.kothari\AppData\Local\Temp;D:\Development\Andorid_SDk_4_new\android-sdk-windows\tools\templates\gradle\wrapper\ionic-starter-1475228469082.zip'
 Error: ENOENT: no such file or directory, open 'C:\Users\shridutt.kothari\AppData\Local\Temp;D:\Development\Andorid_SDk_4_new\android-sdk-windows\tools\templates\gradle\wrapper\ionic-starter-1475228469082.zip'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Request._callback (D:\Development\nodejs\node_modules\ionic\node_modules\ionic-app-lib\lib\utils.js:121:10)
    at Request.self.callback (D:\Development\nodejs\node_modules\ionic\node_modules\request\request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (D:\Development\nodejs\node_modules\ionic\node_modules\request\request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
Caught exception:
 Error: ENOENT: no such file or directory, open 'C:\Users\shridutt.kothari\AppData\Local\Temp;D:\Development\Andorid_SDk_4_new\android-sdk-windows\tools\templates\gradle\wrapper\ionic-starter-1475228469082.zip'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Request._callback (D:\Development\nodejs\node_modules\ionic\node_modules\ionic-app-lib\lib\utils.js:121:10)
    at Request.self.callback (D:\Development\nodejs\node_modules\ionic\node_modules\request\request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (D:\Development\nodejs\node_modules\ionic\node_modules\request\request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by thomaswb** [comment]
I am getting exactly the same problem, on Mac OS 10.12. So I can't create a new RC project.

npm 2.15.9 (this is the latest npm, despite the RC release notes saying you need 3.x)

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by raju1979** [comment]
I am also facing same issue while creating new project
Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:Win-10
Node Version: v6.3.1
NPM 3.10.3
