### ISSUE TITLE
Ionic v2 starter template named "complex-list" does not work

### ISSUE THREAD

**Issue by jdat82** [ionic-team/ionic-cli#1464]
``` bash
$ ionic start -l

Downloading Starter Templates - http://code.ionicframework.com/content/starter-templates.json
Ionic Starter templates

blank ................ A blank starter project for Ionic
complex-list ......... A complex list starter template
maps ................. An Ionic starter project using Google Maps and a side menu
salesforce ........... A starter project for Ionic and Salesforce
sidemenu ............. A starting project for Ionic using a side menu with navigation in the content area
tabs ................. A starting project for Ionic using a simple tabbed interface

$ ionic start --v2 complex-list -t complex-list 
Creating Ionic app in folder /Users/Jean/Developer/Projects/testing-ionicv2/complex-list based on complex-list project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Error with start Error: No starter template named "complex-list"
    at Object.Start.fetchIonicStarter (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:499:13)
    at Object.Start.fetchSeed (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:255:16)
    at /Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
Error Initializing app: Error: No starter template named "complex-list"
 Error: No starter template named "complex-list"
    at Object.Start.fetchIonicStarter (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:499:13)
    at Object.Start.fetchSeed (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:255:16)
    at /Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
Caught exception:
 Error: No starter template named "complex-list"
    at Object.Start.fetchIonicStarter (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:499:13)
    at Object.Start.fetchSeed (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:255:16)
    at /Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/Users/Jean/.nvm/versions/node/v5.5.0/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

Indeed repo at location `https://github.com/driftyco/ionic-starter-complex-list` is empty. At least, the `complex-list` item should not be listed by command `ionic start -l`.

**Comment by tpesce** [comment]
I ran into this same issue today. However, things worked if I used the "complex-list" template to start a v1 project:

```
$ ionic start test complex-list
Creating Ionic app in folder /Users/tim/Projects/SixActual/ag/test based on complex-list project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-complex-list/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...

Adding initial native plugins
[=============================]  100%  0.0s

Adding in iOS application by default

add to body class: platform-ios
Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.zip
[=============================]  100%  0.0s
Saving your Ionic app state of platforms and plugins
Saved platform
Saved plugins
Saved package.json

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Some helpful tips:

Run your app in the browser (great for initial development):
  ionic serve

Run on a device or simulator:
  ionic run ios[android,browser]

Test and share your app on device with Ionic View:
  http://view.ionic.io

Build better Enterprise apps with expert Ionic support:
  http://ionic.io/enterprise

New! Add push notifications, live app updates, and more with Ionic Cloud!
  https://apps.ionic.io/signup
```

```
$ ionic info

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 
```

**Comment by Eddie541** [comment]
Using 'ionic start project-name complex-list' creates a blank project and, as described, only works for v1

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.4

**Comment by jdat82** [comment]
It may be a v1 template only, no problem at all but I do not see any mention of that anywhere whether it is the command line or the github repository. 

Plus in a perfect world: `ionic start --v2 -l` should only list v2 templates ; or as a fallback, mention which version they support. 

Not the end of the world but I think that kind of details is important for true beginners that want to test it for the first time in order to have an opinion. I see a lot of broken little things nowadays. Hope they will find time after releasing IONIC 2 to update the documentation and things like that.
