### ISSUE TITLE
Moving file during live update

### ISSUE THREAD

**Issue by gdeardorff** [ionic-team/ionic-cli#1488]
Moved the file listed within the IDE while running in live update mode "ionic serve"

ionic $ HTML changed: www/templates/tab-dash.html
Caught exception:
 Error: watch /Users/garydeardorff/development/ionic/ionicpoker/www/templates ENOENT
    at exports._errnoException (util.js:1008:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/usr/local/lib/node_modules/ionic/node_modules/gaze/lib/gaze.js:289:30)
    at /usr/local/lib/node_modules/ionic/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/usr/local/lib/node_modules/ionic/node_modules/gaze/lib/helper.js:52:5)
    at /usr/local/lib/node_modules/ionic/node_modules/gaze/lib/helper.js:61:11
    at /usr/local/lib/node_modules/ionic/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/usr/local/lib/node_modules/ionic/node_modules/gaze/lib/helper.js:52:5)
    at /usr/local/lib/node_modules/ionic/node_modules/gaze/lib/helper.js:61:11

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

restarted server

**Comment by jthoms1** [comment]
Can I assume that once you restarted the server that further changes worked correctly?

Also could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
