### ISSUE TITLE
Ionic 2 RC1 Ionic serve bring-up failure with Linux 4.4.0-42-generic(Ubuntu 16.04.1 LTS) / node v6.8.1/npm  v3.10.8

### ISSUE THREAD

**Issue by jing-zhou** [ionic-team/ionic-cli#1547]
#### Short description of the problem:

ionic serve -l -s -c  failed with the following prompts:

```
wjz@bj:~/ion/vajra$ ionic serve -l -s -c 

Running 'serve:before' npm script before serve

> ionic-hello-world@ watch /home/wjz/ion/vajra
> ionic-app-scripts watch

/home/wjz/ion/vajra/node_modules/node-sass/lib/index.js:15
    throw new Error(errors.missingBinary());
    ^

Error: Missing binding /home/wjz/ion/vajra/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/home/wjz/ion/vajra/node_modules/node-sass/lib/index.js:15:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/wjz/ion/vajra/node_modules/@ionic/app-scripts/dist/sass.js:8:19)
    at Module._compile (module.js:570:32)

npm ERR! Linux 4.4.0-42-generic
npm ERR! argv "/home/wjz/.nvm/versions/node/v6.8.1/bin/node" "/home/wjz/.nvm/versions/node/v6.8.1/bin/npm" "run" "watch" "--color"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wjz/ion/vajra/npm-debug.log
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

wjz@bj:~/ion/vajra$ 

```
#### What behavior are you expecting?

the ionic server should come up and application splashes in browser

**Steps to reproduce:**
1 .nvm install v6.8.1
2. npm install -g ionic
3. npm install -g cordova
4. npm install
5. ionic serve -l -s -c

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

```
wjz@bj:~/ion/vajra$ ionic info
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.34
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04.1 LTS 
Node Version: v6.8.1


--------------------------------

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

npm-debug.log 

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/wjz/.nvm/versions/node/v6.8.1/bin/node',
1 verbose cli   '/home/wjz/.nvm/versions/node/v6.8.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch',
1 verbose cli   '--color' ]
2 info using npm@3.10.8
3 info using node@v6.8.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle ionic-hello-world@~prewatch: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prewatch: no script for prewatch, continuing
7 info lifecycle ionic-hello-world@~watch: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~watch: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~watch: PATH: /home/wjz/.nvm/versions/node/v6.8.1/lib/node_modules/npm/bin/node-gyp-bin:/home/wjz/ion/vajra/node_modules/.bin:/home/wjz/.nvm/versions/node/v6.8.1/bin:/home/wjz/bin:/home/wjz/.local/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle ionic-hello-world@~watch: CWD: /home/wjz/ion/vajra
11 silly lifecycle ionic-hello-world@~watch: Args: [ '-c', 'ionic-app-scripts watch' ]
12 silly lifecycle ionic-hello-world@~watch: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~watch: Failed to exec watch script
14 verbose stack Error: ionic-hello-world@ watch: `ionic-app-scripts watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/wjz/.nvm/versions/node/v6.8.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/wjz/.nvm/versions/node/v6.8.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /home/wjz/ion/vajra
17 error Linux 4.4.0-42-generic
18 error argv "/home/wjz/.nvm/versions/node/v6.8.1/bin/node" "/home/wjz/.nvm/versions/node/v6.8.1/bin/npm" "run" "watch" "--color"
19 error node v6.8.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ionic-hello-world@ watch: `ionic-app-scripts watch`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by jthoms1** [comment]
@jing-zhou This looks like an error with node-sass.  Could you try running `npm rebuild node-sass` like the output suggests?  If you are still having issues try deleting the node_modules directory and rerunning `npm install`. Thanks!
