### ISSUE TITLE
Caught exception during setting up ionic

### ISSUE THREAD

**Issue by umairmumtaz-sellanycar** [ionic-team/ionic-cli#1623]
Hi,

I got following exception:

1. Ran npm install -g ionic
2. Ran ionic setup sass

Caught exception:
 TypeError: Cannot read property 'bold' of undefined
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/setup.js:144:49)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by stefanoschrs** [comment]
@umairmumtaz-sellanycar I had the same issue on node v4.6.1 and I updated to v7.2.1 and the problem is solved

**Comment by hectorggp** [comment]
I have the same issue, with ionic 2.2.1 and npm v7.5.0. Please, help
