### ISSUE TITLE
ionic cli does not exit with error code to bash when there are compiling errors

### ISSUE THREAD

**Issue by macolo** [ionic-team/ionic-cli#1627]
#### Short description of the problem:

ionic cli does not return an exit status of non-zero when `ionic build browser` fails. This makes it hard to programmatically determine whether the build process was successful or not, for example in a deploy script (I am using ansible).

#### What behavior are you expecting?

`ionic build browser` should show an exit status of non-zero when the build fails.

**Steps to reproduce:**

1) Make your build fail, for example introduce a typo to a depencency
2) build using `ionic build browser`
3) see the build fail
4) Check the exit status in bash with `echo $?`
5) See the returned code (its 0 instead of an error code like -1)

```
ppp@ppp-dev:/srv/www/ppp$ ionic build browser
Couldn't find ionic.config.json file. Are you in an Ionic project?
ppp@ppp-dev:/srv/www/ppp$ cd frontend/
ppp@ppp-dev:/srv/www/ppp/frontend$ ionic build browser

Running 'build:before' npm script before build
> PPP@ build /srv/www/ppp/frontend
> ionic-app-scripts build
[11:32:46]  ionic-app-scripts 0.0.34 
[11:32:46]  build prod started ... 
[11:32:46]  clean started ... 
[11:32:46]  clean finished in 7 ms 
[11:32:46]  copy started ... 
[11:32:46]  ngc started ... 
[11:32:47]  copy finished in 308 ms 
[11:32:47]  lint started ... 
[11:32:56]  lint finished in 8.48 s 
[11:33:18]  Error: Error at /srv/www/ppp/frontend/.tmp/pages/brand-search-success/brand-search-success.ngfactory.ts:226:40 

[11:33:18]  Property 'user' does not exist on type 'BrandSearchSuccessPage'. 
[11:33:18]  Error at /srv/www/ppp/frontend/.tmp/pages/brand-search-summary/brand-search-summary.ngfactory.ts:398:40 
[11:33:18]  Property 'user' does not exist on type 'BrandSearchSummaryPage'. 
[11:33:18]  ngc failed 
[11:33:18]  ionic-app-script task: "build" 
[11:33:18]  Error: Error 

npm
 
ERR!
 Linux 3.16.0-4-amd64

npm
 ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"

npm
 ERR! node v6.6.0
npm ERR! 
npm 
 v3.10.3
npm ERR! code ELIFECYCLE

npm
 ERR! Adecco_PPP@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm
 
ERR! 
npm ERR! Failed at the PPP@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Adecco_PPP package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PPP
npm
 ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PPP
npm ERR!
 There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www/ppp/frontend/npm-debug.log

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

ppp@ppp-dev:/srv/www/ppp/frontend$ echo $?
0
```

**Post the output of `ionic info` below please**
```
Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.6 (jessie) 
Node Version: v6.6.0


******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
```

**Comment by rolandjitsu** [comment]
I can confirm this for other commands as well. If I use `ionic login` and it fails, it still exits with code `0`.

**Comment by TheoAndersen** [comment]
Run the  build through npm instead, and it will use the right exit codes.

```> npm run build browser```

You can see the scripts that are run in package.json

**Comment by dwieeb** [comment]
This is fixed in the latest version of the CLI.
