### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by yurik94** [ionic-team/ionic-cli#1648]
When I type :

`ionic platform add android`

I get:

#TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.runr (C:\Users\Kevin\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:191:19)
    at C:\Users\Kevin\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:54:9
    at _fulfilled (C:\Users\Kevin\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Kevin\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Kevin\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\Kevin\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:557:44
    at flush (C:\Users\Kevin\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Cannot read property 'hasOwnProperty' of undefined (CLI v2.1.7)

Your system information:

 ordova CLI: 6.4.0
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by hatimox** [comment]
SAME problem please any fix?

**Comment by yurik94** [comment]
Maybe We could downgrade ionic cli but.. To which version?
On node 7.1.0 I can't even run ionic start

**Comment by hatimox** [comment]
yes it worked for me , install the version 2.0.0 of cli with node 6

**Comment by yurik94** [comment]
Thanks 😊

**Comment by delijati** [comment]
Fix:
```
replace:
if (npmScripts.hasOwnProperty(taskName + ':before') || npmScripts.hasOwnProperty(taskName + ':after')) {
with:
if (npmScripts && (npmScripts.hasOwnProperty(taskName + ':before') || npmScripts.hasOwnProperty(taskName + ':after'))) 
{{                                                                                     
in `ionic/lib/cli.js`
```

**Comment by birjega** [comment]
worked, but I suggest that it needs to be released quickly

**Comment by pioneersingh321** [comment]
@delijati thanks it works..
