### ISSUE TITLE
can not find module 'colors'

### ISSUE THREAD

**Issue by starkdigitalmediaservices** [ionic-team/ionic-cli#1650]
ionic serve
Caught exception:
 Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/cli.js:1:63)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by SamarkandTour** [comment]
I have a same issue when I tried this at Mac OS. 

ionic start MyIonic2Project tutorial --v2

**Comment by SamarkandTour** [comment]
But when I reinstalled ionic and cordova after uninstalling both, it works.

**Comment by jthoms1** [comment]
@starkdigitalmediaservices Could you try installing the latest ionic CLI release.

`npm install -g ionic@latest`
