### ISSUE TITLE
command [ionic platform add ios ] run wrong

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-cli#1657]
_From @aqnaruto on November 10, 2016 13:9_

i flowed the offical start document,and rebuild sever time s but  it is still not work 
![image](https://cloud.githubusercontent.com/assets/9067159/20177830/9b2b8756-a703-11e6-959f-87892b61d4fc.png)

```
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.runr (/usr/local/lib/node_modules/ionic/lib/cli.js:191:19)
    at /usr/local/lib/node_modules/ionic/lib/cli.js:54:9
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Cannot read property 'hasOwnProperty' of undefined (CLI v2.1.7)

Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.0.0
Xcode version: Xcode 8.0 Build version 8A218a
```

_Copied from original issue: driftyco/ionic#9109_

**Comment by brandyscarney** [comment]
_From @aqnaruto on November 10, 2016 14:26_

it also do not work on windows ,android .

**Comment by brandyscarney** [comment]
_From @aqnaruto on November 10, 2016 14:55_

i figure it out by adding`--v2` , but i think the offical document should update! it is really confused the document do not mentioned it

**Comment by aqnaruto** [comment]
when u init a project , u should add  version `--v2` such as `ionic start myapp tabs --v2` , if u still not work ,u can contract me in skype `ko_uchihasasuke@outlook.com`

**Comment by aqnaruto** [comment]
oh,thanks .

**Comment by superchenwb** [comment]
Thanks,You solved my problem
