### ISSUE TITLE
'ionic state reset' fails

### ISSUE THREAD

**Issue by jshin49** [ionic-team/ionic-cli#1663]
#### Short description of the problem:
'ionic state reset' fails 

#### What behavior are you expecting?

**Steps to reproduce:**
1. run ```sudo ionic state reset```

and the following error log shows:

```
Removed platforms and plugins
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device
Caught exception:
 undefined 
```
Mind letting us know? https://github.com/driftyco/ionic-cli/issues```

**Post the output of `ionic info` below please**

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 1.3.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

When running ```cordova plugin add cordova-plugin-device``` separately, the following error occurred:

```bash
Installing "cordova-plugin-device" for android
Failed to install 'cordova-plugin-device':CordovaError: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
    at /Users/jshin49/Desktop/dev/thehonorclub-mobileapp/platforms/android/cordova/lib/check_reqs.js:222:19
    at _fulfilled (/Users/jshin49/Desktop/dev/thehonorclub-mobileapp/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/jshin49/Desktop/dev/thehonorclub-mobileapp/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/jshin49/Desktop/dev/thehonorclub-mobileapp/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /Users/jshin49/Desktop/dev/thehonorclub-mobileapp/platforms/android/cordova/node_modules/q/q.js:857:14
    at runSingle (/Users/jshin49/Desktop/dev/thehonorclub-mobileapp/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/jshin49/Desktop/dev/thehonorclub-mobileapp/platforms/android/cordova/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
```

**Comment by Lestt** [comment]
Hi @jshin49,

As mentionned in the error message, you have to declare **ANDROID_HOME** or add to your **PATH** environnement variable the path to android sdk.
