### ISSUE TITLE
Installing cordova plugin fails

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1676]
#### Short description of the problem:
After cloning an app, running `npm install` and then `ionic run android` I get the following error: 
```
Installing ionic-plugin-keyboard
 Error: Command failed: cordova plugin add --save cordova-plugin-device

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
√ Installed platform android
```

**Steps to reproduce:**
1. Start a new app
2. Run `npm install`
3. Run `ionic run android`

**Post the output of `ionic info` below please**
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.0 Build version 8S201h

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by fernandoluizao** [comment]
Possibly related to https://github.com/driftyco/ionic-cli/issues/1673
