### ISSUE TITLE
ionic start myApp blank issue

### ISSUE THREAD

**Issue by Rahul000786** [ionic-team/ionic-cli#1680]
#### Short description of the problem:
ionic start myApp blank command fails with below error

#### What behavior are you expecting?

**Steps to reproduce:**
Creating Ionic app in folder D:\myApp based on blank
project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error with start Error: tunneling socket could not be established, statusCode=5
2
    at ClientRequest.onConnect (C:\nodejs_modules\node_modules\ionic\node_modul
s\request\node_modules\tunnel-agent\index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:391:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
Error Initializing app: Error: tunneling socket could not be established, statu
Code=502
 Error: tunneling socket could not be established, statusCode=502
    at ClientRequest.onConnect (C:\nodejs_modules\node_modules\ionic\node_modul
s\request\node_modules\tunnel-agent\index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:391:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
Caught exception:
 Error: tunneling socket could not be established, statusCode=502
    at ClientRequest.onConnect (C:\nodejs_modules\node_modules\ionic\node_modul
s\request\node_modules\tunnel-agent\index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:391:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**


Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Windows 7 SP1
Node Version: v6.2.1


**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
This appears to be an issue with network access from your machine.  Could you ensure that you are able to access the following url from your browser.

https://github.com/driftyco/ionic-app-base/archive/master.zip

**Comment by Rahul000786** [comment]
Hi , yes i have been able to download the https://github.com/driftyco/ionic-app-base/archive/master.zip   but still get above error on cli  ....any pointers ?
