### ISSUE TITLE
ionic 2 after create app then serve get this error 

### ISSUE THREAD

**Issue by shivam5x** [ionic-team/ionic-cli#1708]
Hi,
In windows 8 , installed ionic@latest and gone through of project creation and then run command "ionic serve"  and got below error every second until ctrl + c;

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

[15:32:30]  transpile started ...
Caught exception:
 TypeError: undefined is not a function
    at Socket.<anonymous> (C:\Users\roshan\AppData\Roaming\npm\node_modules\ioni
c\lib\utils\npmScripts.js:39:49)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

[15:32:41]  build dev failed: undefined is not a function
[15:32:41]  dev server running: http://localhost:8100/
Caught exception:
 TypeError: undefined is not a function
    at Socket.<anonymous> (C:\Users\roshan\AppData\Roaming\npm\node_modules\ioni
c\lib\utils\npmScripts.js:39:49)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: undefined is not a function
    at Socket.<anonymous> (C:\Users\roshan\AppData\Roaming\npm\node_modules\ioni
c\lib\utils\npmScripts.js:39:49)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

[15:32:41]  copy finished in 11.69 s
Caught exception:
 TypeError: undefined is not a function
    at Socket.<anonymous> (C:\Users\roshan\AppData\Roaming\npm\node_modules\ioni
c\lib\utils\npmScripts.js:39:49)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

___
Please  let us know the solution get on nest level.

Thanks

**Comment by tonymccallie** [comment]
I'm getting the exact same error on Mac OSX:

```Caught exception:
 TypeError: undefined is not a function
    at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/npmScripts.js:39:49)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues```

**Comment by estewart9** [comment]
The following resolved this issue for me:
1. Uninstalled and installed latest [NodeJS](https://nodejs.org/)
2. Ran "npm update -g"
3. Ran "npm rebuild node-sass"
4. "ionic serve" ran successfully after this

**Comment by tonymccallie** [comment]
This worked for me as well.

**Comment by juanredondo** [comment]
Same error here. The @emersonstewart solution, not working form me

**Comment by erwinliong** [comment]
I get the same error with Ionic 2, too. @emersonstewart solution did not solve for me. Ionic1 project works fine, though.

Any help, please? Thank you.

**Comment by ericaig** [comment]
:EMOJICODE:

**Comment by debadattabarik** [comment]
@emersonstewart solution did not work for me either. I was simply trying to "ionic serve" the "MyIonic2Project" from the ionic tutorial at "http://ionicframework.com/docs/v2/intro/tutorial/". My details as below:
Win 8.1
Node v0.12.2
NPM v2.7.4
Ionic v2.2.1
Cordova v6.5.0
