### ISSUE TITLE
$ionic run android -l on Multiple Devices at the same time

### ISSUE THREAD

**Issue by SaadeMotion** [ionic-team/ionic-cli#1741]
I can't run: (with live reload flag)
``` $ionic run android -l ```
multiple times, like for testing on multiple devices at the same time.

Even using --target=x flag.

Already tried:
``` $ionic run android -l --target=ADB_DEVICE_ID1 & $ionic run android -l --target=ADB_DEVICE_ID2 ```

How can i test? Seems to be a problem on setting up live-reload server, because without "-l" flag, it works beautifuly

error:
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--" "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"'.
npm ERR! This is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/saademotion/Projects/CariocaMix App copy/npm-debug.log
```

npm-debug.log:

``` 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ionic:serve',
1 verbose cli   '--',
1 verbose cli   '--port',
1 verbose cli   '8001',
1 verbose cli   '--address',
1 verbose cli   '192.168.1.5',
1 verbose cli   '--liveReloadPort',
1 verbose cli   '8000',
1 verbose cli   '--nobrowser' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info preionic:serve ionic-hello-world@
6 info ionic:serve ionic-hello-world@
7 verbose unsafe-perm in lifecycle true
8 info ionic-hello-world@ Failed to exec ionic:serve script
9 verbose stack Error: ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ionic-hello-world@
11 verbose cwd /Users/saademotion/Projects/CariocaMix App copy
12 error Darwin 15.6.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--" "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"
14 error node v4.6.1
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"`
17 error Exit status 1
18 error Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"'.
18 error This is most likely a problem with the ionic-hello-world package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.5" "--liveReloadPort" "8000" "--nobrowser"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ionic-hello-world
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ionic-hello-world
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by dwieeb** [comment]
@SaadeMotion I don't think this is still an issue, but if it is, please open a new issue. Thanks!
