### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by erenalgan** [ionic-team/ionic-cli#1743]
#### Short description of the problem:
I get an exception on a fresh app (based on tabs --v2)

**Post the output of `ionic info` below please**
Your system information:

Cordova CLI: 4.2.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v0.12.0
Xcode version: Xcode 8.1 Build version 8B62

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Here is the stack trace when I try to do ionic build.
Caught exception:
 TypeError: undefined is not a function
    at Socket.<anonymous> (/Users/xxx/.nvm/versions/node/v0.12.0/lib/node_modules/ionic/lib/utils/npmScripts.js:39:49)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:529:20)

**Comment by estewart9** [comment]
This might be related to Issue #1708
