### ISSUE TITLE
ionic serve failed code: 139 

### ISSUE THREAD

**Issue by AlexBDev** [ionic-team/ionic-cli#1751]
Hi, i have issue with the command `ionic serve`, i run my app in a docker container, here the content of my /etc/os-release.

```NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.4
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

The installation of nodejs and npm has been done without problems cordova and also ionic (globaly).
When i try to execute `ionic serve` i have this following error.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'ionic:serve', '--' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:serve: no script for preionic:serve, continuing
7 info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:serve: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:serve: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/app/data/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle ionic-hello-world@~ionic:serve: CWD: /app/data
11 silly lifecycle ionic-hello-world@~ionic:serve: Args: [ '-c', 'ionic-app-scripts serve' ]
12 silly lifecycle ionic-hello-world@~ionic:serve: Returned: code: 139  signal: null
13 info lifecycle ionic-hello-world@~ionic:serve: Failed to exec ionic:serve script
14 verbose stack Error: ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
14 verbose stack Exit status 139
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /app/data
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "ionic:serve" "--"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
22 error Exit status 139
23 error Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mayurdhanokar8527** [comment]
<b>Same issue here only the code: at line number 12 is 1 instead of 139</b>

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:serve',
1 verbose cli   '--' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:serve: no script for preionic:serve, continuing
7 info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:serve: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:serve: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\AppsProject\apps\ionic\omSai\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft\Web Platform Installer\;C:\Users\mayur\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Ruby22-x64\bin;C:\Users\mayur\AppData\Local\Programs\Git\cmd;C:\Program Files (x86)\Android\android-sdk;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\Users\mayur\AppData\Local\Microsoft\WindowsApps;C:\Users\mayur\AppData\Roaming\npm
10 verbose lifecycle ionic-hello-world@~ionic:serve: CWD: D:\AppsProject\apps\ionic\omSai
11 silly lifecycle ionic-hello-world@~ionic:serve: Args: [ '/d /s /c', 'ionic-app-scripts serve' ]
12 silly lifecycle ionic-hello-world@~ionic:serve: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~ionic:serve: Failed to exec ionic:serve script
14 verbose stack Error: ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd D:\AppsProject\apps\ionic\omSai
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by AlexBDev** [comment]
For my part i build my app with the official node:7.2 docker image the `ionic serve` works perfectly when i rebuild node-sass with `npm rebuild node-sass`.
I haven't the time to look this in depth but i think it's a good point to start.

**Comment by mayurdhanokar8527** [comment]
In my case port `8100` (ionic uses it as default) was blocked, you can either remove binding from `8100` before `ionic serve` or use this command to run ionic on another port `ionic serve -p 8080` or any other port that is not bound with any program

**Comment by HachimDev** [comment]
+1 I have the same problem. im trying to run it in an Alpine docker image. Any solution so far ??

**Comment by sebinbenjamin** [comment]
Any solutions? I am trying it on node:boron-alpine.

**Comment by dwieeb** [comment]
FWIW, I _do_ want to support the Ionic CLI in Docker, but there are many challenges of doing so in the node/npm environment.
