### ISSUE TITLE
 Error: Cannot find module 'extend'

### ISSUE THREAD

**Issue by iktsass** [ionic-team/ionic-cli#1779]
I run all ionic commands return below error. What I do?

Caught exception:
 Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/request/index.js:17:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by chansa1** [comment]
Caught exception:
 Error: Cannot find module 'colors/safe'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ZamSoft\AppData\Roaming\npm\node_modules\ionic\node_modules\winston\lib\winston\config.js:9:14)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
