### ISSUE TITLE
When I run " ionic serve" I see error  |  Please Help

### ISSUE THREAD

**Issue by ptmagalhaes** [ionic-team/ionic-cli#1795]
Mac-mini-de-teste:testando Devign$ ionic serve

> ionic-hello-world@ ionic:serve /Users/teste/Desktop/Ionic/testando
> ionic-app-scripts serve "[object Object]"

/Users/teste/Desktop/Ionic/testando/node_modules/node-sass/lib/index.js:13
    throw new Error(errors.unsupportedEnvironment());
    ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.1
    at Object.<anonymous> (/Users/teste/Desktop/Ionic/testando/node_modules/node-sass/lib/index.js:13:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/teste/Desktop/Ionic/testando/node_modules/@ionic/app-scripts/dist/sass.js:11:19)
    at Module._compile (module.js:571:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "[object Object]"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "[object Object]"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "[object Object]"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "[object Object]"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/teste/Desktop/Ionic/testando/npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: Mac OS X El Capitan
Node Version: v7.3.0
Xcode version: Xcode 8.2 Build version 8C23

**Comment by ptmagalhaes** [comment]
Mr. @jthoms1 . Please Take a Look
