### ISSUE TITLE
ionic stuck on 'installing npm packages' with start app-name

### ISSUE THREAD

**Issue by x9t9** [ionic-team/ionic-cli#1842]
#### Short description of the problem:

I have a similar issue to [this one ](https://github.com/driftyco/ionic-cli/issues/1239).
The difference is that I get **no error messages** .
when trying to start new ionic project with ```ionic start x99-test-app blank```
The CLI is just stuck on ```Installing npm packages (may take a minute or two)...```
Just installed ionic today ( assuming last stable version ).

actual output :

```
ionic start x99-test-app blank
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
Creating an Ionic app in X:\#DEV#\ionic\x99-test-app based on the blank template.

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic-starter-blank/archive/master.zip
Installing npm packages (may take a minute or two)...
```

from there on it is stuck for a Really long time .
I have tried waiting even 30min - but nothing .. the only way is to ```CTRl+C``` and out ..

However - the folder project and structure **IS** being created , and looks fine . I have no real way to know if all was initiated ok .

Regarding the cordova warning - read below ( in _Other Information_ )

#### What behavior are you expecting?
Regular initiation of app project folder structure and then , after a **short** while , cli ready for next step //

**Steps to reproduce:**
1. install ionic , cordova with ```npm install -g ionic cordova```
2. Initiate new ionic project with ```ionic start app-name blank```

**output of `ionic info` below**
```
 ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
```
**Other information:** 

Note : the cordova related warning  is also something I do not understand - 
when running ```cordova -version``` I get : 
```
λ cordova -version
6.4.0
```

- Which should be an updated version .. . at least higher than ```4.2.0``` :-)

## EDIT I

I found an ```npm-debug.log``` file inside the project folder .
It is very long , but the last lines might help ...

```
... NOTE :  Actual file start with line 40020

50497 silly postinstall yargs-parser@2.4.1 D:\#DEV#\ionic\k99-barcode\node_modules\.staging\yargs-parser-2021da44
50498 info lifecycle yargs-parser@2.4.1~postinstall: yargs-parser@2.4.1
50499 silly lifecycle yargs-parser@2.4.1~postinstall: no script for postinstall, continuing
50500 silly postinstall yargs@4.8.1 D:\#DEV#\ionic\k99-barcode\node_modules\.staging\yargs-9fb1f824
50501 info lifecycle yargs@4.8.1~postinstall: yargs@4.8.1
50502 silly lifecycle yargs@4.8.1~postinstall: no script for postinstall, continuing
50503 silly postinstall sass-graph@2.1.2 D:\#DEV#\ionic\k99-barcode\node_modules\.staging\sass-graph-94165276
50504 info lifecycle sass-graph@2.1.2~postinstall: sass-graph@2.1.2
50505 silly lifecycle sass-graph@2.1.2~postinstall: no script for postinstall, continuing
50506 silly postinstall node-sass@3.13.1 D:\#DEV#\ionic\k99-barcode\node_modules\.staging\node-sass-8081fb9a
50507 info lifecycle node-sass@3.13.1~postinstall: node-sass@3.13.1
50508 verbose lifecycle node-sass@3.13.1~postinstall: unsafe-perm in lifecycle true
50509 verbose lifecycle node-sass@3.13.1~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\#DEV#\ionic\k99-barcode\node_modules\node-sass\node_modules\.bin;D:\#DEV#\ionic\k99-barcode\node_modules\.bin;C:\Ruby23-x64\bin;C:\Program Files\CollabNet\Subversion Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\SlikSvn\bin;C:\Users\Magic-OFFICE\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\cmd;C:\Users\Magic-OFFICE\AppData\Roaming\npm
50510 verbose lifecycle node-sass@3.13.1~postinstall: CWD: D:\#DEV#\ionic\k99-barcode\node_modules\node-sass
50511 silly lifecycle node-sass@3.13.1~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
50512 silly lifecycle node-sass@3.13.1~postinstall: Returned: code: 1  signal: null
50513 info lifecycle node-sass@3.13.1~postinstall: Failed to exec postinstall script
50514 verbose unlock done using C:\Users\Magic-OFFICE\AppData\Roaming\npm-cache\_locks\staging-0594de7e120e6865.lock for D:\#DEV#\ionic\k99-barcode\node_modules\.staging
50515 silly rollbackFailedOptional Starting
50516 silly rollbackFailedOptional Finishing
50517 silly runTopLevelLifecycles Finishing
50518 silly install printInstalled
50519 warn ionic-project@1.1.1 No repository field.
50520 verbose If you need help, you may report this error at:
50520 verbose     <https://github.com/npm/npm/issues>
50521 warn ionic-project@1.1.1 No license field.
50522 verbose If you need help, you may report this error at:
50522 verbose     <https://github.com/npm/npm/issues>
50523 verbose stack Error: node-sass@3.13.1 postinstall: `node scripts/build.js`
50523 verbose stack Exit status 1
50523 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
50523 verbose stack     at emitTwo (events.js:106:13)
50523 verbose stack     at EventEmitter.emit (events.js:191:7)
50523 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
50523 verbose stack     at emitTwo (events.js:106:13)
50523 verbose stack     at ChildProcess.emit (events.js:191:7)
50523 verbose stack     at maybeClose (internal/child_process.js:877:16)
50523 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
50524 verbose pkgid node-sass@3.13.1
50525 verbose cwd D:\#DEV#\ionic\k99-barcode
50526 error Windows_NT 6.1.7601
50527 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
50528 error node v6.9.1
50529 error npm  v3.10.8
50530 error code ELIFECYCLE
50531 error node-sass@3.13.1 postinstall: `node scripts/build.js`
50531 error Exit status 1
50532 error Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
50532 error Make sure you have the latest version of node.js and npm installed.
50532 error If you do, this is most likely a problem with the node-sass package,
50532 error not with npm itself.
50532 error Tell the author that this fails on your system:
50532 error     node scripts/build.js
50532 error You can get information on how to open an issue for this project with:
50532 error     npm bugs node-sass
50532 error Or if that isn't available, you can get their info via:
50532 error     npm owner ls node-sass
50532 error There is likely additional logging output above.
50533 verbose exit [ 1, true ]

```

**Comment by KleinTong** [comment]
hey, my solution is to stop the install by "ctrl + c"
and use the npm install command to intall npm packages.
hope this can be helpful.

**Comment by x9t9** [comment]
@KleinTong - thanks for your answer . However , installing everything in a manual way can be very painfull on some projects, and takes out the sting in the whole npm ( and ionic ) workflow ...
I have finally resolved this solution - I do not remember how . :-) 
I think I uninstalled IONIC and reinstalled again, and also - changed my CLI to one of the `git-powershell` on my system .
The issue is still a problematic one - also because we are talking on a BLANK new project here ..
