### ISSUE TITLE
CLI 2.2.1 error (.ionic/ionic.config)

### ISSUE THREAD

**Issue by rainmak33r** [ionic-team/ionic-cli#1863]
Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version` 2.2.1

#### Short description of the problem:
The cli just stopped working for some reason. Yesterday it was working perfectly. 

#### What behavior are you expecting?

**Steps to reproduce:**
1. ionic info
2. get error
3. cry a bit.

```
insert any relevant code between the above and below backticks
`
Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ionic.config)
Caught exception:
 SyntaxError: Unexpected token
    at Object.parse (native)
    at Object.module.exports.load (C:\Users\nym\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\config.j
s:14:26)
    at Object.<anonymous> (C:\Users\nym\AppData\Roaming\npm\node_modules\ionic\lib\utils\stats.js:31:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\nym\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:3:18)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
`
`

**Post the output of `ionic info` below please**
get the error...

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by rainmak33r** [comment]
nvm, here's a solution 


https://forum.ionicframework.com/t/ionic-command-not-work/19452/5
