### ISSUE TITLE
Caught exception:  SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by CraigHarley** [ionic-team/ionic-cli#1882]
#### Short description of the problem:
I added some images into assets, then no ionic scripts work afterwards.
I have tried `rm -rf node_modules` and reinstalled the dependencies.
That didn't work, the error I'm getting is:
 
```
Craigs-MBP:ionic2app craigharley$ ionic info
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.load (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:13:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/stats.js:31:31)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19) 

```

#### What behavior are you expecting?
I should be able to run ionic scripts, I have tried `ionic info`,`ionic serve`

**Steps to reproduce:**
Not sure how to reproduce this, the problem occured right after I created a folder in `assets/img`, however the images copied over to assets okay.
Earlier today I installed android and ran `ionic run android` to my phone but I doubt that is related.

**Output of `ionic info` below please**
```
Craigs-MBP:ionic2app craigharley$ ionic info
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.load (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:13:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/stats.js:31:31)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19) 
Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by CraigHarley** [comment]
The file that is read by:
```
    at Object.load (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:13:24)
```
is `ionic.config.json`, which looks like:

```
{
  "name": "myapp",
  "app_id": "",
  "v2": true,
  "typescript": true,
  "gulpStartupTasks": [
    "sass",
    "watch"
  ],
  "watchPatterns": [
    "www/**/*",
    "!www/lib/**/*",
    "!www/**/*.map"
  ]
}
```

which looks correctly formed to me

**Comment by msolima** [comment]
Under your project root, check .io-config.json
if should have something like:
{"app_id":"xxxxxxxx"}
if the file is empty, add {"app_id":"xxxxxxxx"} to it and replace the xxxxxx with the app id from ionic.config.json.

**Comment by dwieeb** [comment]
Closed as this is the legacy CLI. If this is still an issue with the latest version, please make a new issue.
