### ISSUE TITLE
Ionic Release 2 Bug in ScreenOrientation

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/ionic-cli#1883]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### Short description of the problem:
With Ionic framework 2.0.0, on android platform bug with 

ScreenOrientation.lockOrientation('portrait-primary');

this was working in RC4 and RC5

#### What behavior are you expecting?
Lock the screen in portrait mode

**Steps to reproduce:**
1. ionic start ionic2bug sidemenu --v2
2. cd ionic2bug
3. ionic plugin add cordova-plugin-screen-orientation --save
4. open the app.component.ts in an editor (i use visual studio code editor)
5. modify line 3 as follows:
    import { StatusBar, Splashscreen, ScreenOrientation } from 'ionic-native';
6. add the following lines above line 34 (StatusBar.....)
      if( this.platform.is('android') || this.platform.is('ios') ||
          this.platform.is('windows')){
        ScreenOrientation.lockOrientation('portrait-primary');
      }
7. save the file
8. in the console window add the android platform 
    ionic platform add android
9. run android on device in visual Studio code

10 from the debug console window i got 
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
see the full message in other information

see the code for the app.component.ts
```
import { Component, ViewChild } from '@angular/core';
import { Nav, Platform } from 'ionic-angular';
import { StatusBar, Splashscreen, ScreenOrientation } from 'ionic-native';

import { Page1 } from '../pages/page1/page1';
import { Page2 } from '../pages/page2/page2';


@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  @ViewChild(Nav) nav: Nav;

  rootPage: any = Page1;

  pages: Array<{title: string, component: any}>;

  constructor(public platform: Platform) {
    this.initializeApp();

    // used for an example of ngFor and navigation
    this.pages = [
      { title: 'Page One', component: Page1 },
      { title: 'Page Two', component: Page2 }
    ];

  }

  initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      if( this.platform.is('android') || this.platform.is('ios') ||
          this.platform.is('windows')){
        ScreenOrientation.lockOrientation('portrait-primary');
      }
      StatusBar.styleDefault();
      Splashscreen.hide();
    });
  }

  openPage(page) {
    // Reset the content nav to have just this page
    // we wouldn't want the back button to show in this scenario
    this.nav.setRoot(page.component);
  }
}

```

**Post the output of `ionic info` below please**
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.3.0
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
App successfully launched
Attaching to android
Forwarding debug port
Attaching to app.
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
deviceready has not fired after 5 seconds.
DEVICE READY FIRED AFTER 4726 ms
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at file:///android_asset/www/build/main.js:366:21
    at file:///android_asset/www/build/main.js:319:17
    at new t (file:///android_asset/www/build/polyfills.js:3:11329)
    at tryNativePromise (file:///android_asset/www/build/main.js:318:20)
    at getPromise (file:///android_asset/www/build/main.js:340:16)
    at wrapOtherPromise (file:///android_asset/www/build/main.js:361:12)
    at Function.<anonymous> (file:///android_asset/www/build/main.js:510:20)
    at Function.value [as lockOrientation] (file:///android_asset/www/build/main.js:574:53)
    at file:///android_asset/www/build/main.js:99045:89
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9094)
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined

**Comment by jepiqueau** [comment]
i have located the problem in plugin.js in the function callCordovaPlugin
the value of pluginInstance[methodName] is : function(orientation)
but pluginInstance[methodName].apply(pluginInstance, args)  is undefined
so in the function wrapOtherPromise the value of pluginResult is undefined and so doing a then on undefined is the cause
