### ISSUE TITLE
exception Watch

### ISSUE THREAD

**Issue by gregoiremotot** [ionic-team/ionic-cli#1886]
ionic $ Caught exception:
 Error: watch www/app/Services/Common/WebService/WebService.js ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**ionic info**

Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v4.2.6
Xcode version: Not installed

**Comment by sayyaff** [comment]
Look at this issue this may help you
https://github.com/ionic-team/ionic-cli/issues/1828

**Comment by gregoiremotot** [comment]
thanks
