### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined - Cordova splashScreen plugin

### ISSUE THREAD

**Issue by mahfuz-aftab** [ionic-team/ionic-cli#1901]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
https://github.com/driftyco/ionic-app-scripts

When I am trying to add andorid platform 
`ionic platform add android`

### I am getting this error

 add to body class: platform-android

Installing "cordova-plugin-console" for android

Installing "cordova-plugin-device" for android

Installing "cordova-plugin-splashscreen" for android

TypeError: Cannot read property 'indexOf' of undefined
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:232:44
    at Array.forEach (native)
    at getEngines (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:211:13)
    at runInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:269:22)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:81:16
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/lib/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by Erickson20** [comment]
resolviste?

**Comment by mahfuz-aftab** [comment]
No, not yet.
