### ISSUE TITLE
Cannot find module 'ctype'

### ISSUE THREAD

**Issue by pjoriginal** [ionic-team/ionic-cli#1903]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What behavior are you expecting?

**Steps to reproduce:**
1. Installed ionic via the code `npm install -g cordova ionic`

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
Caught exception:
 Error: Cannot find module 'ctype'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/request/node_modules/http-signature/lib/util.js:7:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17) 

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
Closing as this is a CLI v2 issue. Please upgrade to CLI v3.
