### ISSUE TITLE
lodash/assign ionic command

### ISSUE THREAD

**Issue by wesleyhuang23** [ionic-team/ionic-cli#1907]
Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) 

Node v7.5.0
npm v4.1.2

**Comment by dwieeb** [comment]
Closing because this is a CLI v2 issue. Please upgrade to CLI v3.
