### ISSUE TITLE
Error: Cannot find module 'sax'

### ISSUE THREAD

**Issue by ajanthanm** [ionic-team/ionic-cli#1922]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### Short description of the problem:
Ionic CLI is not running. shows Cannot find module 'sax'

#### What behavior are you expecting?
Was expecting to run my project in web using ionic serve.

**Steps to reproduce:**
1.  installed latest version of ionic (2.2.1)
2. ran ionic serve
3.

```
insert any relevant code between the above and below backticks
```ionic serve

**Post the output of `ionic info` below please**

Caught exception:
 Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:9:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:538:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)


http://stackoverflow.com/questions/35225518/building-ionic-cordova-app-i-get-an-error-cannot-find-module-sax

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by navaidabidi** [comment]
@jthoms1 I am having the same problem on step 2 of a fresh ionic install.

Step 1: npm install -g ionic cordova
Step 2: ionic start cutePuppyPics --v2

Here is the error with ionic info:

c:\Development\Sandbox\Proto>ionic info
Caught exception:
 Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Navaid\AppData\Roaming\npm\node_modules\ionic\node_modules\xml2js\lib\xml2js.js:9:9)
    at Object.<anonymous> (C:\Users\Navaid\AppData\Roaming\npm\node_modules\ionic\node_modules\xml2js\lib\xml2js.js:538:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by CraigHarley** [comment]
@navaidabidi 
```npm uninstall -g cordova ionic```
then
```npm install -g cordova ionic```

fixed this same error for me

**Comment by davidecheli** [comment]
@CraigHarley Your solution solved my problem too.

Thank you!

**Comment by Dyabel03** [comment]
@CraigHarley for my too, thank you 🥇

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!

**Comment by Anujmoglix** [comment]
i tried it but not working for me
