### ISSUE TITLE
Caught exception:  Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by sulmansarwar** [ionic-team/ionic-cli#1929]
>: ionic g provider MyData
Caught exception:
 Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:391:17)
    at Function.Module._resolveFilename (module.js:461:31)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:11:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by rapropos** [comment]
That looks like you are running in a directory that has been deleted. Try resetting the working directory and running it again.

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
