### ISSUE TITLE
Facing an issue in executing  IONIC UPLOAD command in office LAN Network

### ISSUE THREAD

**Issue by jeena28** [ionic-team/ionic-cli#1932]
Hi Team,

As part of IONIC1 Project development, we are facing an issue to execute the command “ionic upload --email [email-address]  --password [password] ”

ISSUE : While executing the above command in LAN Network, we are getting a connection timeout error from different IP Addresses as shown below :  
 
An error occurred uploading the build: Error: connect ETIMEDOUT [IPAddress1]

Error: connect ETIMEDOUT [IPAddress1]

at Object.exports._errnoException (util.js:1026:11)
at exports._exceptionWithHostPort (util.js:1049:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

In order to resolve this issue, we tried to bypass few of the IP Addresses which we received from connection timeout error messages.
Since we are receiving connection Timeout error messages with different IP Addresses, we are unable to list out all the IP Addresses.

It would be great, if we could get the details on below details : 
1.	 Which  server IP address, IONIC UPLOAD command is connecting and executing with.
2.	  Do we have any configuration files inside IONIC Project to identify the IONIC Server IP Address.

Thanks and regards,
Jeena Paulson

**Comment by CodingYiyi** [comment]
weak network lead to this error。
do not use wifi in your office room。
using Ethernet cable fixed me this error。

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
