### ISSUE TITLE
spawn UNKNOWN error in ionic2

### ISSUE THREAD

**Issue by ATakaSKY** [ionic-team/ionic-cli#1954]
I am trying to serve my ionic 2 application with `ionic serve` command but I am getting an error:

```
$ ionic serve
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please update your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
There was an error serving your Ionic application: Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:380:9)
    at Function.spawn (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node                                                            _modules\cross-spawn\index.js:17:18)
    at Object.runIonicScript (C:\Users\user\AppData\Roaming\npm\node_modules\ion                                                            ic\lib\utils\npmScripts.js:72:32)
    at C:\Users\user\AppData\Roaming\npm\node_modules\ionic\lib\ionic\serve.js:1                                                            19:23
    at _fulfilled (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_mod                                                            ules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\user\AppData\Roaming\npm\node_modules                                                            \ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\user\AppData\Roaming\npm\node_m                                                            odules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:  
```

Versions running:

Ionic version:2.2.1

Cordova version:6.5.0

npm version:3.10.10

node version:6.9.5

I created the project with ionic start myApp tabs --v2.

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
