### ISSUE TITLE
Ionic build android" from node js (using Shelljs npm)

### ISSUE THREAD

**Issue by jeneive** [ionic-team/ionic-cli#1992]
I am trying to run "Ionic build android" from node js (using Shelljs npm). Getting Following Error

Caught exception:
 TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at Object.load (C:\Users\jeneive.dhanapalan\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\config.js:12:28)
    at Object.<anonymous> (C:\Users\jeneive.dhanapalan\AppData\Roaming\npm\node_modules\ionic\lib\utils\stats.js:31:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17) 

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
Are you able to execute this from command line within the project directory without error?

**Comment by jeneive** [comment]
yes I can run the command without any error

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
