### ISSUE TITLE
Ionic Upload Issue - Can't call method on  undefined

### ISSUE THREAD

**Issue by rafialikhan** [ionic-team/ionic-cli#2004]
Getting the following error when running ionic upload. However seeing the upload at https://apps.ionic.io

```
ionic upload --note "with new ui"
Uploading app....
Saved app_id, writing to ionic.io.bundle.min.js...

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/xxxxx/Projects/xxxxx-ui/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/xxxxx/Projects/xxxxx-ui/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/xxxxx/Projects/xxxxx-ui/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as info] (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Request._callback (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:150:11) 
```

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
