### ISSUE TITLE
getaddrinfo ENOTFOUND localhost

### ISSUE THREAD

**Issue by rafialikhan** [ionic-team/ionic-cli#2011]
Following error happens on `ionic serve`

This never used to happen before. This happened after I did `ionic emulate android --livereload` and then doing Ctrl+C to get back to the terminal prompt. 

Reporting so that ionic team can follow up on it. 

**For now the solution is `ionic serve --address 127.0.0.1`**

Linked Bug: (https://github.com/driftyco/ionic-cli/issues/1314)

```
There was an error serving your Ionic application: Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Caught exception:
 Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

System information:

> Cordova CLI: 6.5.0
> Gulp version:  CLI version 3.9.1
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 1.3.3
> Ionic CLI Version: 2.0.0
> Ionic App Lib Version: 2.0.0-beta.20
> ios-deploy version: 1.9.1 
> ios-sim version: 5.0.8 
> OS: Mac OS X El Capitan
> Node Version: v6.10.0
> Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by b3h3rkz** [comment]
Facing the same issue. Too bad it's not reproduceable. 

But running ionic serve --address 127.0.0.1:8100 works for me as stated above

**Comment by rafialikhan** [comment]
This seems to be an issue with a messed up hosts file. It happens when you use VPN and other softwares, which may overwrite the hosts file and removes the localhost details in /etc/hosts. I have been having it on angular and other node projects too. Ended up doing either --address 0.0.0.0 or --host 0.0.0.0 to get past the `getaddrinfo ENOTFOUND localhost ` issue during `ng serve` or `grunt serve` or `ionic serve`

**Here is the permanent solution:**

```
$ cat /etc/hosts 
```

to see whats currently in your host, if you dont see any details for **localhost**, you know thats the problem.

sudo vi /etc/hosts 
i for insert
```
##
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting. Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1 localhost
fe80::1%lo0	localhost
```
copy paste at the end of whatever you have.
```
Esc
:wq 
```
Esc + :wq to write and quit.

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
