### ISSUE TITLE
Incorrect exit code when ionic build fails (0)

### ISSUE THREAD

**Issue by ncapito** [ionic-team/ionic-cli#2018]
#### What version of the CLI are you using? Output of `ionic --version`

Ionic Version: 2.2.1

#### Short description of the problem:
We use the following command in our build process `ionic build browser --release --prod`.    When there is a build failure it is returning an exit code of 0 versus 1, and as a result our build server is not correctly notifying us during a build break.

#### What behavior are you expecting?
When we are building using ionic build browser and our webpack fails we are not getting a correct error code.

**Steps to reproduce:**
Setup your build so it fails. 
1. ionic build browser --release --prod 
2. Notice the message is correct (npm ERR! Exit status 1) but if you echo its wrong.
2. echo $?
3. when builds fail this number should not be 0

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

Cordova CLI: 6.5.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

In case its useful here is the output.  Our issue was effects had a bad push so our build was failing.

[:~/work/some/client] 86a6b1a(+1/-1)+* 1 ±  ionic build browser --release --prod

> some-client@0.6.0 ionic:build /Users/nick/work/some/client
> ionic-app-scripts build  --release --prod "--release" "--prod"

[12:02:16]  ionic-app-scripts 1.1.3
[12:02:16]  build prod started ...
[12:02:16]  clean started ...
[12:02:16]  clean finished in less than 1 ms
[12:02:16]  copy started ...
[12:02:16]  ngc started ...
can't resolve module ./bootstrap-listener from /Users/nick/work/some/client/node_modules/@ngrx/effects/src/effects.module.d.ts
[12:02:19]  build prod failed: Cannot read property 'runAfterBootstrapEffects' of undefined, resolving symbol
            EffectsModule in /Users/nick/work/some/client/node_modules/@ngrx/effects/src/effects.module.d.ts,
            resolving symbol EffectsModule in
            /Users/nick/work/some/client/node_modules/@ngrx/effects/src/effects.module.d.ts
[12:02:19]  ionic-app-script task: "build"
[12:02:19]  Error: Cannot read property 'runAfterBootstrapEffects' of undefined, resolving symbol EffectsModule in
            /Users/nick/work/some/client/node_modules/@ngrx/effects/src/effects.module.d.ts, resolving symbol
            EffectsModule in /Users/nick/work/some/client/node_modules/@ngrx/effects/src/effects.module.d.ts
Error: Cannot read property 'runAfterBootstrapEffects' of undefined, resolving symbol EffectsModule in /Users/nick/work/some/client/node_modules/@ngrx/effects/src/effects.module.d.ts, resolving symbol EffectsModule in /Users/nick/work/some/client/node_modules/@ngrx/effects/src/effects.module.d.ts
    at simplifyInContext (/Users/nick/work/some/client/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/Users/nick/work/some/client/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/Users/nick/work/some/client/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/Users/nick/work/some/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/nick/work/some/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/nick/work/some/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/nick/work/some/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/nick/work/some/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/nick/work/some/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--" "--release" "--prod"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! some-client@0.6.0 ionic:build: `ionic-app-scripts build  --release --prod "--release" "--prod"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the some-client@0.6.0 ionic:build script 'ionic-app-scripts build  --release --prod "--release" "--prod"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the some-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build  --release --prod "--release" "--prod"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs some-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls some-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nick/.npm/_logs/2017-03-21T16_02_19_117Z-debug.log
[:~/work/some/client] 86a6b1a(+1/-1)+* 5s ± echo $?
0

**Comment by ncapito** [comment]
Anyone out there have thoughts on this?   I'm going to poke around this am and see if i can figure out what is gobbling up the failed error code.

**Comment by ncapito** [comment]
Any update on this?

**Comment by ncapito** [comment]
@jthoms1  you all marked this as closed and I'm still seeing the issue.  It's changed now so when a build fials its actually now returning `-bash`:

>> echo $0
>> -bash

**Comment by bradjones1** [comment]
Confirming this persists in v3. So, a failed build on CI returns successful even though it's not.

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!

**Comment by loban** [comment]
Yes another example of ionic developers closing tickets without fixing them. Shame.

**Comment by loban** [comment]
Yes another example of ionic developers closing tickets without fixing them. Shame.

**Comment by dwieeb** [comment]
https://github.com/ionic-team/ionic-cli/pull/2040#issuecomment-391443333
