### ISSUE TITLE
ionic upload failed - error occured uploading the build

### ISSUE THREAD

**Issue by sharduul** [ionic-team/ionic-cli#2031]
Uploading app...

Saved app_id, writing to ionic.io.bundle.min.js...
An error occurred uploading the build: Error: connect ETIMEDOUT 54.231.98.136:443

Error: connect ETIMEDOUT 54.231.98.136:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

connect ETIMEDOUT 54.231.98.136:443 (CLI v2.2.1)

Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
