### ISSUE TITLE
cannot find module 'sax' error

### ISSUE THREAD

**Issue by cbitar** [ionic-team/ionic-cli#2055]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
2.2.2

#### Short description of the problem:
 Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/clarissabitar/.nvm/versions/node/v7.0.0/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:9:9)
    at Object.<anonymous> (/Users/clarissabitar/.nvm/versions/node/v7.0.0/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:538:4)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12) 

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
