### ISSUE TITLE
Ionic serve problem

### ISSUE THREAD

**Issue by menendea** [ionic-team/ionic-cli#2061]
Hello,

I'm having an issue using IONIC SERVE.

This is the situation:

Ionic Version: 2.2.1
Cordova Version: 6.5.0
Nodejs Version: 6.10.0

1 - I create a new project in this way: ionic start [app-name] [template] --v2 --ts

2 - Start to do things and execute ionic serve to view the result in chrome.

Till this stage it is all right.

The thing is when I shut down my computer and then start the project again.

1 - I prompt the path where the project is, execute ionic serve and I get the following error.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:serve',
1 verbose cli   '--',
1 verbose cli   '--v2',
1 verbose cli   '--address',
1 verbose cli   '0.0.0.0',
1 verbose cli   '--port',
1 verbose cli   '8100',
1 verbose cli   '--livereload-port',
1 verbose cli   '35729' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info lifecycle test-anm@~preionic:serve: test-anm@
6 silly lifecycle test-anm@~preionic:serve: no script for preionic:serve, continuing
7 info lifecycle test-anm@~ionic:serve: test-anm@
8 verbose lifecycle test-anm@~ionic:serve: unsafe-perm in lifecycle true
9 verbose lifecycle test-anm@~ionic:serve: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\menen_000\Google Drive\Pruebas\Ionic2\anm-test\node_modules\.bin;C:\Users\menen_000\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\menen_000\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Nmap;C:\Program Files (x86)\Nmap;C:\Users\menen_000\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\menen_000\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\menen_000\AppData\Roaming\npm
10 verbose lifecycle test-anm@~ionic:serve: CWD: C:\Users\menen_000\Google Drive\Pruebas\Ionic2\anm-test
11 silly lifecycle test-anm@~ionic:serve: Args: [ '/d /s /c',
11 silly lifecycle   'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"' ]
12 silly lifecycle test-anm@~ionic:serve: Returned: code: 1  signal: null
13 info lifecycle test-anm@~ionic:serve: Failed to exec ionic:serve script
14 verbose stack Error: test-anm@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid test-anm@
16 verbose cwd C:\Users\menen_000\Google Drive\Pruebas\Ionic2\anm-test
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error test-anm@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
22 error Exit status 1
23 error Failed at the test-anm@ ionic:serve script 'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test-anm package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test-anm
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test-anm
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

2 - The only way to start the project using ionic serve again is creating a new project and copy the src folder.

Best regards

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by rajeesab** [comment]
I am also getting the same error, while ionic serve.


C:\Users\Downloads\ionic-tutorial-master\new\mySMSApp>ionic info

Your system information:

Cordova CLI: 6.1.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v0.12.0
Xcode version: Not installed

**Comment by jsteruya** [comment]
For update NODEJS
https://nodejs.org/en/download/

Do you checked if you npm is up to date?

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
