### ISSUE TITLE
The issue after installed ionic v2 and try to run it first time

### ISSUE THREAD

**Issue by muzukashii** [ionic-team/ionic-cli#2074]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`

Ionic CLI version : 2.2.2

#### Short description of the problem:

I have some problem when run ionic serve.
After i run command "ionic serve", It's working . But after a couple second it has an error below and the ionic serve which running before is stopped

C:\xampp\htdocs\t-rexs-dev-app\Trexs-app\node_modules\tiny-lr\src\server.js:266
      console.error('... Uhoh. Got error %s ...', e.message);
                                                   ^

TypeError: Cannot read property 'message' of undefined
    at Server.error (C:\xampp\htdocs\t-rexs-dev-app\Trexs-app\node_modules\tiny-lr\src\server.js:266:52)
    at Socket.<anonymous> (C:\xampp\htdocs\t-rexs-dev-app\Trexs-app\node_modules\tiny-lr\src\server.js:217:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:346:10)
    at onwrite (_stream_writable.js:364:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:471:13)
    at Socket._destroy (net.js:512:3)
    at Socket._writeGeneric (net.js:715:17)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bitee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! node v6.10.2
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\t-rexs-dev-app\Trexs-app\npm-debug.log

#### What behavior are you expecting?

Run without any error

**Post the output of `ionic info` below please**
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by muzukashii** [comment]
npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Bitee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:serve',
1 verbose cli   '--',
1 verbose cli   '--f',
1 verbose cli   'chrome',
1 verbose cli   '--v2',
1 verbose cli   '--address',
1 verbose cli   '0.0.0.0',
1 verbose cli   '--port',
1 verbose cli   '8100',
1 verbose cli   '--livereload-port',
1 verbose cli   '35729' ]
2 info using npm@3.9.6
3 info using node@v6.10.2
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:serve: no script for preionic:serve, continuing
7 info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:serve: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:serve: PATH: C:\Users\Bitee\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\xampp\htdocs\t-rexs-dev-app\Trexs-app\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Git\cmd;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;JAVA_HOME\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Java\jdk1.8.0_74\bin;C:\Users\Bitee\AppData\Roaming\npm;C:\Users\Bitee\AppData\Local\Microsoft\WindowsApps;C:\Users\Bitee\AppData\Roaming\Composer\vendor\bin
10 verbose lifecycle ionic-hello-world@~ionic:serve: CWD: C:\xampp\htdocs\t-rexs-dev-app\Trexs-app
11 silly lifecycle ionic-hello-world@~ionic:serve: Args: [ '/d /s /c',
11 silly lifecycle   'ionic-app-scripts serve "--f" "chrome" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"' ]
12 silly lifecycle ionic-hello-world@~ionic:serve: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~ionic:serve: Failed to exec ionic:serve script
14 verbose stack Error: ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--f" "chrome" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Bitee\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Bitee\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd C:\xampp\htdocs\t-rexs-dev-app\Trexs-app
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bitee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--f" "chrome" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
19 error node v6.10.2
20 error npm  v3.9.6
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--f" "chrome" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--f" "chrome" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts serve "--f" "chrome" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
