### ISSUE TITLE
Sass setup problem

### ISSUE THREAD

**Issue by Malatji** [ionic-team/ionic-cli#2138]
Caught exception:
 TypeError: Cannot read property 'bold' of undefined
    at ChildProcess.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/setup.js:152:38)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by dwieeb** [comment]
This issue has been automatically closed because it had the `v2` label. Please install the new CLI v3 (`npm install -g ionic@latest`). See [CHANGELOG.md#Upgrading from CLI v2](https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2) for details.

If this issue is still a problem in CLI v3, please create a new issue. Thank you!
