### ISSUE TITLE
TypeError: Cannot read property 'widget' of undefined

### ISSUE THREAD

**Issue by Ahmedesayed** [ionic-team/ionic-cli#2175]
Caught exception:
 TypeError: Cannot read property 'widget' of undefined
    at C:\Users\Ahmed\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\serve.js:410:30
    at Parser.<anonymous> (C:\Users\Ahmed\AppData\Roaming\npm\node_modules\ionic\node_modules\xml2js\lib\xml2js.js:488:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onerror (C:\Users\Ahmed\AppData\Roaming\npm\node_modules\ionic\node_modules\xml2js\lib\xml2js.js:309:26)
    at emit (C:\Users\Ahmed\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:640:35)
    at error (C:\Users\Ahmed\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:669:5)
    at strictFail (C:\Users\Ahmed\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:693:7)
    at closeTag (C:\Users\Ahmed\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:887:9)
    at Object.write (C:\Users\Ahmed\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:1452:13)

**Comment by piotrowski** [comment]
This sounds more like a support problem for the forum: http://forum.ionicframework.com/
