### ISSUE TITLE
Some character (İ) crashes ionic serve

### ISSUE THREAD

**Issue by 0m3rF** [ionic-team/ionic-cli#2418]
**Description:**

Hello ,

I've just tried to generate new ionic app ( i tried blank, sidenav and tabs ) but i'm getting really interesting error. This is my www folder after running ionic serve command

Directory: E:\Coding\İonic\cutePuppyPics\www

Mode LastWriteTime Length Name

d----- 11.06.2017 03:57 assets
d----- 11.06.2017 03:57 build
-a---- 11.06.2017 03:53 0 .gitkeep
-a---- 11.06.2017 03:57 266 anifest.json
-a---- 11.06.2017 03:57 715 ervice-worker.js
-a---- 11.06.2017 03:53 207 manifest.json
-a---- 11.06.2017 03:57 1276 ndex.html
-a---- 11.06.2017 03:53 168 service-worker.js

If you noticed there is no index.html. It is ndex.html (there is no 'i' ) so i'm getting this error ;

var contentStr = content.toString();
                        ^

TypeError: Cannot read property 'toString' of undefined
at Object.injectLiveReloadScript (E:\Coding\İonic\cutePuppyPics\node_modules\@ionic\app-scripts\dist\dev-server\live-reload.js:28:29)
at ReadFileContext.callback (E:\Coding\İonic\cutePuppyPics\node_modules\@ionic\app-scripts\dist\dev-server\http-server.js:69:39)
at FSReqWrap.readFileAfterOpen as oncomplete

If i rename ndex.html to index.html this error gets fixed but i get another error;

ionic serve
[INFO] Starting app-scripts server: --port 8100 --p 8100 --livereload-port 35729 --r 35729 --address 0.0.0.0 - Ctrl+C to cancel
[04:03:14] watch started ...
[04:03:14] build dev started ...
[04:03:14] clean started ...
[04:03:14] clean finished in 4 ms
[04:03:14] copy started ...
[04:03:14] transpile started ...
[04:03:16] transpile finished in 2.33 s
[04:03:16] preprocess started ...
[04:03:16] deeplinks started ...
[04:03:16] deeplinks finished in 18 ms
[04:03:16] preprocess finished in 19 ms
[04:03:16] webpack started ...
[04:03:16] copy finished in 2.49 s
[04:03:22] webpack finished in 6.22 s
[04:03:22] sass started ...
[04:03:23] sass finished in 826 ms
[04:03:23] postprocess started ...
[04:03:23] postprocess finished in 5 ms
[04:03:23] lint started ...
[04:03:23] build dev finished in 9.44 s
[04:03:25] lint finished in 1.92 s
[04:03:26] dev server running: http://localhost:8100/

[ERROR] app-scripts serve unexpectedly failed.settings: undefinedcontext: [object Object]

I tried to reinstall ionic and cordova but it didnt solved as well. Also tried with another node version but it is same. 

With help of Sujan12 from ionic framework we have noticed that big i ( İ ) inside project path causes this problem. (like here : E:\Coding\İonic ) If i remove İ from path there wont be any problem.

**Steps to Reproduce:**
Just create fresh project which path includes İ ( or some other different characters.) then run ionic serve 

**Output:**
PS E:\Coding\İonic\testApp> ionic serve --verbose
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for global @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] Getting plugin info for ionic
[DEBUG] Getting plugin info for @ionic/cli-plugin-ionic-angular
[DEBUG] Checking for latest plugin version of ionic@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-ionic-angular@latest.
[DEBUG] Latest version of ionic@latest is 3.3.0.
[DEBUG] Latest version of @ionic/cli-plugin-ionic-angular@latest is 1.3.0.
[INFO] Starting app-scripts server: --log-level debug --port 8100 --p 8100 --livereload-port 35729 --r 35729 --address 0.0.0.0 - Ctrl+C to cancel
[15:50:44] watch started ...
[15:50:44] build dev started ...
[15:50:44] clean started ...
[15:50:44] clean finished in 40 ms
[15:50:44] copy started ...
[15:50:44] transpile started ...
[15:50:52] transpile finished in 7.32 s
[15:50:52] preprocess started ...
[15:50:52] deeplinks started ...
[15:50:52] deeplinks finished in 7 ms
[15:50:52] preprocess finished in 8 ms
[15:50:52] webpack started ...
[15:50:52] copy finished in 8.23 s
[15:51:00] webpack finished in 8.75 s
[15:51:00] sass started ...
[15:51:02] sass finished in 2.03 s
[15:51:02] postprocess started ...
[15:51:02] postprocess finished in 24 ms
[15:51:02] lint started ...
[15:51:02] build dev finished in 18.23 s
[15:51:05] lint finished in 2.34 s
[15:51:05] dev server running: http://localhost:8100/

[DEBUG] !!! ERROR ENCOUNTERED !!!
[ERROR] app-scripts serve unexpectedly failed.settings: undefinedcontext: [object Object]

**My `ionic info`:**
PS E:\Coding\İonic\testApp> ionic info
global packages:

@ionic/cli-utils : 1.3.0
Ionic CLI        : 3.3.0

local packages:

@ionic/app-scripts              : 1.3.7
@ionic/cli-plugin-ionic-angular : 1.3.0
Ionic Framework                 : ionic-angular 3.3.0

System:

Node       : v7.7.0
OS         : Windows 10
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed

**Other Information:**

Solved here ; 
https://forum.ionicframework.com/t/ionic-serve-generates-missing-file-s-or-missing-file-names/93756/3

**Comment by piotrowski** [comment]
Also reported for app-scripts here: https://github.com/ionic-team/ionic-app-scripts/issues/1002
