### ISSUE TITLE
ionic package build exists with code 1 on success

### ISSUE THREAD

**Issue by rolandjitsu** [ionic-team/ionic-cli#2483]
**Description:**

It seems that when I run `ionic package build android --profile=production --prod --release` the command exits with code 1 even though everything seems to be fine:

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

```text
✔ Retrieving security profile production - done!
Running app-scripts build: --prod

[00:16:09]  build prod started ...
[00:16:09]  clean started ...
[00:16:09]  clean finished in 3 ms
[00:16:09]  copy started ...
[00:16:09]  ngc started ...
[00:16:20]  ngc finished in 10.64 s
[00:16:20]  preprocess started ...
[00:16:20]  deeplinks started ...
[00:16:21]  deeplinks finished in 702 ms
[00:16:21]  optimization started ...
[00:16:21]  copy finished in 11.53 s
[00:16:37]  optimization finished in 16.57 s
[00:16:37]  preprocess finished in 17.27 s
[00:16:37]  webpack started ...
[00:16:46]  webpack finished in 8.40 s
[00:16:46]  sass started ...
[00:16:46]  uglifyjs started ...
[00:16:49]  sass finished in 2.94 s
[00:16:49]  cleancss started ...
[00:16:51]  cleancss finished in 2.03 s
[00:17:08]  uglifyjs finished in 22.22 s
[00:17:08]  postprocess started ...
[00:17:08]  postprocess finished in 16 ms
[00:17:08]  lint started ...
[00:17:08]  build prod finished in 58.58 s
✔ Requesting snapshot upload - done!
✔ Uploading snapshot - done!
[OK] Uploaded snapshot 19d50f9e-1acd-4df4-b18b-b271ecd44795!
✔ Requesting project upload - done!
✔ Uploading project - done!
✔ Queuing build - done!
[OK] Build 136 has been submitted!
[00:17:39]  lint finished in 31.40 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @infarm/maintenance@5.3.2 release: `scripts/release.sh patch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @infarm/maintenance@5.3.2 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rolandjitsu/.npm/_logs/2017-06-29T22_17_41_510Z-debug.log
```

**My `ionic info`:**

```text
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4
```

**Other Information:**

The NPM log:
```text
0 info it worked if it ends with ok
1 verbose cli [ '/Users/rolandjitsu/.nvm/versions/node/v7.4.0/bin/node',
1 verbose cli   '/Users/rolandjitsu/.nvm/versions/node/v7.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'release' ]
2 info using npm@5.0.4
3 info using node@v7.4.0
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle @infarm/maintenance@5.3.3~prerelease: @infarm/maintenance@5.3.3
6 silly lifecycle @infarm/maintenance@5.3.3~prerelease: no script for prerelease, continuing
7 info lifecycle @infarm/maintenance@5.3.3~release: @infarm/maintenance@5.3.3
8 verbose lifecycle @infarm/maintenance@5.3.3~release: unsafe-perm in lifecycle true
9 verbose lifecycle @infarm/maintenance@5.3.3~release: PATH: /Users/rolandjitsu/.nvm/versions/node/v7.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/rolandjitsu/Projects/infarm/maintenance/node_modules/.bin:/usr/local/heroku/bin:/Users/rolandjitsu/.pyenv/shims:/Users/rolandjitsu/.cabal/bin:/Users/rolandjitsu/.nvm/versions/node/v7.4.0/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/heroku/bin:/Users/rolandjitsu/.pyenv/shims:/Users/rolandjitsu/.cabal/bin:/usr/local/opt/go/libexec/bin:/Users/rolandjitsu/Projects/go/bin:/Users/rolandjitsu/.nvm/versions/node/v7.4.0/bin:/usr/local/opt/go/libexec/bin:/Users/rolandjitsu/Projects/go/bin:/Users/rolandjitsu/Projects/infarm/maintenance/node_modules/.bin
10 verbose lifecycle @infarm/maintenance@5.3.3~release: CWD: /Users/rolandjitsu/Projects/infarm/maintenance
11 silly lifecycle @infarm/maintenance@5.3.3~release: Args: [ '-c', 'scripts/release.sh patch' ]
12 silly lifecycle @infarm/maintenance@5.3.3~release: Returned: code: 1  signal: null
13 info lifecycle @infarm/maintenance@5.3.3~release: Failed to exec release script
14 verbose stack Error: @infarm/maintenance@5.3.3 release: `scripts/release.sh patch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/rolandjitsu/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/rolandjitsu/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @infarm/maintenance@5.3.3
16 verbose cwd /Users/rolandjitsu/Projects/infarm/maintenance
17 verbose Darwin 16.5.0
18 verbose argv "/Users/rolandjitsu/.nvm/versions/node/v7.4.0/bin/node" "/Users/rolandjitsu/.nvm/versions/node/v7.4.0/bin/npm" "run" "release"
19 verbose node v7.4.0
20 verbose npm  v5.0.4
21 error code ELIFECYCLE
22 error errno 1
23 error @infarm/maintenance@5.3.3 release: `scripts/release.sh patch`
23 error Exit status 1
24 error Failed at the @infarm/maintenance@5.3.3 release script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by rolandjitsu** [comment]
Closing, the status code seems to be `0`, something else was failing 😕
