### ISSUE TITLE
[ionic-v1] Can not `ionic start` project on Win/node8/npm5 because of node-sass

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2524]
`ionic start ionicv1 tabs --type=ionic1` doesn't work right now:

```
PS C:\Users\Jan\Documents> ionic start ionicv1 tabs --type=ionic1
√ Creating directory .\ionicv1 - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic-app-base/archive/master.tar.gz)
√ Downloading - done!
[INFO] Fetching starter template tabs (https://github.com/ionic-team/ionic-starter-tabs/archive/master.tar.gz)
√ Downloading - done!
[INFO] Fetching resources (https://github.com/ionic-team/ionic-default-resources/archive/master.tar.gz)
√ Downloading - done!
√ Updating package.json with app details - done!
√ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
× Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css
        npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new*
        front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and
        AMD projects. Currently there's no migration path, but please help to create it:
        https://github.com/bower/bower/issues/2467
        npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
        npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
        npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please
        update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

        > node-sass@3.13.1 install C:\Users\Jan\Documents\ionicv1\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
        try setting a proxy via HTTP_PROXY, e.g.

        export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

        npm config set proxy http://example.com:8080

        > node-sass@3.13.1 postinstall C:\Users\Jan\Documents\ionicv1\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe C:\Users\Jan\Documents\ionicv1\node_modules\node-gyp\bin\node-gyp.js
        rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@8.1.3 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError
        (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError
        (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError
        (C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\which\\which.js:13:12)\n    at F
        (C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\which\\which.js:68:19)\n    at E
        (C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\which\\which.js:80:29)\n    at
        C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\which\\which.js:89:16\n    at
        C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\isexe\\index.js:42:5\n    at
        C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete
        (fs.js:152:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError
        (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError
        (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\Jan\Documents\ionicv1\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError
        (C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\which\\which.js:13:12)\n    at F
        (C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\which\\which.js:68:19)\n    at E
        (C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\which\\which.js:80:29)\n    at
        C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\which\\which.js:89:16\n    at
        C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\isexe\\index.js:42:5\n    at
        C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete
        (fs.js:152:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython
        (C:\Users\Jan\Documents\ionicv1\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous>
        (C:\Users\Jan\Documents\ionicv1\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at
        C:\Users\Jan\Documents\ionicv1\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp ERR! System Windows_NT 10.0.15063
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe"
        "C:\\Users\\Jan\\Documents\\ionicv1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
        "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd C:\Users\Jan\Documents\ionicv1\node_modules\node-sass
        gyp ERR! node -v v8.1.3
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm WARN ionicv1@0.0.1 No repository field.
        npm WARN ionicv1@0.0.1 No license field.

        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@3.13.1 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Jan\AppData\Roaming\npm-cache\_logs\2017-07-14T08_06_01_460Z-debug.log
```

ionic info:
```

global packages:

    @ionic/cli-utils : 1.5.0
    Gulp CLI         : not installed globally
    Ionic CLI        : 3.5.0

local packages:

    @ionic/cli-plugin-gulp   : 1.0.2
    @ionic/cli-plugin-ionic1 : 2.0.1
    Ionic Framework          : ionic1 1.3.3

System:

    Node       : v8.1.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0
```

**Comment by janpio** [comment]
So who in there  is requesting `node-sass@3.13.1` to be installed that doesn't work for Win/node8?

**Comment by janpio** [comment]
```
{
  "name": "ionicv1",
  "version": "0.0.1",
  "description": "An Ionic project",
  "dependencies": {
    "gulp": "^3.5.6",
    "gulp-sass": "^2.0.4",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0"
  },
  "devDependencies": {
    "@ionic/cli-plugin-gulp": "1.0.2",
    "@ionic/cli-plugin-ionic1": "2.0.1",
    "bower": "^1.3.3",
    "gulp-util": "^2.2.14",
    "shelljs": "^0.3.0"
  }
}
```

`"gulp-sass": "^2.0.4",` seems to be at fault:
https://github.com/dlmanning/gulp-sass/blob/v2.0.4/package.json#L25

Unfortunately this is the last release of gulp-sass 2.0.x

**Comment by janpio** [comment]
This package.json is from ionic-app-base.
Yay, there is a PR for fixing this: https://github.com/ionic-team/ionic-app-base/pull/32

**Comment by dwieeb** [comment]
Thanks for testing this so thoroughly, @janpio !
