### ISSUE TITLE
ionic package build ios failing consistently

### ISSUE THREAD

**Issue by burggraf** [ionic-team/ionic-cli#2528]
I've been using the following command to package for years:

ionic package build ios --profile myprofile --release

A few days ago, the builds have been failing with the following error:

**$ ionic package info 43**

```
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/Users/markb/.nvm/versions/node/v6.10.3/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/package.js:117:27)
    at Request.self.callback (/Users/markb/.nvm/versions/node/v6.10.3/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/markb/.nvm/versions/node/v6.10.3/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/markb/.nvm/versions/node/v6.10.3/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:1266:12)
    at emitNone (events.js:91:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

```

**Comment by dwieeb** [comment]
Can you update your CLI to the latest version? You have a very old version. Here's some docs: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2

Let me know if you still have issues after updating.
