### ISSUE TITLE
Command: ionic resources have error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jimiatworking** [ionic-team/ionic-cli#2532]
**Description:**
I'm already setup proxy and unable to get icon and splash when I give ionic resource command.
Got **Error: unable to get local issuer certificate** 

**Steps to Reproduce:**
1. ionic resources

**Output:**
[DEBUG] !!! ERROR ENCOUNTERED !!!
Error: unable to get local issuer certificate
[DEBUG] Error: unable to get local issuer certificate
        at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
        at emitNone (events.js:105:13)
        at TLSSocket.emit (events.js:207:7)
        at TLSSocket._finishInit (_tls_wrap.js:628:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)

![image](https://user-images.githubusercontent.com/22278237/28257241-d41dfbc2-6afb-11e7-982d-72e0e7e81dc6.png)

**Comment by dwieeb** [comment]
This is an issue with your SSL setup, either locally or your proxy. 

Did you need to configure npm to work with your proxy? The Ionic CLI will need to be configured similarly. See https://github.com/nodejs/node/issues/3742

**Comment by SimplyComplexable** [comment]
Does anyone have more information on this? I've followed the link from @dwieeb, but nothing in there has helped. I've changed the npm registry, the '@ionic' registry and the cordova registry, but nothing fixes the issue. Did you ever find a solution @jimiatworking?

**Comment by jimiatworking** [comment]
@SimplyComplexable nope, haven't had a solution here.

**Comment by rahulbhooteshwar** [comment]
set an environment variable  `NODE_TLS_REJECT_UNAUTHORIZED` with value` 0` in your windows/linux system.

**Comment by dwieeb** [comment]
Setting `NODE_TLS_REJECT_UNAUTHORIZED` to `0` or otherwise disabling SSL verification is highly discouraged.

If you know you're behind a proxy, you need to configure your environment for a proxy:

* Please carefully follow the docs if you're behind a proxy: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy
* Your organization needs to provide proxy details for you. If you don't know the details, talk with your network administrator.
* Remember to avoid disabling SSL verification. This can lead to prolonged insecure configuration with your computer.

If you know you're **not** behind a proxy, make sure your system is up to date, which should ensure you have the latest CA certificates distributed with every OS.

If this _specific_ issue (SSL error upon `ionic login`) is happening with the latest CLI (3.20.0), please provide an updated stack trace and/or error message.

**Comment by sunnyrai31** [comment]
i was facing the same issue.but due to only one application which is Zscaler.if you are also having similar app,close it first and then try it.
here is few setups.
install the ionic using : npm i -g ionic
create a project : ionic start
go inside the dir : ionic serve
u might have to make resuce ssl false but i didn't.
