### ISSUE TITLE
[ERROR] An error occurred while running npm view ionic dist-tags.latest --json

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2545]
**Description:**

Random error popped up, haven't seen this one before so reporting:

```
PS C:\Users\Jan\Documents\yatsa> ionic help serve
[ERROR] An error occurred while running npm view ionic dist-tags.latest --json (exit code 1):

        C:\nvm\v8.1.3\node_modules\npm\node_modules\update-notifier\node_modules\configstore\index.js:63
        throw err;
        ^

        Error: EPERM: operation not permitted, rename
        'C:\Users\Jan\.config\configstore\update-notifier-npm.json.1643414399' ->
        'C:\Users\Jan\.config\configstore\update-notifier-npm.json'
        at Object.fs.renameSync (fs.js:771:18)
        at Function.writeFileSync [as sync]
        (C:\nvm\v8.1.3\node_modules\npm\node_modules\write-file-atomic\index.js:129:8)
        at Configstore.set all [as all]
        (C:\nvm\v8.1.3\node_modules\npm\node_modules\update-notifier\node_modules\configstore\index.js:56:20)
        at Configstore.delete
        (C:\nvm\v8.1.3\node_modules\npm\node_modules\update-notifier\node_modules\configstore\index.js:91:12)
        at UpdateNotifier.check (C:\nvm\v8.1.3\node_modules\npm\node_modules\update-notifier\index.js:83:22)
        at module.exports.options (C:\nvm\v8.1.3\node_modules\npm\node_modules\update-notifier\index.js:146:17)
        at C:\nvm\v8.1.3\node_modules\npm\bin\npm-cli.js:31:5
        at Object.<anonymous> (C:\nvm\v8.1.3\node_modules\npm\bin\npm-cli.js:92:3)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)


  ionic serve - Start a local dev server for app dev/testing

    Easily spin up a development server which launches in your browser. It watches for changes in your source files and
    automatically reloads with the updated build.

    Try the --lab option to see multiple platforms at once.

  Usage:

    $ ionic serve

  Options:

    --consolelogs, -c ........ Print app console logs to Ionic CLI
    --serverlogs, -s ......... Print dev server logs to Ionic CLI
    --port, -p ............... Dev server HTTP port (default: 8100)
    --livereload-port, -r .... Live Reload port (default: 35729)
    --nobrowser, -b .......... Disable launching a browser
    --nolivereload, -d ....... Do not start live reload
    --noproxy, -x ............ Do not add proxies
    --address ................ Network address for server (default: 0.0.0.0)
    --browser, -w ............ Specifies the browser to use (safari, firefox, chrome)
    --browseroption, -o ...... Specifies a path to open to (/#/tab/dash)
    --lab, -l ................ Test your apps on multiple platform types in the browser
    --platform, -t ........... Start serve with a specific platform (ios/android)

  Examples:

    $ ionic serve -lcs
    $ ionic serve --lab -lcs
```

File exists on the disk and was edited by the CLI with the `ionic info` run I did after I got the error.

**My `ionic info`:**

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0

**Comment by dwieeb** [comment]
Some internal npm error, looks like.
