### ISSUE TITLE
Info.gatherInfo(...).then is not a function

### ISSUE THREAD

**Issue by jnewman12** [ionic-team/ionic-cli#2568]
I want to preface this issue w/ I recently updated some node related things on my system. But I made a change to an ionic app today of mine and I wanted to upload it to ionic view. First, I was getting the error:

```
Caught exception:
 Error: Cannot find module 'colors/safe'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/config.js:9:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) 
```
which was resolved by just running `npm install colors -g`. Then i went to upload again, and got this error that I can't seem to find any fix for

```
Caught exception:
 TypeError: Info.gatherInfo(...).then is not a function
    at Object.doRuntimeCheck (/usr/local/lib/node_modules/ionic/lib/cli.js:692:30)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:51:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7) 
```
Also running things like `ionic info` results in the same error above. I'm not sure what changed in my setup, but everything ionic related seems to be broken right now. 

Does anyone know a fix to this?

**Comment by dwieeb** [comment]
The fix is to use CLI v3. `npm i -g ionic@latest`.
