### ISSUE TITLE
Yarn issue w/ ionic-cli

### ISSUE THREAD

**Issue by garryyao** [ionic-team/ionic-cli#2579]
**Description:**

`yarn global list` gives me an "401 Unauthorized" error because of previously installed ionic, perhaps this's something that worth taking a look at, it works after I remove "ionic" from yarn global package.json file.

**Steps to Reproduce:**
yarn: 0.27.5

**Output:**

Trace: 
  Error: https://registry.yarnpkg.com/@ionic/cli-utils/-/cli-utils-1.3.0.tgz: Request failed "401 Unauthorized"
      at Request.handleRequestError (/Users/garry/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/lib/fetchers/tarball-fetcher.js:203:20)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at Request.onRequestResponse (/Users/garry/.nvm/versions/node/v8.2.1/lib/node_modules/yarn/node_modules/request/request.js:1074:10)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:565:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
      at TLSSocket.socketOnData (_http_client.js:454:20)
      at emitOne (events.js:115:13)

**Comment by dwieeb** [comment]
Does the yarn registry take a while to notice new versions? Either way, I don't think yarn is on our plate to support. We're doing everything the standard npm way, which should work if yarn is doing things right.

Closing for now.
