### ISSUE TITLE
Uploading app to ionic view fails silently

### ISSUE THREAD

**Issue by TheSnip3r** [ionic-team/ionic-cli#2581]
**Description:**
When i try to execute command "ionic upload" or "ionic package build android" it just shows the building steps then shows that build is finished , then nothing , no uploading.

**Output:**

```
F:\xampp\htdocs\MyIonic>ionic upload

Running app-scripts build:
[10:14:16]  build dev started ...
[10:14:16]  clean started ...
[10:14:16]  clean finished in 4 ms
[10:14:16]  copy started ...
[10:14:16]  transpile started ...
[10:14:18]  transpile finished in 2.57 s
[10:14:18]  preprocess started ...
[10:14:18]  deeplinks started ...
[10:14:18]  deeplinks finished in 26 ms
[10:14:18]  preprocess finished in 28 ms
[10:14:18]  webpack started ...
[10:14:18]  copy finished in 2.73 s
[10:14:27]  webpack finished in 8.27 s
[10:14:27]  sass started ...
[10:14:27]  sass finished in 915 ms
[10:14:27]  postprocess started ...
[10:14:27]  postprocess finished in 4 ms
[10:14:27]  lint started ...
[10:14:27]  build dev finished in 11.82 s

F:\xampp\htdocs\MyIonic>

```
**My `ionic info`:**
```

cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (F:\xampp\htdocs\MyIonic\node_modules\@ionic\cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (F:\xampp\htdocs\MyIonic\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-plugin-proxy         : 1.4.0 (F:\xampp\htdocs\MyIonic\node_modules\@ionic\cli-plugin-proxy)
    @ionic/cli-utils                : 1.6.0 (F:\xampp\htdocs\MyIonic\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (F:\xampp\htdocs\MyIonic\node_modules\ionic)

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.0.0
    OS                : Windows 8.1
    npm               : 5.3.0

```

**Comment by dwieeb** [comment]
Please try with `--nobuild` and confirm that this is still an issue.

**Comment by TheSnip3r** [comment]
@dwieeb 

the issue still there with `--nobuild` , the command returned nothing
```
F:\xampp\htdocs\MyIonic>ionic upload --nobuild

F:\xampp\htdocs\MyIonic>
```

**Comment by dwieeb** [comment]
Can you run with `--verbose`?

**Comment by TheSnip3r** [comment]
@dwieeb 
yup

```

F:\xampp\htdocs\MyIonic>ionic upload --nobuild --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'F:\\xampp\\htdocs\\MyIonic', local: true, binPath:
        'C:\\Users\\Sniper\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ion
ic',
        libPath:
        'F:\\xampp\\htdocs\\MyIonic\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] Daemon found (pid: 8420)
[DEBUG] Getting plugin info for ionic
[DEBUG] Checking for latest plugin version of ionic@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-proxy
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-proxy@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-cordova
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-cordova@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-ionic-angular
[DEBUG] Checking for latest plugin version of
        @ionic/cli-plugin-ionic-angular@latest.

F:\xampp\htdocs\MyIonic>

```

**Comment by dwieeb** [comment]
@TheSnip3r Sorry, one more flag, haha. Can you also run with `--no-interactive`?

**Comment by TheSnip3r** [comment]
@dwieeb 

i have added `--dwieeb` flag too maybe it helps 😆 
and it seems it really did , finally we see errors
```
F:\xampp\htdocs\MyIonic>ionic upload --dwieeb --nobuild --verbose --no-interacti
ve
[DEBUG] CLI flags: { interactive: false, confirm: false }
[DEBUG] { cwd: 'F:\\xampp\\htdocs\\MyIonic', local: true, binPath:
        'C:\\Users\\Sniper\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ion
ic',
        libPath:
        'F:\\xampp\\htdocs\\MyIonic\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (F:\xampp\htdocs\MyIon
ic\node_modules\compress-commons\lib\archivers\zip\zip-archive-output-stream.js:
184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (F:\xampp\htdocs\MyIo
nic\node_modules\compress-commons\lib\archivers\zip\zip-archive-output-stream.js
:96:20)
    at module.exports.ArchiveOutputStream.entry (F:\xampp\htdocs\MyIonic\node_mo
dules\compress-commons\lib\archivers\archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (F:\xampp\htdocs\MyIonic\node_modules\zip-
stream\index.js:157:49)
    at Zip.append (F:\xampp\htdocs\MyIonic\node_modules\archiver\lib\plugins\zip
.js:53:15)
    at Archiver._moduleAppend (F:\xampp\htdocs\MyIonic\node_modules\archiver\lib
\core.js:172:16)
    at Archiver._onQueueTask (F:\xampp\htdocs\MyIonic\node_modules\archiver\lib\
core.js:370:8)
    at F:\xampp\htdocs\MyIonic\node_modules\async\dist\async.js:4069:9
    at process (F:\xampp\htdocs\MyIonic\node_modules\async\dist\async.js:2317:17
)

F:\xampp\htdocs\MyIonic>
```

**Comment by dwieeb** [comment]
@TheSnip3r Haha 😂 `--dwieeb` should've been an easter egg.

Okay, so it's weird we didn't see that error. I've seen that before. It's a node bug. Try updating to latest node 8. I should've also actually read your `ionic info` so you didn't have to go through all these hoops.
