### ISSUE TITLE
Cordova: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by dniccum** [ionic-team/ionic-cli#2592]
**Description:**

I was attempting to get the list of available targets for the `ionic cordova emulate` command, however during the process of getting the CLI generated response, I received this error:

```
Available ios virtual devices:

/Users/dougniccum/Apps/quiq-math/platforms/ios/cordova/node_modules/ios-sim/src/lib.js:282
            list.push(util.format('%s, %s', name_id_map[ deviceName ].replace(/^com.apple.CoreSimulator.SimDeviceType./, ''), runtime.replace(/^iOS /, '')));
                                                                     ^

TypeError: Cannot read property 'replace' of undefined
    at remove (/Users/dougniccum/Apps/quiq-math/platforms/ios/cordova/node_modules/ios-sim/src/lib.js:282:70)
    at Array.forEach (native)
    at Object.getdevicetypes (/Users/dougniccum/Apps/quiq-math/platforms/ios/cordova/node_modules/ios-sim/src/lib.js:292:22)
    at listEmulatorImages (/Users/dougniccum/Apps/quiq-math/platforms/ios/cordova/lib/list-emulator-images:34:29)
    at Object.<anonymous> (/Users/dougniccum/Apps/quiq-math/platforms/ios/cordova/lib/list-emulator-images:43:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
An unexpected error has occured while running list-emulator-images with code 1: Error: /Users/dougniccum/Apps/quiq-math/platforms/ios/cordova/lib/list-emulator-images: Command failed with exit code 1
```

It appears that this is simply a syntax error, but I could be wrong.

These are the current versions of my dependencies:

* `ionic:` 3.6.0
* `cordova:` 7.0.1
* `@ionic/app-scripts:` 2.0.2
* `@ionic/cli-plugin-cordova:` 1.5.0
* `@ionic/cli-plugin-ionic-angular:` 1.4.0

**Steps to Reproduce:**

Example repo: N/A

1. Within a freshly updated project, I executed this command `ionic cordova emulate ios --list`\

**Output:**

**My `ionic info`:**

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/Users/dougniccum/Apps/quiq-math/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/dougniccum/Apps/quiq-math/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/dougniccum/Apps/quiq-math/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/dougniccum/Apps/quiq-math/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node       : v8.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 5.3.0 
```

**Comment by dwieeb** [comment]
@dniccum I got this today as well. This fixed it for me: https://stackoverflow.com/a/44451292
