### ISSUE TITLE
can not found page modules 

### ISSUE THREAD

**Issue by zz373609** [ionic-team/ionic-cli#2603]
**Description:**

Runtime Error
Uncaught (in promise): Error: Cannot find module '../pages/user-main/user-main.module'. Error: Cannot find module '../pages/user-main/user-main.module'. at http://localhost:8100/build/main.js:54:56 at new t (http://localhost:8100/build/polyfills.js:3:15044) at webpackEmptyAsyncContext (http://localhost:8100/build/main.js:54:9) at loadAndCompile (http://localhost:8100/build/vendor.js:66931:36) at NgModuleLoader.load (http://localhost:8100/build/vendor.js:66896:83) at ModuleLoader.load (http://localhost:8100/build/vendor.js:52487:44) at DeepLinker.getNavLinkComponent (http://localhost:8100/build/vendor.js:20612:39) at DeepLinker.getComponentFromName (http://localhost:8100/build/vendor.js:20595:25) at getComponent (http://localhost:8100/build/vendor.js:29076:23) at convertToView (http://localhost:8100/build/vendor.js:29094:16)
Stack
Error: Uncaught (in promise): Error: Cannot find module '../pages/user-main/user-main.module'.
Error: Cannot find module '../pages/user-main/user-main.module'.
    at http://localhost:8100/build/main.js:54:56
    at new t (http://localhost:8100/build/polyfills.js:3:15044)
    at webpackEmptyAsyncContext (http://localhost:8100/build/main.js:54:9)
    at loadAndCompile (http://localhost:8100/build/vendor.js:66931:36)
    at NgModuleLoader.load (http://localhost:8100/build/vendor.js:66896:83)
    at ModuleLoader.load (http://localhost:8100/build/vendor.js:52487:44)
    at DeepLinker.getNavLinkComponent (http://localhost:8100/build/vendor.js:20612:39)
    at DeepLinker.getComponentFromName (http://localhost:8100/build/vendor.js:20595:25)
    at getComponent (http://localhost:8100/build/vendor.js:29076:23)
    at convertToView (http://localhost:8100/build/vendor.js:29094:16)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:12891)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:44755:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:44743:14)
    at http://localhost:8100/build/vendor.js:44798:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4508:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
Ionic Framework: 3.4.2
Ionic App Scripts: 2.1.3
Angular Core: 4.1.3
Angular Compiler CLI: ^4.1.3
Node: 7.7.2
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 1

this is error when I run the app

I think I have this correct on other computer, it runs yesterday, but it wont work today 

import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  // rootPage:any = 'ConnectPage';
rootPage:any = 'UserMainPage';

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    // platform.ready().then(() => {
    //   // Okay, so the platform is ready and our plugins are available.
    //   // Here you can do any higher level native things you might need.
    //   statusBar.styleDefault();
    //   splashScreen.hide();
    // });
    platform.ready().then(() => {
      // do whatever you need to do here.
      setTimeout(() => {
        splashScreen.hide();
      }, 100);
    });

    // let status bar overlay webview
    statusBar.overlaysWebView(true);

    // set status bar to white
    statusBar.styleDefault();
  }
}

app ts code

import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { UserMainPage } from './user-main';

@NgModule({
  declarations: [
    UserMainPage,
  ],
  imports: [
    IonicPageModule.forChild(UserMainPage),
  ],
  exports: [
    UserMainPage
  ]
})
export class UserMainPageModule {}
 user moudles code

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

**Other Information:**

**Comment by janpio** [comment]
You have to wrap the code you post in <code>```</code> so it is readable here.

**Comment by dwieeb** [comment]
Yeah, I can't read this.

Also, you did not fill out the issue template.

**Comment by dwieeb** [comment]
@zz373609 Let me know if you're still having issues.

**Comment by rizzla22** [comment]
Im hitting this issue now also
