### ISSUE TITLE
Generate pipe error

### ISSUE THREAD

**Issue by FallenRiteMonk** [ionic-team/ionic-cli#2621]
**Description:**
Running the command:
```
ionic g pipe testPipe
```
results in the following error:
```
Error: ENOENT: no such file or directory, open '<PROJECT_PATH>/testProject/src/PIPES/pipes.module.ts'
```

generating a component for example creates the 'components.module.ts'

**Steps to Reproduce:**
```
ionic start testProject blank --no-git --no-link --cordova
```
then in the project folder:
```
ionic g pipe testPipe --verbose
```

**Output:**
```
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '/<PROJECT_PATH>/testProject', local: true, binPath:
        '/usr/local/lib/node_modules/ionic/bin/ionic', libPath:
        '<PROJECT_PATH>/testProject/node_modules/ionic/dist/index.js' }
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] Daemon found (pid: 6638)
[DEBUG] Getting plugin info for ionic
[DEBUG] Checking for latest plugin version of ionic@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-cordova
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-cordova@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-ionic-angular
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-ionic-angular@latest.
Error: ENOENT: no such file or directory, open '<PROJECT_PATH>/testProject/src/PIPES/pipes.module.ts'
[DEBUG] Error: ENOENT: no such file or directory, open
        '<PROJECT_PATH>/testProject/src/PIPES/pipes.module.ts'
        at Error (native)
        at Object.fs.openSync (fs.js:641:18)
        at Object.fs.writeFileSync (fs.js:1347:33)
        at createCommonModule
        (<PROJECT_PATH>/testProject/node_modules/@ionic/app-scripts/dist/generators/util.js:77:10)
        at Object.<anonymous>
        (<PROJECT_PATH>/testProject/node_modules/@ionic/app-scripts/dist/generators/util.js:238:29)
        at step
        (<PROJECT_PATH>/testProject/node_modules/@ionic/app-scripts/dist/generators/util.js:32:23)
        at Object.next
        (<PROJECT_PATH>/testProject/node_modules/@ionic/app-scripts/dist/generators/util.js:13:53)
        at fulfilled
        (<PROJECT_PATH>/testProject/node_modules/@ionic/app-scripts/dist/generators/util.js:4:58)

```

**My `ionic info`:**
```
cli packages: (<PROJECT_PATH>/testProject/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.1
    OS                : Linux 4.11
    npm               : 5.3.0 

```

**Comment by mhartington** [comment]
Hmm, this looks like an async issue inside of app-scripts.

```
$ ionic info

cli packages: (/Users/mhartington/GitHub/tmp/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.2.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9M136h
    ios-deploy        : 1.9.1
    ios-sim           : 5.0.13
    npm               : 5.3.0
```

I'll take a look and see if something is being done async when it should be done synchronously

**Comment by iget-master** [comment]
I've the same issue here, the generator doesn't work for pipes. Could someone merge @JHeimbach's PR #1172?

**Comment by viswanathamsantosh** [comment]
Any update on this? I'm facing the same issue?

**Comment by JHeimbach** [comment]
As far as I know, my pr is merged and fixed the problem (within the app-scripts) don't know exactly what you have to update

**Comment by mhartington** [comment]
Hey, sorry. So PR has been merged, just need to cut a release. I'll get that going and provide an update

**Comment by terrycollinson** [comment]
Any news as I am facing this issue

**Comment by dwieeb** [comment]
@terrycollinson A fix has been in for quite some time now. Make sure your Ionic Framework, Ionic CLI, and `@ionic/app-scripts` are all up to date.
