### ISSUE TITLE
deleted local cli if yarn is used

### ISSUE THREAD

**Issue by DominikPieper** [ionic-team/ionic-cli#2630]
If I use yarn instead of npm, the local ionic-cli folder is deleted after some commands (refering to this topic: https://forum.ionicframework.com/t/cli-gone-after-any-ionic-command/101534)

cli packages:

```
@ionic/cli-plugin-cordova       : 1.6.2
@ionic/cli-plugin-ionic-angular : 1.4.1
@ionic/cli-utils                : 1.7.0
ionic (Ionic CLI)               : 3.7.0
```

global packages:
```
Cordova CLI : 7.0.1 
```

local packages:

```
@ionic/app-scripts : 2.1.3
Cordova Platforms  : ios 4.4.0
Ionic Framework    : ionic-angular 3.6.0

```
System:
```
Node       : v8.2.1
OS         : macOS Sierra
Xcode      : Xcode 8.3.3 Build version 8E3004b 
ios-deploy : 1.9.1 
npm        : 5.3.0
```
```
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: ‘/Users/dominik/Projects/testapp’, local: true, binPath:
’/usr/local/lib/node_modules/ionic/bin/ionic’, libPath:
’/Users/dominik/Projects/testapp/node_modules/ionic/dist/index.js’ }
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for local @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] Daemon found (pid: 2114)
[DEBUG] Getting plugin info for ionic
[DEBUG] Checking for latest plugin version of ionic@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-cordova
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-cordova@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-ionic-angular
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-ionic-angular@latest.

    cordova platform add android --save
    :heavy_multiplication_x: Running command - failed!

[ERROR] Cordova encountered an error.
You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova platform add android --save (exit code 1):

    Using cordova-fetch for cordova-android@~6.2.2
    Adding ionic-plugin-keyboard project...
    Error: Your ionic-plugin-keyboard platform does not have Api.js

➜ testapp git:(master) ✗ ionic cordova platform add android --verbose
{ Error: Cannot find module '/Users/dominik/Projects/testapp/node_modules/ionic’
at Function.Module._resolveFilename (module.js:485:15)
at Function.Module._load (module.js:437:25)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at /usr/local/lib/node_modules/ionic/bin/ionic:18:13
at code: ‘MODULE_NOT_FOUND’ }
```

**Comment by dwieeb** [comment]
Is this a recurring issue?

**Comment by nachtwandler** [comment]
Yes, it's deleted and have to be reinstalled after every command

**Comment by dwieeb** [comment]
Is the CLI in your `package.json` file? What about `yarn.lock`?

**Comment by matheo** [comment]
I'm having the same issue right now!

I've just installed `npm install -g ionic cordova` and tried to `ionic cordova prepare` an existing project, after that my CLI throws the reported `/usr/lib/node_modules/ionic/bin/ionic:18:13 code: 'MODULE_NOT_FOUND'` error.

The `cli` is not on my `package.json`
My info:
```
cli packages: (/media/work/git/selvera/ccr-mobileApp/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.0

System:

    Node : v6.11.3
    npm  : 5.4.2 
    OS   : Linux 4.10

Misc:

    backend : pro
```

**Comment by dwieeb** [comment]
@matheo That's not the same issue. Someone weird probably happened during the installation. Try these steps:

```
npm uninstall ionic
npm uninstall -g ionic
npm install ionic
```

**Comment by gregunz** [comment]
I'm facing the same issue, any help out there ?

**Comment by nowzig** [comment]
I have the same issue too. Very annoying.

**Comment by dwieeb** [comment]
@nachtwandler @gregunz @nowzig Can you answer my question here? I'm trying to help. https://github.com/ionic-team/ionic-cli/issues/2630#issuecomment-328585718

**Comment by nowzig** [comment]
yes it is in the package.json and in the yarn.lock as well:

`ionic@3.12.0:
  version "3.12.0"
  resolved "https://registry.yarnpkg.com/ionic/-/ionic-3.12.0.tgz#f279f6fbd24237ce3113c416c685e70876090537"
  dependencies:
    "@ionic/cli-utils" "1.12.0"
    "@ionic/discover" "^0.3.1"
    chalk "^2.0.0"
    opn "^5.1.0"
    os-name "^2.0.1"
    rimraf "^2.6.2"
    semver "^5.3.0"
    tslib "^1.7.1"`

**Comment by dwieeb** [comment]
Is this still an issue?
