### ISSUE TITLE
ionic cordova build ios --prod --release 

### ISSUE THREAD

**Issue by 395779222** [ionic-team/ionic-cli#2631]
there is no problem if i remove the parameter of prod and release.
when i run ionic cordova build ios --prod --release
Error: chunk main [initial]
[name].js
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at enterNode (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:118:14)
    at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:97:24)
    at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:106:24)
    at enterNode (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:121:18)
    at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:110:25)
    at enterNode (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:121:18)
    at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:97:24)
    at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:106:24)
    at enterNode (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:121:18)
    at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:97:24)

**Comment by dwieeb** [comment]
@395779222 I assume you get the same error with `ionic build`?

**Comment by 395779222** [comment]
the problem has been solved, thanks. maybe its a problem by webpack.
