### ISSUE TITLE
Ionic serve not working (exit code 130)

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-cli#2670]
_From @Alvaroctal on August 18, 2017 7:56_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Trying to compile the code, `ionic serve` or `ionic build` will end in exit code 

**Expected behavior:**
The ionic serve starts watching and opens the web server.

**Steps to reproduce:**

Since ionic left v3.6, using typescript version 2.3.4 (the one that works with rxjs) (upper versions of typescript in fact allows ionic start watching and work fine, but the project doesn't work due to type errors in rxjs).
 
```
$ ionic serve --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 
    '/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project', 
    local: true, binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', 
    libPath: 
    '/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/ionic/dist/index.js' 
    }
[DEBUG] Daemon found (pid: 628)
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 
   --livereload-port 35729 - Ctrl+C to cancel
[16:41:59]  watch started ... 
[16:41:59]  build dev started ... 
[16:41:59]  clean started ... 
[16:41:59]  clean finished in 1 ms 
[16:41:59]  copy started ... 
[16:41:59]  transpile started ... 
[16:42:05]  transpile finished in 5.30 s 
[16:42:05]  preprocess started ... 
[16:42:05]  deeplinks started ... 
[16:42:05]  deeplinks finished in 71 ms 
[16:42:05]  preprocess finished in 72 ms 
[16:42:05]  webpack started ... 
[16:42:05]  copy finished in 5.65 s

And then the prompt is returned with exit code 130.
```

**Related code:**

Doesn't seems to be related with the code it self but setting typescript version to 2.4.1 or newer seems to allow ionic to complete the compilation, for some reason.   

**Other information:**

Moving to typescript 2.4.1 or newer it starts watching, opens the browser and seems to work fine (but as I said, this version of typescript doesn't work with rxjs).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules)

   @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v6.11.2
    npm   : 3.10.10 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.2 Build version 8E2002 
```

_Copied from original issue: ionic-team/ionic#12696_

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! I am moving this issue to ionic-team/ionic-cli as it appears to CLI related. Please track the issue over there. Thank you for using Ionic

**Comment by Alvaroctal** [comment]
Just noticed, when the project has an error the compilation ends fine, so I tried to `ionic serve` with the broken code, and the serve starts listening, but then I fix it, so it can compile successfully... but the CLI crashes and returns `exit code 1`:

```
$ ionic serve --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 
        '/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project', 
        local: true, binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', 
        libPath: 
        '/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/ionic/dist/index.js' 
        }
[DEBUG] Daemon found (pid: 2398)
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 
       --livereload-port 35729 - Ctrl+C to cancel
[13:18:37]  watch started ... 
[13:18:37]  build dev started ... 
[13:18:37]  clean started ... 
[13:18:37]  clean finished in 1 ms 
[13:18:37]  copy started ... 
[13:18:37]  transpile started ... 
[13:18:42]  typescript: src/app/app.component.ts, line: 78 
            Property 'filter' does not exist on type 'Observable<Geoposition>'. 

      L77:  this.watch = this.geolocation.watchPosition({enableHighAccuracy:true, timeout:20000, maximumAge:0})
      L78:      .filter((p) => p.coords !== undefined) //Filter Out Errors
      L79:      .subscribe(position => {

[13:18:42]  dev server running: http://localhost:8100/ 

[INFO] Development server running
       Local: http://localhost:8100
       External: http://192.168.1.186:8100
       
[13:18:42]  copy finished in 5.35 s 
[13:18:42]  watch ready in 5.43 s 
[13:18:47]  build started ... 
[13:18:47]  transpile update started ... 
[13:18:47]  transpile update finished in 77 ms 
[13:18:47]  deeplinks update started ... 
[13:18:48]  deeplinks update finished in 74 ms 
[13:18:48]  webpack started ... 
/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/source-map/lib/source-node.js:115
        node.add(nextLine.substr(0, mapping.generatedColumn));
                         ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/source-map/lib/source-node.js:115:26)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/source-map/lib/source-node.js:80:24)
    at SourceMapSource.node (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/webpack-sources/lib/SourceMapSource.js:39:21)
    at ReplaceSource.node (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/webpack-sources/lib/ReplaceSource.js:70:30)
    at CachedSource.node (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/webpack-sources/lib/CachedSource.js:18:24)
    at /Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/webpack-sources/lib/ConcatSource.js:37:50
    at Array.map (native)
    at ConcatSource.node (/Applications/XAMPP/xamppfiles/htdocs/proyectos/my-project/node_modules/webpack-sources/lib/ConcatSource.js:36:63)
```

thanks in advance

**Comment by matejkramny** [comment]
Experiencing the same issue, is there any fix?

Tried the procedure as @Alvaroctal (borked code, then fix..)

```
$ ionic serve --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '/Users/m/p/app', local: true, binPath:
        '/usr/local/lib/node_modules/ionic/bin/ionic', libPath:
        '/Users/m/p/app/node_modules/ionic/dist/index.js' }
[DEBUG] New daemon pid: 12214
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100
       --livereload-port 35729 - Ctrl+C to cancel
[22:38:31]  watch started ...
[22:38:31]  build dev started ...
[22:38:31]  clean started ...
[22:38:31]  clean finished in 1 ms
[22:38:31]  copy started ...
[22:38:31]  transpile started ...
[22:38:33]  typescript: src/app/app.module.ts, line: 6
            Cannot find name 'tafux'.

       L5:  import { HttpService } from '../providers/http';
       L6:  tafux
       L7:  import { MyApp } from './app.component';

[22:38:33]  dev server running: http://localhost:8100/

[INFO] Development server running
       Local: http://localhost:8100
       External: http://10.0.0.3:8100

[22:38:33]  copy finished in 2.25 s
[22:38:33]  watch ready in 2.27 s
[22:38:36]  build started ...
[22:38:36]  transpile update started ...
[22:38:36]  transpile update finished in 32 ms
[22:38:36]  deeplinks update started ...
[22:38:37]  deeplinks update finished in 33 ms
[22:38:37]  webpack started ...
crypto.js:97
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:97:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (/Users/m/p/app/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:144:8)
    at /Users/m/p/app/node_modules/webpack/lib/DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (/Users/m/p/app/node_modules/webpack/lib/DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (/Users/m/p/app/node_modules/webpack/lib/Module.js:162:41)
    at NormalModule.updateHash (/Users/m/p/app/node_modules/webpack/lib/NormalModule.js:327:30)
    at modules.forEach.m (/Users/m/p/app/node_modules/webpack/lib/Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (/Users/m/p/app/node_modules/webpack/lib/Chunk.js:253:16)
```

**Comment by Alvaroctal** [comment]
Hi,

Actually, fixed this, it was not directly related to any angular CLI updated (it simply happened at the same time)...

```js
@Component({
  templateUrl: 'announcements.component.html',
})
export class AnnouncementsPageComponent {
```
fine, that comma ruined my life.

home this helps you

**Comment by matejkramny** [comment]
heh. wasted a couple of hours chasing this. Wish ionic could be more descriptive about this
