### ISSUE TITLE
ionic cordova build android --prod

### ISSUE THREAD

**Issue by jimcjy** [ionic-team/ionic-cli#2717]
when i run ionic cordova build android --prod ,the build failed
but run ionic build android or ionic build android --release  is successful
Error: chunk main [initial]
[name].js
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
at enterNode (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:118:14)
at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:97:24)
at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:106:24)
at enterNode (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:121:18)
at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:110:25)
at enterNode (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:121:18)
at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:97:24)
at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:106:24)
at enterNode (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:121:18)
at getPathInAst (/Users/coffice/Desktop/work/app/tonglunApp/node_modules/_webpack@3.2.0@webpack/lib/optimize/ConcatenatedModule.js:97:24)

**Comment by souzace** [comment]
--prod seems check all structure of .ts and .html files to find troubles inside them, fix that variable "range" checking with "if" condition if it receive the value expected and continue the process. e.g: if (range){ ... or if (!range){ etc...

**Comment by jimcjy** [comment]
@souzace 
Thanks
This is my modified code , the build success , But I don't know if it will hide anything
function enterNode(n) {
		if(n && n.range) {
			const r = n.range;
			if(r[0] <= nr[0] && r[1] >= nr[1]) {
				const path = getPathInAst(n, node);
				if(path) {
					path.push(n);
					return path;
				}
			}
		}
		return undefined;
	}

**Comment by souzace** [comment]
nice
