### ISSUE TITLE
Alias configuration does not work when building in production

### ISSUE THREAD

**Issue by kinglionsoft** [ionic-team/ionic-cli#2726]
**Description:**
To simplify the import path (e.g. './../../'),  I set an alias for a specific path in webpack.config.js. It works fine in development building, but not in production building.

**Steps to Reproduce:**
1. ionic start ionic-seed blank
2. add  "baseUrl": "./src" to compilerOptions section of tsconfig.json;
3. add ionic_webpack to package.json
``` js
"config": {
    "ionic_webpack": "./config/webpack.config.js"
  },
```
4.  config alias in new webpack.config.js
```js
 resolve: {
    extensions: ['.ts', '.js', '.json'],
    modules: [path.resolve('node_modules')],
    alias: {
      'kl': path.resolve('src/kl')
    }
  },
```

**Output:**
``` bash
npm run ionic:build --prod

// output
> ionic-seed@0.0.1 ionic:build E:\Projects\GitHub\ionic-seed3
> ionic-app-scripts build

[11:38:42]  ionic-app-scripts 2.1.3
[11:38:42]  build prod started ...
[11:38:42]  clean started ...
[11:38:42]  clean finished in 9 ms
[11:38:42]  copy started ...
[11:38:42]  ngc started ...
[11:38:47]  ngc finished in 4.29 s
[11:38:47]  preprocess started ...
[11:38:47]  deeplinks started ...
[11:38:47]  deeplinks finished in 137 ms
[11:38:47]  optimization started ...
[11:38:47]  copy finished in 4.59 s
[11:38:49]  ionic-app-script task: "build"
[11:38:49]  Error: ./src/app/app.module.js Module not found: Error: Can't resolve 'kl/core' in
            'E:\Projects\GitHub\ionic-seed3\src\app' resolve 'kl/core' in 'E:\Projects\GitHub\ionic-seed3\src\app'
            Parsed request is a module using description file: E:\Projects\GitHub\ionic-seed3\package.json (relative
            path: ./src/app) Field 'browser' doesn't contain a valid alias configuration after using description file:
            E:\Projects\GitHub\ionic-seed3\package.json (relative path: ./src/app) resolve as module
            E:\Projects\GitHub\ionic-seed3\src\app\node_modules doesn't exist or is not a directory
            E:\Projects\GitHub\ionic-seed3\src\node_modules doesn't exist or is not a directory
            E:\Projects\GitHub\node_modules doesn't exist or is not a directory E:\Projects\node_modules doesn't exist
            or is not a directory E:\node_modules doesn't exist or is not a directory looking for modules in
            E:\Projects\GitHub\ionic-seed3\node_modules using description file:
            E:\Projects\GitHub\ionic-seed3\package.json (relative path: ./node_modules) Field 'browser' doesn't contain
            a valid alias configuration after using description file: E:\Projects\GitHub\ionic-seed3\package.json
            (relative path: ./node_modules) using description file: E:\Projects\GitHub\ionic-seed3\package.json
            (relative path: ./node_modules/kl/core) no extension Field 'browser' doesn't contain a valid alias
            configuration E:\Projects\GitHub\ionic-seed3\node_modules\kl\core doesn't exist .js Field 'browser' doesn't
            contain a valid alias configuration E:\Projects\GitHub\ionic-seed3\node_modules\kl\core.js doesn't exist .ts
            Field 'browser' doesn't contain a valid alias configuration
            E:\Projects\GitHub\ionic-seed3\node_modules\kl\core.ts doesn't exist as directory
            E:\Projects\GitHub\ionic-seed3\node_modules\kl\core doesn't exist
            [E:\Projects\GitHub\ionic-seed3\src\app\node_modules] [E:\Projects\GitHub\ionic-seed3\src\node_modules]
            [E:\Projects\GitHub\node_modules] [E:\Projects\node_modules] [E:\node_modules]
            [E:\Projects\GitHub\ionic-seed3\node_modules\kl\core]
            [E:\Projects\GitHub\ionic-seed3\node_modules\kl\core.js]
            [E:\Projects\GitHub\ionic-seed3\node_modules\kl\core.ts]
            [E:\Projects\GitHub\ionic-seed3\node_modules\kl\core] @ ./src/app/app.module.js 15:0-39 @
            ./src/app/app.module.ngfactory.js @ ./src/app/main.ts
Error: ./src/app/app.module.js
Module not found: Error: Can't resolve 'kl/core' in 'E:\Projects\GitHub\ionic-seed3\src\app'
resolve 'kl/core' in 'E:\Projects\GitHub\ionic-seed3\src\app'
  Parsed request is a module
  using description file: E:\Projects\GitHub\ionic-seed3\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: E:\Projects\GitHub\ionic-seed3\package.json (relative path: ./src/app)
    resolve as module
      E:\Projects\GitHub\ionic-seed3\src\app\node_modules doesn't exist or is not a directory
      E:\Projects\GitHub\ionic-seed3\src\node_modules doesn't exist or is not a directory
      E:\Projects\GitHub\node_modules doesn't exist or is not a directory
      E:\Projects\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
      looking for modules in E:\Projects\GitHub\ionic-seed3\node_modules
        using description file: E:\Projects\GitHub\ionic-seed3\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Projects\GitHub\ionic-seed3\package.json (relative path: ./node_modules)
          using description file: E:\Projects\GitHub\ionic-seed3\package.json (relative path: ./node_modules/kl/core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Projects\GitHub\ionic-seed3\node_modules\kl\core doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Projects\GitHub\ionic-seed3\node_modules\kl\core.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Projects\GitHub\ionic-seed3\node_modules\kl\core.ts doesn't exist
            as directory
              E:\Projects\GitHub\ionic-seed3\node_modules\kl\core doesn't exist
[E:\Projects\GitHub\ionic-seed3\src\app\node_modules]
[E:\Projects\GitHub\ionic-seed3\src\node_modules]
[E:\Projects\GitHub\node_modules]
[E:\Projects\node_modules]
[E:\node_modules]
[E:\Projects\GitHub\ionic-seed3\node_modules\kl\core]
[E:\Projects\GitHub\ionic-seed3\node_modules\kl\core.js]
[E:\Projects\GitHub\ionic-seed3\node_modules\kl\core.ts]
[E:\Projects\GitHub\ionic-seed3\node_modules\kl\core]
 @ ./src/app/app.module.js 15:0-39
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (E:\Projects\GitHub\ionic-seed3\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at E:\Projects\GitHub\ionic-seed3\node_modules\@ionic\app-scripts\dist\preprocess.js:18:21
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**My `ionic info`:**
``` bash
  @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.0
    npm  : 3.10.10
    OS   : Windows 10
```
Thanks.

**Comment by dwieeb** [comment]
@kinglionsoft Build related issues can be posted in https://github.com/ionic-team/ionic-app-scripts. Thanks!
