### ISSUE TITLE
Error at FatalException.Exception 

### ISSUE THREAD

**Issue by iauro-pratik** [ionic-team/ionic-cli#2728]
**Description:**

when try to run the application throws an following error
my command : ionic cordova build android

**Output:**

{ Error
    at FatalException.Exception (/usr/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/errors.js:8:23)
    at FatalException (/usr/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/errors.js:17:9)
    at Config.<anonymous> (/usr/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/config.js:45:35)
    at throw (native)
    at rejected (/usr/lib/node_modules/ionic/node_modules/tslib/tslib.js:94:69) name: 'Exception', exitCode: 1, fatal: true }
**My `ionic info`:**

**Other Information:**

node@6.11.3
Bower@1.0.0
cordova@7.0.1
gulp@3.9.1
ionic@3.9.2
npm@3.10.10
typings@2.1.1

**Comment by iauro-pratik** [comment]
Solve issue

**Comment by iauro-pratik** [comment]
error given due to /home/<username>/.ionic/config.js file json structure miss match
