### ISSUE TITLE
[3.10.1] `ionic serve` error: events.js:182 ... Error: send EHOSTUNREACH 169.254.255.255:41234

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2732]
People report crashes with `ionic serve`:

```
[18:46:37]  sass finished in 961 ms
[18:46:37]  postprocess started ...
[18:46:37]  postprocess finished in 5 ms
[18:46:37]  lint started ...
[18:46:37]  build dev finished in 8.75 s
[18:46:37]  watch ready in 8.79 s
[18:46:37]  dev server running: http://localhost:8100/

[INFO] Development server running!
       Local: http://localhost:8100
       External: http://10.210.108.20:8100, http://169.254.53.88:8100

[18:46:39]  lint finished in 1.73 s
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: send EHOSTUNREACH 169.254.255.255:41234
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:474:11)
/Users/pbrack/dev/temp/great:
```
https://forum.ionicframework.com/t/event-js-182-getting-error-from-ionic-serve-immediately/105166
https://forum.ionicframework.com/t/3-10-1-ionic-cli-crashes-ionic-serve/105210

"Solution" seems to be to unplug the iPhone.

Probable culprit would be the new discovery/benjour replacedment stuff.

**Comment by KevinFu** [comment]
the same solution from @jaybloke

> By simply unplugging my iPhone from my Mac and then running ionic serve again fixed the problem.



[https://forum.ionicframework.com/t/event-js-182-getting-error-from-ionic-serve-immediately/105166/3
](url)

**Comment by giumarzo** [comment]
My solution: I disconnected network sharing

**Comment by shahriar** [comment]
Disconnecting iphone didn't work for me. Rolled back to 3.9.2

**Comment by WilliamZimmermann** [comment]
I had the same problem since yesterday. I spend 8 hours to discover the problem... simply disconnect my iPhone from my MacBook and it's work again.

This was the error:

`ionic serve
[INFO] Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 -
       Ctrl+C to cancel
[11:21:38]  watch started ...
[11:21:38]  build dev started ...
[11:21:38]  clean started ...
[11:21:38]  clean finished in 4 ms
[11:21:38]  copy started ...
[11:21:38]  transpile started ...
[11:21:41]  transpile finished in 3.11 s
[11:21:41]  preprocess started ...
[11:21:41]  deeplinks started ...
[11:21:41]  deeplinks finished in 10 ms
[11:21:41]  preprocess finished in 11 ms
[11:21:41]  webpack started ...
[11:21:41]  copy finished in 3.33 s
[11:21:50]  webpack finished in 8.75 s
[11:21:50]  sass started ...
[11:21:51]  sass finished in 1.78 s
[11:21:51]  postprocess started ...
[11:21:51]  postprocess finished in 11 ms
[11:21:51]  lint started ...
[11:21:51]  build dev finished in 13.73 s
[11:21:52]  watch ready in 13.84 s
[11:21:52]  dev server running: http://localhost:8100/

[INFO] Development server running!
       Local: http://localhost:8100
       External: http://192.168.0.17:8100, http://169.254.97.29:8100

[11:21:57]  lint finished in 5.38 s
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: send EHOSTUNREACH 169.254.255.255:41234
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:474:11)`

**Comment by jorojas** [comment]
Dear Ionic Team.
Could please fix this issue? I think every person that is using a mac is presenting this issue related to "ionic serve".

Thx.

```
[14:58:26]  lint finished in 2.43 s
events.js:160
     throw er; // Unhandled 'error' event
     ^

Error: send EHOSTUNREACH 169.254.255.255:41234
   at Object.exports._errnoException (util.js:1020:11)
   at exports._exceptionWithHostPort (util.js:1043:20)
   at SendWrap.afterSend [as oncomplete] (dgram.js:405:11)

```

**Comment by dwieeb** [comment]
Is `ionic serve` actually crashing now? My understanding is it just prints an ugly error.

**Comment by dwieeb** [comment]
@jorojas @WilliamZimmermann @KevinFu @shahriar @giumarzo Would you please try using `ionic serve` with the canary CLI? I've silenced the error for now because we don't care about it.

`npm i -g ionic@canary`.

**Comment by WilliamZimmermann** [comment]
@dwieeb , thanks! Now, with Ionic CLI 3.10.2 it's working fine!

**Comment by jorojas** [comment]
@dwieeb You are the best, we were down for 4 hours.

Thanks.

**Comment by dwieeb** [comment]
There is now a `ionic@3.10.3` release which should hide this error. Thanks all! My apologies.

**Comment by tomavic** [comment]
Hi guys I had same problem, I tried clening npm cashe but it didn't work for me
