### ISSUE TITLE
Cannot find module 'sax' for CLI 3.12 @ ionic 1.3.2 project

### ISSUE THREAD

**Issue by sonicwong** [ionic-team/ionic-cli#2762]
ionic cordova run android --device
```
Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sonic/Documents/repo/booking-app/node_modules/elementtree/lib/parsers/sax.js:3:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

////


cli packages: (/Users/sonic/Documents/repo/f1k-booking-app/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    Cordova Platforms : android 6.2.3 ios 4.3.1
    Ionic Framework   : ionic1 1.3.2

System:

    ios-deploy : 1.9.0 
    ios-sim    : 5.0.11 
    Node       : v6.11.1
    npm        : 5.4.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 

Misc:

    backend : legacy

```

**Comment by sonicwong** [comment]
#1922

**Comment by dwieeb** [comment]
Please try to reinstall the CLI. I think there was an error in the npm installation.

```
npm uninstall ionic
npm uninstall -g ionic
npm install -g ionic
```
