### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by hmuschett** [ionic-team/ionic-cli#2768]
$ ionic start MyIonicProject tutorial
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
× Downloading - failed!
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1120:19)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by dwieeb** [comment]
@hmuschett Please fill out the issue template.

Is this a recurring issue?

**Comment by hmuschett** [comment]
@dwieeb Yes, I've been trying to fix it for days and nothing.

**Comment by dwieeb** [comment]
@hmuschett Are you behind a firewall? Did you need to configure npm for a proxy?

**Comment by hmuschett** [comment]
@dwieeb yes i am behind a firewall but I have npm configured and it works with other packages like AngularCLI

**Comment by dwieeb** [comment]
@hmuschett Please see the docs for Proxy Configuration: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy

Let me know if you have any more issues.

**Comment by hmuschett** [comment]
I have configured everything and it does not work

$ ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (C:\Users\hmuschett\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.4.9
    @ionic/cli-utils        : 1.10.2
    ionic (Ionic CLI)       : 3.10.3

System:

    Node : v7.10.0
    npm  : 4.2.0
    OS   : Windows 7


HTTPS_PROXY=https://hmuschett:muschett.26.@10.63.1.29:3128
HTTP_PROXY=http://hmuschett:muschett.26.@10.63.1.29:3128

**Comment by dwieeb** [comment]
Can you send the full output of the command that doesn't work? Please add `--verbose` to enable debug logging.

**Comment by Nirbhay94** [comment]
+1

**Comment by hmuschett** [comment]
@dwieeb 
$ ionic start mytest tutorial
√ Creating directory .\mytest - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
× Downloading - failed!
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1120:19)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:

**Comment by dwieeb** [comment]
@Nirbhay94 @hmuschett Please run it with the `--verbose` flag.

Run this command: `ionic start mytest tutorial --verbose`

**Comment by jhbosch** [comment]
C:\Users\U>ionic start mytest tutorial --verbose
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'C:\\Users\\U', local: false, binPath:
        'C:\\Users\\U\\AppData\\Roaming\\npm\\node_modules\\ion
onic',
        libPath:
        'C:\\Users\\U\\AppData\\Roaming\\npm\\node_modules\\ion
index.js'
        }
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
? Would you like to integrate your new app with Cordova to target nati
d Android? Yes
[DEBUG] globalDeps=cordova
V Creating directory .\mytest - done!
[INFO] Fetching app base
       (https://github.com/ionic-team/ionic2-app-base/archive/master.t
× Downloading - failed!
Error: socket hang up
[DEBUG] Error: socket hang up
        at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
        at Object.onceWrapper (events.js:314:30)
        at emitNone (events.js:110:20)
        at TLSSocket.emit (events.js:207:7)
        at endReadableNT (_stream_readable.js:1047:12)
        at _combinedTickCallback (internal/process/next_tick.js:102:11
        at process._tickCallback (internal/process/next_tick.js:161:9)

C:\Users\U>
