### ISSUE TITLE
Auto Update from ionic CLI is failing

### ISSUE THREAD

**Issue by danova123** [ionic-team/ionic-cli#2786]
Hi Team,
I got the usual CLI Update message to update to ionic CLI 3.12.0. I pressed Y and it started processing and i got an error. Also, my ionic installation got deleted.

However, when i reinstalled ionic, it installed to the latest version. 

```
? The Ionic CLI has an update available (3.10.3 => 3.12.0)! Would you like to i
> npm install -g ionic@latest
× Running command - failed!
Error
    at ShellException.Exception (C:\Users\sd0003\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\errors.js:8:23)
    at ShellException (C:\Users\sd0003\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\errors.js:26:9)
    at ChildProcess.p.on (C:\Users\sd0003\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\utils\shell.js:66:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\sd0003\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by montycrypto** [comment]
I encountered the same issue, for me doing an uninstall followed by an install also resolved the issue:

```
$ npm uninstall -g ionic
$ npm install -g ionic
```

**Comment by dwieeb** [comment]
@danova123 Has the auto update feature ever worked for you? I noticed failed in the same way for me on my Windows machine.

**Comment by thesourav123** [comment]
@dwieeb It never worked for me on Windows. Worked on Mac though.

Thanks for adding this bug.

**Comment by dwieeb** [comment]
I may need to disable it for Windows and simply show a message.

**Comment by dwieeb** [comment]
As of right now, the latest CLI v4 alpha does not auto update on any OS. This may change, but it will be addressed for v4.

**Comment by dwieeb** [comment]
For v4 we're just going to try using `update-notifier` (like npm does). No auto-updating for the timebeing.
