### ISSUE TITLE
Can't run build for legacy 1.3.3 app

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-cli#2795]
_From @adyngom on September 27, 2017 11:20_

#### Short description of the problem:
I cannot get beyond the build step of trying to run a legacy client app using the ionic cli

#### What behavior are you expecting?
The normal build firing a de server and pointing to a local url for developemt

**Steps to reproduce:**
1. npm install -g ionic@1.3.3
2. rm -rf node_modules
3. npm install
4. ionic serve

```sh
Running 'serve:before' gulp task before serve
[11:12:43] Starting 'sass'...
Caught exception:
 Error: Missing error message
    at new PluginError (/Users/adyngom/Code/IonicProjects/weli/node_modules/gulp-util/lib/PluginError.js:53:28)
    at DestroyableTransform.logError (/Users/adyngom/Code/IonicProjects/weli/node_modules/gulp-sass/index.js:179:17)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at onwriteError (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:427:12)
    at onwrite (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:448:11)
    at WritableState.onwrite (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at afterTransform (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:3)
    at TransformState.afterTransform (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at errorM (/Users/adyngom/Code/IonicProjects/weli/node_modules/gulp-sass/index.js:134:14) 
```

_Copied from original issue: ionic-team/ionic-app-scripts#1244_

**Comment by kensodemann** [comment]
_From @rasor on October 1, 2017 16:28_

@adyngom:
I just had a similar problem with node_modules/node-sass/.
`@ionic/app-scripts` was using a version of node-sass that did not support the new Node v8.
If your Node.js is too new you can back to an older
Or you can use a newer version of `@ionic/app-scripts`.
Perhaps solution is same in you case.
Or how about creating a new starter and move the code from your legacy app?

**Comment by kensodemann** [comment]
_From @adyngom on October 2, 2017 1:4_

@rasor thanks for responding. When you say move legacy to new starter what do you essentially move?? The old www folder replaces the new one I guess - and what else

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This issue is being moved to the CLI repo. Please follow and respond to the new issue over there.

Thank you for using Ionic

**Comment by dwieeb** [comment]
@adyngom @kensodemann We are not supporting CLI versions 1 and 2. The Ionic CLI v3 is compatible with all versions of Ionic Framework, please upgrade: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2

If there are issues with older apps in the CLI, let me know and I will fix them.

**Comment by dwieeb** [comment]
This command installs a very old version of the Ionic CLI: `npm install -g ionic@1.3.3`

The npm package `ionic` is the Ionic CLI, not the Ionic Framework.

**Comment by adyngom** [comment]
@dwieeb thanks for the heads up I will try to run with CLI v3 and report back ASAP.

**Comment by adyngom** [comment]
@dwieeb the project runs after updating to latest
```sh
npm uninstall -g ionic
npm install -g ionic@latest
```
I had some dependencies that were missing but that's the responsibility of the project not Ionic.  NVM was using an older version of node (v.5.1.3) I adjusted it to v.8.1.3

Running ```ionic info```
outputs this

```sh
adyngom@Adys-MBP:~/Code/IonicProjects/weli$ ionic info

cli packages: (/Users/adyngom/.nvm/versions/node/v8.1.3/lib/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : not installed
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : none
    Ionic Framework   : ionic1 1.3.3

System:

    Node : v8.1.3
    npm  : 5.4.2 
    OS   : macOS Sierra

Misc:

    backend : pro
```

I guess we can consider this issue closed. Thanks to @everyone who helped on this. @rasor you rock :)

**Comment by dwieeb** [comment]
@adyngom That's great to hear. Let me know if you have any issues with CLI v3 and your Ionic 1 app! 😄
