### ISSUE TITLE
What happened today? Can No longer building my app

### ISSUE THREAD

**Issue by wowkucko** [ionic-team/ionic-cli#2811]
Yesterday i had no problems. Today i haven't changed anything, just trying to run my project with ionic cordova run android. Getting the following error:
```

[21:30:06]  build dev started ...
[21:30:06]  clean started ...
[21:30:06]  clean finished in 4 ms
[21:30:06]  copy started ...
[21:30:06]  deeplinks started ...
[21:30:06]  deeplinks finished in 189 ms
[21:30:06]  transpile started ...
[21:30:11]  typescript: .../feederhorgasz/node_modules/@ionic/app-scripts/dist/util/virtual-file-utils.d.ts, line: 3
            Class 'VirtualStats' incorrectly implements interface 'Stats'. Property 'atimeMs' is missing in type
            'VirtualStats'.

       L2:  export declare class VirtualStats implements Stats {
       L3:      protected _path: string;
       L4:      protected _ctime: Date;

Error: Failed to transpile program
    at BuildError.Error (native)
    at new BuildError (C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at transpileWorker (C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\build.js:106:82
```

ionic info:
cli packages: (C:\Users\Thomas\AppData\Roaming\npm\node_modules)

@ionic/cli-utils  : 1.12.0
ionic (Ionic CLI) : 3.12.0
global packages:

cordova (Cordova CLI) : 7.0.1
local packages:

@ionic/app-scripts : 3.0.0
Cordova Platforms  : android 6.2.3
Ionic Framework    : ionic-angular 3.7.1
System:

Node : v6.11.3
npm  : 3.10.10
OS   : Windows 10
Misc:

backend : pro

**Comment by dwieeb** [comment]
Are you importing `@ionic/app-scripts` somewhere?

**Comment by jcesarmobile** [comment]
closing as there was no response
