### ISSUE TITLE
Is there some kind of official fix for the node-sass issue with Windows x64?

### ISSUE THREAD

**Issue by Zerokk** [ionic-team/ionic-cli#2834]
This is important.

I already posted this in https://github.com/ionic-team/ionic-cli/issues/2817 and fixed it via a very, very ugly way: creating a new fresh Ionic project, and moving all my views and assets there. It worked, but come on, we NEED to have some other type of fix for this serious problem.

It doesn't care if you have the LTS or the latest Node version; it happens on both of them. You get the following message:

Error: Missing binding C:\Zerok\dev\StepApp\node_modules\@ionic\app-scripts\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 8.x

```
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (C:\some\folder\my_project\node_modules\@ionic\app-scripts\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\some\folder\my_project\node_modules\@ionic\app-scripts\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\some\folder\my_project\node_modules\@ionic\app-scripts\dist\core\bundle-components.js:6:16)

```

... and that's all. If you do the rebuild thing, you mess everything up and the project won't be served anyways. I already tested everything, but nothing seems to really work. "npm install" for reinstalling the dependencies doesn't seem to work either. 

We need a fix for this problem. Otherwise, Windows x64 users are totally left behind and with no option to properly use Ionic, since we're going to have tons of problems with every serious npm/node change we make.

**Comment by dwieeb** [comment]
@Zerokk I haven't heard this issue from other Windows users recently. Firstly, make sure you have the latest `@ionic/app-scripts` installed. We switched to the latest `node-sass` which supports Node 8 on Windows (https://github.com/ionic-team/ionic-app-scripts/commit/ea4c5caaa1929754343a4a23baa1059f7b47e430). You can see a list of bindings for `node-sass` here: https://github.com/sass/node-sass/releases

If the pre-built binary is missing, an `npm rebuild` can compile the binary locally, but can sometimes fail if a system is misconfigured.

Perhaps elaborate on "If you do the rebuild thing, you mess everything up" ? If you post a compilation error, I may be able to help.
