### ISSUE TITLE
Error on ionic serve

### ISSUE THREAD

**Issue by sondauta2** [ionic-team/ionic-cli#2874]
**Description:**

Hi, I try to run my project with ionic serve, but not run. Show errors.

**Steps to Reproduce:**

Example repo: 

1.  MacBook-Air-de-manuel:wagner-app-cliente mcastillo$ ionic serve
2.
3.

**Output:**

Error: Cannot find module 'json-stable-stringify'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mcastillo/Desktop/ionic/wagner-app-cliente/node_modules/webpack/node_modules/ajv/lib/compile/index.js:6:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**My `ionic info`:**

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v8.9.1
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : /Users/mcastillo/Library/Android/sdk

Misc:

    backend : legacy

**Other Information:**

Thanks.

**Comment by dwieeb** [comment]
Looks like an issue with webpack installation. Try reinstalling your npm dependencies.
