### ISSUE TITLE
CLI throwing exception on every ionic command I run.

### ISSUE THREAD

**Issue by amanvishnani** [ionic-team/ionic-cli#2892]
**Description:**

My ionic cli is crashing every time whenever I run any command such as `ionic lab` or `ionic info`.
The Same Exception is thrown when I run ionic from the local node_modules folder.

**Steps to Reproduce:**

Example repo: 

1. Run `ionic lab`
2. Press Ctrl + C
3. When prompted with `Y/N?` press `N`
4. Try to rerun command.

**Output:**

```
PS D:\Projects\DF\demandfarm-mobile> ionic
{ Error
    at new Exception (D:\Projects\DF\demandfarm-mobile\node_modules\ionic\node_modules\@ionic\cli-utils\lib\errors.js:8:23)
    at new FatalException (D:\Projects\DF\demandfarm-mobile\node_modules\ionic\node_modules\@ionic\cli-utils\lib\errors.js:17:9)
    at Config.<anonymous> (D:\Projects\DF\demandfarm-mobile\node_modules\ionic\node_modules\@ionic\cli-utils\lib\config.js:61:35)
    at Generator.throw (<anonymous>)
    at rejected (D:\Projects\DF\demandfarm-mobile\node_modules\ionic\node_modules\tslib\tslib.js:101:69)
    at <anonymous> name: 'Exception', exitCode: 1, fatal: true }
```

```
PS D:\Projects\DF\demandfarm-mobile> .\node_modules\.bin\ionic.cmd info --verbose
{ Error
    at new Exception (D:\Projects\DF\demandfarm-mobile\node_modules\ionic\node_modules\@ionic\cli-utils\lib\errors.js:8:23)
    at new FatalException (D:\Projects\DF\demandfarm-mobile\node_modules\ionic\node_modules\@ionic\cli-utils\lib\errors.js:17:9)
    at Config.<anonymous> (D:\Projects\DF\demandfarm-mobile\node_modules\ionic\node_modules\@ionic\cli-utils\lib\config.js:61:35)
    at Generator.throw (<anonymous>)
    at rejected (D:\Projects\DF\demandfarm-mobile\node_modules\ionic\node_modules\tslib\tslib.js:101:69)
    at <anonymous> name: 'Exception', exitCode: 1, fatal: true }
```

I tried reinstalling local and global ionic package as well as reinstalling nodejs + removing npm global files and npm-cache folder. But could not resolve this problem.
I think ionic maintains a separate set of files which are affecting this problem.
**My `ionic info`:**

```
ionic: 3.18.0
node: v9.0.0
npm: v5.5.1
```

**Other Information:**

**Comment by amanvishnani** [comment]
**Update**

Deleting `C:\Users\{username}\.ionic`  fixed my problem.
