### ISSUE TITLE
CLI problem - Can't add IOS platform Error 404 Not Found: IOS@latest

### ISSUE THREAD

**Issue by Shtibel** [ionic-team/ionic-cli#2927]
Hi all I have an emergency problem please help ASAP !!!

I built an application win for android, all worked grate.
Now I am trying to build it for IOS on a Mac.
When I run: ionic cordova platform add IOS
I get this Error:

```
Error: Failed to fetch platform IOS
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: IOS@latest

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/…/.npm/_logs/2017-12-18T18_22_27_884Z-debug.log

[ERROR] Exception:

```
This is the first time ever I get this error.
I build 10+ apps till now with no problem.
What can be the problem and how can I fix it?

Here is the full log:

```
0 info it worked if it ends with ok
1 verbose cli [ ‘/usr/local/Cellar/node/8.9.1/bin/node’,
1 verbose cli ‘/usr/local/bin/npm’,
1 verbose cli ‘install’,
1 verbose cli ‘IOS’,
1 verbose cli ‘–production’,
1 verbose cli ‘–save-exact’ ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session d680010d168d73f6
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/IOS 2125ms
8 silly fetchPackageMetaData error for IOS@latest 404 Not Found: IOS@latest
9 verbose stack Error: 404 Not Found: IOS@latest
9 verbose stack at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack at runCallback (timers.js:789:20)
9 verbose stack at tryOnImmediate (timers.js:751:5)
9 verbose stack at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd /…/ionic/web-recipes
11 verbose Darwin 16.7.0
12 verbose argv “/usr/local/Cellar/node/8.9.1/bin/node” “/usr/local/bin/npm” “install” “IOS” “–production” "–save-exact"
13 verbose node v8.9.1
14 verbose npm v5.5.1
15 error code E404
16 error 404 Not Found: IOS@latest
17 verbose exit [ 1, true ]

```
See the image attached
![screen shot 2017-12-18 at 20 25 03](https://user-images.githubusercontent.com/24429607/34122927-9c800a3e-e436-11e7-8081-167b567c8285.png)

I try to reinstall ionic, did not help.
I try to update npm, did not help

**Comment by Shtibel** [comment]
the problem was upper case in IOS
needed to enter lower case ios...
