### ISSUE TITLE
ionic -v resulting in exception

### ISSUE THREAD

**Issue by Mukund07** [ionic-team/ionic-cli#2939]
**Description:**

with every ionic command i run, there is this dependency warning: this warning persists even after installing ios-sim.
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)

******************************************************

**Steps to Reproduce:**

Example repo: 

1.ionic -v
2.
3.

**Output:**

Caught exception:
 Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1184:25)
    at Function.Module._resolveLookupPaths (module.js:419:17)
    at Function.Module._resolveFilename (module.js:522:22)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vamsi/.nvm/versions/node/v8.6.0/lib/node_modules/ionic/bin/ionic:11:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)

**My `ionic info`:**
Cordova CLI: 8.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v8.6.0
Xcode version: Xcode 9.2 Build version 9C40b

**Other Information:**

**Comment by dwieeb** [comment]
@Mukund07 Please update to the latest CLI version (`npm i -g ionic@latest`). Let me know if this is still an issue.
