### ISSUE TITLE
Ionic-CLI does not allow interactive shell input (git credentials)

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-cli#2941]
_From @wilk-polarny on January 3, 2018 16:24_

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[  ] **2.x**
[X] **3.x**
[  ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[  ] feature request

**Current behavior:**
When running cordova commands through ionic whose resulting calls issue a git command, prompted credentials cannot be entered using the shell. Shell input is not being redirected to the credential helper. The cursor at the input field stays blinking, but input is not possible, nor is it possible to SIGTERM or close the command line windows without killing the wrapped npm process.

**Expected behavior:**
Ionic-CLI shall be able to process input for issued git commands.
using cordova commands directly works, but I noticed by the way that cordova simply clones repos, Ionic rather tries to create submodules, it seems (which failed on previous versions on git for windows with an error stating a missing package.json).

**Steps to reproduce:**
Add a plugin using the Ionic-CLI with a git repo as its location requiring basic authentication.

**Related code:**

```
ionic cordova plugin add git+https://github.enterprise.tld/ORGUNIT/cordova-enterprise-plugin.git
```

**Other information:**
OS: Win10
Ionic: 3.19.0
cli-utils: 1.19.0
Ionic-Framework: 3.9.2
App-scripts: 3.1.7
Cordova: 7.1.0
Node: 6.12.0
npm: 5.6.0
git: 2.15.1.windows.2
Shell: Windows Command Line Prompt

(no direct ionic info output, I had to write it down, as the machines are air gapped)

Another odd thing is, that the git credential manager for windows is not being called (even though the credential helper is set to manager, and the modal dialog setting is set to 'true'), wheras usuall git calls on the windows prompt and git bash usually trigger a modal dialog for the first time.

  

_Copied from original issue: ionic-team/ionic#13755_

**Comment by wilk-polarny** [comment]
Hi, in addition to that git+ssh fails with the following message:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'git+ssh://git@github.enterprise.tld/ORGUNIT/cordova-enterprise-plugin.git',
1 verbose cli   '--production',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v6.12.0
4 verbose npm-session 63c798e164af4658
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+ssh://git@github.enterprise.tld/ORGUNIT/cordova-enterprise-plugin.git Error while executing:
7 silly fetchPackageMetaData C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.enterprise.tld/ORGUNIT/cordova-enterprise-plugin.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData error: cannot spawn ssh: No such file or directory
7 silly fetchPackageMetaData fatal: unable to fork
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
8 verbose stack Error: exited with error code: 128
8 verbose stack     at ChildProcess.onexit (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
8 verbose stack     at emitTwo (events.js:106:13)
8 verbose stack     at ChildProcess.emit (events.js:191:7)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
9 verbose cwd C:\Users\User\git\PROJECT\IONIC
10 verbose Windows_NT 10.0.15063
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "git+ssh://git@github.enterprise.tld/ORGUNIT/cordova-enterprise-plugin.git" "--production" "--save"
12 verbose node v6.12.0
13 verbose npm  v5.6.0
14 error Error while executing:
14 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.enterprise.tld/ORGUNIT/cordova-enterprise-plugin.git
14 error
14 error error: cannot spawn ssh: No such file or directory
14 error fatal: unable to fork
14 error
14 error exited with error code: 128
15 verbose exit [ 1, true ]
```

running the cordova command itself or the git.exe command from the error message works fine, though. Still, this breaks our builds as we rely on the ionic-cli.

I suggest someone takes a look on how the ionic-cli spawns the shell and how it sets its environment (variables) for the windows command line shell.

**Comment by dwieeb** [comment]
@wilk-polarny Thanks, I don't think we're forwarding stdin to those cordova commands.

As for the "unable to fork" issue: see https://github.com/ionic-team/ionic-cli/issues/2836 -- I haven't yet been able to reproduce the issue, but it's common enough to be concerning. I see you're using cmd prompt. Does the "unable to fork" problem persist if you use Git for Windows? (Git Bash)

The best workaround for this is just to use the `cordova` CLI directly for now.

**Comment by wilk-polarny** [comment]
@dwieeb 
Thank you for the reply. All git related problems disappear if I issue the command on the git bash.
Also it seems git for windows cannot set up its environment correctly, when being called through ionic, as git.exe complains about missing "sh" and "sed", which are part of the bash script associated with git. I'm not sure why it can't build its environment. Calling the same git commands directly using the executable invoked by ionic, and lastly npm works fine too.

**Comment by fakerLinXiao** [comment]
I use inquirer.js in ionic CLI hook, but can not input Y/N.
