### ISSUE TITLE
 creation of new blank app failed

### ISSUE THREAD

**Issue by chandanch** [ionic-team/ionic-cli#2947]
**Description:**

Trying to create a new blank from the CLI using the command:
`ionic start myapp blank`
The process stops while downloading the blank from: 
https://d2ql0qc7j8u4b2.cloudfront.net/ionic-angular-official-blank.tar.gz
The error thrown is: 
***Error***: Encountered bad status code (**400**) for https://d2ql0qc7j8u4b2.cloudfront.net/ionic-angular-official-blank.tar.gz
*This could mean the server is experiencing difficulties right now--please try again later*.

**Steps to Reproduce:**

1. Try creating a new blank app using the CLI using the command: `ionic start myapp blank`

Example repo: 
N/A

**Output:**

Error: Encountered bad status code (400) for https://d2ql0qc7j8u4b2.cloudfront.net/ionic-angular-official-blank.tar.gz
This could mean the server is experiencing difficulties right now--please try again later.
    at Request.req.on.res (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\http.js:74:28)
    at Request.emit (events.js:159:13)
    at Request._emitResponse (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:749:8)
    at ClientRequest.req.once.res (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:359:10)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:164:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at Socket.socketOnData (_http_client.js:439:20)
    at Socket.emit (events.js:159:13)

**My `ionic info`:**

cli packages: (C:\Users\admin\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.5.6
    @ionic/cli-utils        : 1.19.0
    ionic (Ionic CLI)       : 3.19.0

System:

    Node : v9.3.0
    npm  : 5.5.1
    OS   : Windows 10

Environment Variables:

    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : http://183.82.112.39:8007
    proxy            : http://183.82.112.39:8007

Misc:

    backend : pro

**Comment by dwieeb** [comment]
@chandanch I assume this is a recurring problem? What does https://d2ql0qc7j8u4b2.cloudfront.net/ionic-angular-official-blank.tar.gz actually say if you go to it in your browser?

I see you're using a proxy, would it be related to that?

**Comment by chandanch** [comment]
I removed the proxy and it worked thanks @dwieeb .
