### ISSUE TITLE
Cannot find module 'internal/fs' when ionic build iOS

### ISSUE THREAD

**Issue by nadavb** [ionic-team/ionic-cli#2954]
ionic build ios or ionic platform remove ios  does this error message:

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/Users/nadav/.nvm/versions/node/v8.2.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

Cannot find module 'internal/fs' (CLI v1.7.16)

Your system information:

Cordova CLI: 8.0.0
Ionic Framework Version: 1.1.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v8.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014 

Doing npm rebuild didn't work.

**Comment by dwieeb** [comment]
@nadavb We don't support CLI v1 anymore. Please update to the latest CLI version, which fully supports Ionic 1.
