### ISSUE TITLE
Contributing from Windows - npm run bootstrap - 'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Tiberriver256** [ionic-team/ionic-cli#2967]
Attempting to run the following command from the [contributing](https://github.com/ionic-team/ionic-cli/blob/master/CONTRIBUTING.md) guidelines:

```js
npm run bootstrap
```
I received the following error:

```
'rm' is not recognized as an internal or external command
```

**Full Error**
```
> @ bootstrap C:\My\ionic-cli
> lerna bootstrap && npm run build

lerna info version 2.8.0
lerna info versioning independent
lerna info Bootstrapping 9 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 9 packages

> @ build C:\My\ionic-cli
> lerna run build

lerna info version 2.8.0
lerna info versioning independent
lerna ERR! build Errored while running script in '@ionic/cli-framework'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! 'rm' is not recognized as an internal or external command,
lerna ERR! operable program or batch file.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @ionic/cli-framework@0.1.2 clean: `rm -rf index.* definitions.* guards.* ./lib ./utils`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @ionic/cli-framework@0.1.2 clean script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\WMRM\AppData\Roaming\npm-cache\_logs\2018-01-25T01_07_35_648Z-debug.log
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @ionic/cli-framework@0.1.2 build: `npm run clean && tsc`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @ionic/cli-framework@0.1.2 build script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\WMRM\AppData\Roaming\npm-cache\_logs\2018-01-25T01_07_35_698Z-debug.log
lerna ERR!
lerna ERR! > @ionic/cli-framework@0.1.2 build C:\My\ionic-cli\packages\@ionic\cli-framework
lerna ERR! > npm run clean && tsc
lerna ERR!
lerna ERR!
lerna ERR! > @ionic/cli-framework@0.1.2 clean C:\My\ionic-cli\packages\@ionic\cli-framework
lerna ERR! > rm -rf index.* definitions.* guards.* ./lib ./utils
lerna ERR!
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\My\ionic-cli\node_modules\lerna\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
lerna ERR! build Errored while running script in '@ionic/discover'
lerna ERR! build Errored while running script in '@ionic/schematics-angular'
{ Error: Command failed: npm run build
'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ionic/cli-framework@0.1.2 clean: `rm -rf index.* definitions.* guards.* ./lib ./utils`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ionic/cli-framework@0.1.2 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WMRM\AppData\Roaming\npm-cache\_logs\2018-01-25T01_07_35_648Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ionic/cli-framework@0.1.2 build: `npm run clean && tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ionic/cli-framework@0.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WMRM\AppData\Roaming\npm-cache\_logs\2018-01-25T01_07_35_698Z-debug.log

> @ionic/cli-framework@0.1.2 build C:\My\ionic-cli\packages\@ionic\cli-framework
> npm run clean && tsc


> @ionic/cli-framework@0.1.2 clean C:\My\ionic-cli\packages\@ionic\cli-framework
> rm -rf index.* definitions.* guards.* ./lib ./utils


    at Promise.all.then.arr (C:\My\ionic-cli\node_modules\lerna\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '\n> @ionic/cli-framework@0.1.2 build C:\\My\\ionic-cli\\packages\\@ionic\\cli-framework\n> npm run clean && tsc\n\n\n> @ionic/cli-framework@0.1.2 clean C:\\My\\ionic-cli\\packages\\@ionic\\cli-framework\n> rm -rf index.* definitions.* guards.* ./lib ./utils\n\n',
  stderr: '\'rm\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @ionic/cli-framework@0.1.2 clean: `rm -rf index.* definitions.* guards.* ./lib ./utils`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @ionic/cli-framework@0.1.2 clean script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\WMRM\\AppData\\Roaming\\npm-cache\\_logs\\2018-01-25T01_07_35_648Z-debug.log\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @ionic/cli-framework@0.1.2 build: `npm run clean && tsc`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @ionic/cli-framework@0.1.2 build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\WMRM\\AppData\\Roaming\\npm-cache\\_logs\\2018-01-25T01_07_35_698Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run build',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `lerna run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WMRM\AppData\Roaming\npm-cache\_logs\2018-01-25T01_07_35_925Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ bootstrap: `lerna bootstrap && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WMRM\AppData\Roaming\npm-cache\_logs\2018-01-25T01_07_35_989Z-debug.log
```

**Comment by Tiberriver256** [comment]
Looking at replacing the rm -rf command with [rimraf](https://github.com/isaacs/rimraf). 

Hopefully have a PR for you within a few days.
