### ISSUE TITLE
Error on serve ionic 1 app

### ISSUE THREAD

**Issue by rahulsharma841990** [ionic-team/ionic-cli#2984]
**Description:**
On ionic serve: 

```
   Running 'serve:before' gulp task before serve
[14:31:57] Starting 'wiredep'...
[14:31:57] Wiring the bower dependencies into the html
[14:31:57] Starting 'styles'...
[14:31:57] Compiling SASS --> CSS
[14:31:57] Starting 'clean-code'...
[14:31:57] Cleaning: ./src/.tmp/**/*.js,./www/js/**/*.js,./www/**/*.html
[14:31:57] Starting 'watch'...
[14:31:57] Finished 'watch' after 11 ms
[14:31:57] Finished 'clean-code' after 103 ms
[14:31:57] Starting 'templatecache'...
[14:31:57] Creating an AngularJS $templateCache
Caught exception:
 TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at DestroyableTransform._transform (C:\xampp\htdocs\genx-work\testing_errors\node_modules\wiredep\wiredep.js:135:23)
    at DestroyableTransform.Transform._read (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

[14:31:59] Finished 'styles' after 1.66 s
[14:31:59] Finished 'templatecache' after 1.62 s
```

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**
````
 Running 'serve:before' gulp task before serve
[14:31:57] Starting 'wiredep'...
[14:31:57] Wiring the bower dependencies into the html
[14:31:57] Starting 'styles'...
[14:31:57] Compiling SASS --> CSS
[14:31:57] Starting 'clean-code'...
[14:31:57] Cleaning: ./src/.tmp/**/*.js,./www/js/**/*.js,./www/**/*.html
[14:31:57] Starting 'watch'...
[14:31:57] Finished 'watch' after 11 ms
[14:31:57] Finished 'clean-code' after 103 ms
[14:31:57] Starting 'templatecache'...
[14:31:57] Creating an AngularJS $templateCache
Caught exception:
 TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at DestroyableTransform._transform (C:\xampp\htdocs\genx-work\testing_errors\node_modules\wiredep\wiredep.js:135:23)
    at DestroyableTransform.Transform._read (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\xampp\htdocs\genx-work\testing_errors\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\xampp\htdocs\genx-work\testing_errors\node_modules\gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

[14:31:59] Finished 'styles' after 1.66 s
[14:31:59] Finished 'templatecache' after 1.62 s
```

**My `ionic info`:**
Cordova CLI: 8.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed


**Other Information:**

**Comment by dwieeb** [comment]
@rahulsharma841990 This is happening in your gulp task (`Running 'serve:before' gulp task before serve`).

Also, we are no longer supporting CLI v2. Please upgrade your CLI ASAP.
