### ISSUE TITLE
Ionic cordova does not build with --keystore without Xorg server

### ISSUE THREAD

**Issue by pickfire** [ionic-team/ionic-cli#2996]
The need for ionic cordova to build over ssh fails when **Xorg server is not available** to be used to display the java ugly looking password prompt. Thus
```
> cordova build android --release --device -- --keystore=my-release-key.keystore --alias=alias_name --minSdkVersion=21
ANDROID_HOME=/opt/android-sdk
JAVA_HOME=/usr/lib/jvm/java-8-openjdk
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

        at build_a28o7epn5kyydakukpqtoxwly.run(/tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/build.gradle:141)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

Incremental java compilation is an incubating feature.

The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.


FAILURE: Build failed with an exception.

* Where:
Script '/tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/CordovaLib/cordova.gradle' line: 143

* What went wrong:
Failed to create component for 'dialog' reason: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
>
  No X11 DISPLAY variable was set, but this program performed an operation which requires it.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.598 secs
(node:18291) UnhandledPromiseRejectionWarning: Error: /tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/CordovaLib/cordova.gradle' line: 143

* What went wrong:
Failed to create component for 'dialog' reason: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
>
  No X11 DISPLAY variable was set, but this program performed an operation which requires it.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/tmp/asd-it/home/it/src/apiit/iwebspace/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:18291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Is there anyway sane way for ionic cordova to just prompt for the password rather than abandoning the build?
 
https://github.com/ionic-team/cordova-plugin-ionic/issues/39

**Comment by dwieeb** [comment]
@pickfire I don't know of any way other than also specifying the password in command line or via a `build.json` file.

**Comment by pickfire** [comment]
@dwieeb I thought we can't specify the password in command line? It doesn't prompt it in command line if we are not using GUI and therefore it breaks (we need to waste a lot of time rebuilding it then).

**Comment by dwieeb** [comment]
Please see these docs: https://cordova.apache.org/docs/en/latest/guide/platforms/android/#signing-an-app

**Comment by pickfire** [comment]
@dwieeb Yes, I saw that a while ago but typing password as a parameter isn't a good practice right? Others can see the arguments in processes tree and the same goes for storing the password in file.

**Comment by dwieeb** [comment]
@pickfire The password in command line is visible by anyone looking at the process tree when your build is running. The password in a `build.json` file is visible to anyone with read access. 

If you trust `root`, the file can be made safe with appropriate file permissions. If you don't trust `root`, you probably shouldn't be signing your app on that server. 

If this isn't adequate, you can file an issue with Cordova: https://issues.apache.org/jira/projects/CB/issues/CB-13589?filter=allopenissues

**Comment by pickfire** [comment]
@dwieeb Okay, I feel like that is adequate but wouldn't really want to bump an issue on Cordova issue tracker just for a simple password prompt.
