### ISSUE TITLE
error in my ionic

### ISSUE THREAD

**Issue by HannaMJ** [ionic-team/ionic-cli#3010]
TypeError: Cannot read property 'listname' of undefined
    at Object.eval [as updateDirectives] (ng:///AppModule/AddItemPage.ngfactory.js:284:43)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:8100/build/vendor.js:14692:21)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:13861:14)
    at callViewAction (http://localhost:8100/build/vendor.js:14211:21)
    at execComponentViewsAction (http://localhost:8100/build/vendor.js:14143:13)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:13867:5)
    at callViewAction (http://localhost:8100/build/vendor.js:14211:21)
    at execEmbeddedViewsAction (http://localhost:8100/build/vendor.js:14169:17)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:13862:5)
    at callViewAction (http://localhost:8100/build/vendor.js:14211:21)

what is the problem im having here? can anyone help me :(

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo is reserved for bug reports and feature requests of the Ionic CLI. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).
