### ISSUE TITLE
Using cli 4.0 RC.0 we run into an error for android release build

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-cli#3025]
**Description:**
We are testing your **4.0 RC** cli as requested in the readme file :smile:
We have an ionic 3.9.2 app, but doing a simple android release build does not work for us, this is what we have done:
```
sudo npm i -g ionic@rc
ionic cordova build android --release
```

**Steps to Reproduce:**
If we do a UNSIGNED release on a fresh IONIC3 app with your new CLI 4 RC.0 we do not get the error, not sure if the problem is the app, cordova or the SIGNING method. But for sure the problem is only on `--release` tag

But if we revert to @latest cli the build is working again.

**Output:**
This is our output what we get
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: 
java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define 
Lcom/google/android/gms/actions/ItemListIntents;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
36 actionable tasks: 3 executed, 33 up-to-date
(node:17264) UnhandledPromiseRejectionWarning: Error: 
/home/michi/software/workspace/web-client-ionic/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: 
java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define 
Lcom/google/android/gms/actions/ItemListIntents;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
     at ChildProcess.whenDone 
(/home/michi/software/workspace/web-client-ionic/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
     at emitTwo (events.js:126:13)
     at ChildProcess.emit (events.js:214:7)
     at maybeClose (internal/child_process.js:925:16)
     at Socket.stream.socket.on (internal/child_process.js:346:11)
     at emitOne (events.js:116:13)
     at Socket.emit (events.js:211:7)
     at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:17264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing 
inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
(rejection id: 1)
(node:17264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise 
rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**My `ionic info`:**
```
cli packages: (/usr/lib/node_modules)
   @ionic/cli-utils  : 2.0.0-rc.0
   ionic (Ionic CLI) : 4.0.0-rc.0

global packages:
   cordova (Cordova CLI) : 8.0.0 

local packages:
   @ionic/app-scripts : 3.1.8
   Cordova Platforms  : android 6.4.0
   Ionic Framework    : ionic-angular 3.9.2

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v8.10.0
   npm               : 5.7.1 
   OS                : Linux 4.13

Environment Variables:
   ANDROID_HOME : /abc/android/sdk
```

**Comment by rdlabo** [comment]
I try android build in Ionic v3 Project , and successful.
Will your symptoms be reproduced in a new v3 project?

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.0
   ionic (Ionic CLI) : 4.0.0-rc.0

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @ionic/app-scripts : 3.1.2
   Cordova Platforms  : android 7.0.0 ios 4.5.4
   Ionic Framework    : ionic-angular 3.9.2

System:

   Android SDK Tools : 25.2.3
   ios-deploy        : 1.9.2
   ios-sim           : 3.1.1
   NodeJS            : v8.9.3
   npm               : 5.7.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

   ANDROID_HOME : /Users/sakakibara/Library/Android/sdk
```

**Comment by dwieeb** [comment]
@mburger81 I am also not able to reproduce this issue. After you try a new project as @rdlabo suggested, also try Cordova 7 and the older version of `cordova-android`.

**Comment by mburger81** [comment]
I think it must be a combination of the installed cordova plugins, if we install this plugins into a fresh ionic-angular build we run into the issue, this are the plugins we have installed


<plugin name="ionic-plugin-keyboard" spec="2.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="1.1.16" />
    <plugin name="cordova-plugin-ble-central" spec="1.1.4" />
    <plugin name="cordova-plugin-fcm" spec="2.1.2" />
    <plugin name="cordova-plugin-local-notification" spec="0.9.0-beta.3" />
    <plugin name="cordova-plugin-network-information" spec="2.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.1" />
    <plugin name="cordova-sqlite-storage" spec="2.3.0" />
    <engine name="android" spec="7.1.0" />
