### ISSUE TITLE
Testing Ionic 4 - [ERROR] Error with .\aeion-4\.angular-cli.json file: FILE_NOT_FOUND

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-cli#3074]
**Description:**
.angular-cli.json file: FILE_NOT_FOUND

**Steps to Reproduce:**
Create new project

**Output:**

```
C:\ae\adaept.com>ionic start

Every great app needs a name!

You can change this at any time. To bypass this prompt next time, supply name, the first argument to ionic start.

? Project name: aeion4
[INFO] Using aeion-4 for --project-id.

What type of project would you like to create?

We recommend angular. To learn more about project types, see the CLI documentation[1]. To bypass this prompt next time,
supply the --type option.

[1]: https://ionicframework.com/docs/cli/starters.html

? Project type: angular

Let's pick the perfect starter template!

Starter templates are ready-to-go Ionic apps that come packed with everything you need to build your app. To bypass this
prompt next time, supply template, the second argument to ionic start.

? Starter template: blank
√ Preparing directory .\aeion-4 - done!
√ Downloading and extracting blank starter - done!
? Would you like to integrate your new app with Cordova to target native iOS and Android? Yes
> ionic integrations enable cordova --quiet
√ Downloading integration cordova - done!
√ Copying integrations files to project - done!
[OK] Integration cordova added!
[ERROR] Error with .\aeion-4\.angular-cli.json file: FILE_NOT_FOUND

Installing dependencies may take several minutes.

     *   IONIC  DEVAPP   *

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -     Test on iOS and Android without Native SDKs
  -     LiveReload for instant style and JS updates

 -->    Install DevApp: https://bit.ly/ionic-dev-app    <--
. . .
```

**My `ionic info`:**
Rename folder from aeion-4 to aeion4 (what I want)

```
C:\ae\adaept.com>dir
 Volume in drive C is XMAS
 Volume Serial Number is E605-5540

 Directory of C:\ae\adaept.com

04/09/2018  09:47 PM    <DIR>          .
04/09/2018  09:47 PM    <DIR>          ..
03/22/2018  09:29 PM    <DIR>          aedh
04/05/2018  08:58 PM    <DIR>          aegit
11/07/2017  10:54 PM    <DIR>          aegit_Template
04/09/2018  09:50 PM    <DIR>          aeion-4
04/09/2018  09:38 PM    <DIR>          aeion4zzz
03/24/2018  11:47 PM    <DIR>          aeprime
02/25/2018  05:55 PM    <DIR>          aezdb
02/25/2018  08:42 PM    <DIR>          arehta
04/08/2018  06:00 PM    <DIR>          pica
03/26/2018  08:48 PM    <DIR>          test-side-menu-content
03/23/2018  09:02 PM    <DIR>          test-side-menu-content - Copy
               0 File(s)              0 bytes
              13 Dir(s)  204,663,521,280 bytes free

C:\ae\adaept.com>
C:\ae\adaept.com>cd aeion4

C:\ae\adaept.com\aeion4>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.3
   ionic (Ionic CLI) : 4.0.0-rc.3

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.1
   @angular-devkit/schematics : 0.5.1
   @angular/cli               : 6.0.0-rc.2
   @ionic/schematics-angular  : 1.0.0-rc.4
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.1

System:

   NodeJS : v8.9.4
   npm    : 5.6.0
   OS     : Windows 10

```

**Other Information:**

**Comment by peterennis** [comment]
The file does exist in the folder:

![capture268](https://user-images.githubusercontent.com/140737/38537142-cad8bdf0-3c41-11e8-996a-edf2e5fa8a29.png)

**Comment by dwieeb** [comment]
@peterennis I'm not sure what caused that, but please update your CLI to RC.4. This is the Angular 6 upgrade, so the config file changed from `.angular-cli.json` to `angular.json`.

**Comment by peterennis** [comment]
Try with cordova prepare

Error: Local workspace file ('angular.json') could not be found.

```
C:\ae\adaept.com\aeion4>ionic cordova prepare android
√ Creating .\www directory for you - done!
? Platform android is not installed! Would you like to install it? Yes
> cordova platform add android --save
Using cordova-fetch for cordova-android@~7.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.ionic.starter
        Name: aeion4
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected
Android Studio project detected
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

                This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous
platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for android
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for android
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for android
Adding cordova-plugin-ionic-webview to package.json
Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
Discovered plugin "cordova-plugin-ionic-keyboard" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-keyboard" for android
Adding cordova-plugin-ionic-keyboard to package.json
Saved plugin info for "cordova-plugin-ionic-keyboard" to config.xml
--save flag or autosave detected
Saving android@~7.0.0 into config.xml file ...
> ng build --base-href=file:///android_asset/www/
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
     at WorkspaceLoader._getProjectWorkspaceFilePath
(C:\ae\adaept.com\aeion4\node_modules\@angular\cli\models\workspace-loader.js:37:19)
     at WorkspaceLoader.loadWorkspace
(C:\ae\adaept.com\aeion4\node_modules\@angular\cli\models\workspace-loader.js:24:21)
     at BuildCommand._loadWorkspaceAndArchitect
(C:\ae\adaept.com\aeion4\node_modules\@angular\cli\models\architect-command.js:151:32)
     at BuildCommand.<anonymous> (C:\ae\adaept.com\aeion4\node_modules\@angular\cli\models\architect-command.js:45:25)
     at Generator.next (<anonymous>)
     at C:\ae\adaept.com\aeion4\node_modules\@angular\cli\models\architect-command.js:7:71
     at new Promise (<anonymous>)
     at __awaiter (C:\ae\adaept.com\aeion4\node_modules\@angular\cli\models\architect-command.js:3:12)
     at BuildCommand.initialize (C:\ae\adaept.com\aeion4\node_modules\@angular\cli\models\architect-command.js:44:16)
     at C:\ae\adaept.com\aeion4\node_modules\@angular\cli\models\command-runner.js:57:23
[ERROR] An error occurred while running subprocess ng.

        ng build --base-href=file:///android_asset/www/ exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.


C:\ae\adaept.com\aeion4>
```

**Comment by peterennis** [comment]
Kill the project, create new, copy assets, success.

https://aeion4.adaept.com/

```
C:\ae\adaept.com\aeion4>ionic build
> ng build
Date: 2018-04-11T05:38:40.540Z
Hash: bd392c191414642b5367
Time: 12367ms
chunk {main} main.js, main.js.map (main) 17.5 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 226 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.09 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 21.1 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.79 MB [initial] [rendered]

C:\ae\adaept.com\aeion4>firebase init

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\ae\adaept.com\aeion4

Before we get started, keep in mind:

  * You are currently outside your home directory

? Are you ready to proceed? Yes
? Which Firebase CLI features do you want to setup for this folder? Press Space to select features, then Enter to confi
rm your choices.

Error: Must select at least one feature. Use SPACEBAR to select features, or provide a feature with firebase init [feature_name]

C:\ae\adaept.com\aeion4>firebase init

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\ae\adaept.com\aeion4

Before we get started, keep in mind:

  * You are currently outside your home directory

? Are you ready to proceed? Yes
? Which Firebase CLI features do you want to setup for this folder? Press Space to select features, then Enter to confi
rm your choices. Hosting: Configure and deploy Firebase Hosting sites

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Select a default Firebase project for this directory: aeion4-dev (aeion4-dev)

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

? What do you want to use as your public directory? www
? Configure as a single-page app (rewrite all urls to /index.html)? Yes
? File www/index.html already exists. Overwrite? No
i  Skipping write of www/index.html

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

+  Firebase initialization complete!

C:\ae\adaept.com\aeion4>firebase deploy

=== Deploying to 'aeion4-dev'...

i  deploying hosting
i  hosting: preparing www directory for upload...
+  hosting: 926 files uploaded successfully

+  Deploy complete!

Project Console: https://console.firebase.google.com/project/aeion4-dev/overview
Hosting URL: https://aeion4-dev.firebaseapp.com

C:\ae\adaept.com\aeion4>
```

**Comment by peterennis** [comment]
@dwieeb, The ionic slides do not auto fit correctly.
Check the demo using a phone.
https://aeion4.adaept.com/
Where should I open a ticket?

**Comment by dwieeb** [comment]
@peterennis Yep, it needs a new project to work.

As for the slides, please open a ticket in the Ionic repo: https://github.com/ionic-team/ionic
