### ISSUE TITLE
Ionic CLI 4 is broken now ??

### ISSUE THREAD

**Issue by thruthesky** [ionic-team/ionic-cli#3075]
**Description:**

I installed Ionic v4 today. and I see error
```
[ERROR] Error with ./site/.angular-cli.json file: FILE_NOT_FOUND
```

After installing, `.angular-cli.json` does not exists. Instead, I could see `angular.json`.

And I ran ` $ ionic s ` and it's dead.

```
~/apps/site $ ionic s
> ng serve --host=0.0.0.0 --port=8100 --progress=false
[ng] Schema validation failed with the following errors:
[ng]   Data path "" should NOT have additional properties (progress).
[ng] Error: Schema validation failed with the following errors:
[ng]   Data path "" should NOT have additional properties (progress).
[ng]     at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:145:42)
[ng]     at MergeMapSubscriber._tryNext (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
[ng]     at MergeMapSubscriber._next (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
[ng]     at MergeMapSubscriber.Subscriber.next (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:103:18)
[ng]     at MergeMapSubscriber.notifyNext (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
[ng]     at InnerSubscriber._next (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
[ng]     at InnerSubscriber.Subscriber.next (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:103:18)
[ng]     at MapSubscriber._next (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:92:26)
[ng]     at MapSubscriber.Subscriber.next (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:103:18)
[ng]     at SwitchMapSubscriber.notifyNext (/Users/thruthesky/apps/site/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:122:26)

[OK] Development server running!

     Local: http://localhost:8100
     External: http://192.168.0.70:8100
     DevApp: site@8100 on JaeHos-MacBook-Pro.local

[INFO] Browser window opened to http://localhost:8100!

```

**Steps to Reproduce:**

Create a new project and run.

**Output:**

It's not working. `.angular-cli.json` is missing and it opens blank page in browser.

**My `ionic info`:**

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.3
   ionic (Ionic CLI) : 4.0.0-rc.3

local packages:

   @angular-devkit/core       : 0.5.1
   @angular-devkit/schematics : 0.5.1
   @angular/cli               : 6.0.0-rc.2
   @ionic/schematics-angular  : 1.0.0-rc.4
   Ionic Framework            : @ionic/angular 4.0.0-alpha.1

System:

   NodeJS : v8.9.4
   npm    : 5.8.0
   OS     : macOS High Sierra
```

**Other Information:**

**Comment by dwieeb** [comment]
@thruthesky With the Ionic CLI RC.4 update, we're using Angular 6 for starters. This was a big breaking change, but hey, it's an experimental feature on a release candidate. Please update: `npm i -g ionic@rc`. The apps created with the RC CLI for Angular 5 won't work. Angular 6 changed the name and structure of the config file.

**Comment by thruthesky** [comment]
@dwieeb Thank you. My mistake.
