### ISSUE TITLE
Cannot run in Cordova mode with V4 project using Angular CLI >6.0.0-rc.3

### ISSUE THREAD

**Issue by cwoolum** [ionic-team/ionic-cli#3102]
**Description:**

When trying to use the V4 CLI to run a project with Cordova using ```ionic cordova run browser -lcs```, I get the error 

```
[ng] Schema validation failed with the following errors:
[ng]   Data path "" should NOT have additional properties(deleteOutputPath).
[ng] Error: Schema validation failed with the following errors:
[ng]   Data path "" should NOT have additional properties(deleteOutputPath).
[ng]     at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (C:\Users\slick\Source\Repos\GroupSplit\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\workspace\workspace.js:139:42)
[ng]     at MergeMapSubscriber._tryNext (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\operators\mergeMap.js:122:27)
[ng]     at MergeMapSubscriber._next (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\operators\mergeMap.js:112:18)
[ng]     at MergeMapSubscriber.Subscriber.next (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\Subscriber.js:103:18)
[ng]     at MergeMapSubscriber.notifyNext (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\operators\mergeMap.js:141:26)
[ng]     at InnerSubscriber._next (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\InnerSubscriber.js:30:21)
[ng]     at InnerSubscriber.Subscriber.next (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\Subscriber.js:103:18)
[ng]     at MapSubscriber._next (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\operators\map.js:92:26)
[ng]     at MapSubscriber.Subscriber.next (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\Subscriber.js:103:18)
[ng]     at SwitchMapSubscriber.notifyNext (C:\Users\slick\Source\Repos\GroupSplit\node_modules\rxjs\internal\operators\switchMap.js:122:26)
```

when using @angular/cli@6.0.0-rc.3. If I update to RC5, I get a much more useful 

```
 ionic:cli-utils Terminal info: { tty: true, ci: false } +0ms
  ionic:cli-utils:lib:project Project type from config: Ionic Angular v4+ (angular) +0ms
  ionic:cli-utils:lib:environment Environment open. +0ms
  ionic:cli-utils CLI flags: { interactive: true, confirm: false } +791ms
  ionic:cli Context: { binPath: 'C:\\Users\\slick\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath: 'C:\\Users\\slick\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js', execPath: 'C:\\Users\\slick\\Source\\Repos\\GroupSplit', version: '4.0.0-rc.5' } +0ms
  ionic:cli-utils:lib:integrations:cordova:config Using config.xml: C:\Users\slick\Source\Repos\GroupSplit\config.xml +0ms
  ionic:cli-utils:lib:integrations:cordova:config Using config.xml: C:\Users\slick\Source\Repos\GroupSplit\config.xml +43ms
  ionic:cli-utils:lib:hooks Looking for ionic:serve:before npm script. +0ms
  ionic:cli-utils:lib:project:angular:utils Adding Cordova engine for platform: browser +0ms
  ionic:cli-utils:lib:project:angular:utils Adding Cordova assets to angular.json: { glob: '**/*', input: 'C:\\Users\\slick\\Source\\Repos\\GroupSplit\\platforms\\browser\\platform_www', output: './' } +3ms
  ionic:cli-utils:lib:project:angular:utils Inserting Cordova HTML within C:\Users\slick\Source\Repos\GroupSplit\src +6ms
  ionic:cli-utils:lib:project:angular:serve None of the following proxy files found: proxy.conf.json, proxy.conf.js, proxy.config.json, proxy.config.js +0ms
  ionic:cli-utils:lib:project:angular:serve Looking for ionic:serve npm script. +2ms
> ng serve --host=0.0.0.0 --port=8100 --delete-output-path=false
  ionic:cli-utils:lib:project:angular:serve waiting for connectivity with ng serve (20000ms timeout) +50ms
[ng] Unknown option: '--deleteOutputPath'
```

**Steps to Reproduce:**

Create a new ionic project and add cordova. Try to run ```ionic cordova run android -lcs``` when Angular CLI >6.0.0-rc.3 is installed.

**Output:**

See description above

**My `ionic info`:**

```
cli packages: (C:\Users\slick\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.7
   @angular-devkit/schematics : 0.5.7
   @angular/cli               : 6.0.0-rc.5
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : browser 5.0.3
   Ionic Framework            : @ionic/angular 4.0.0-alpha.2

System:

   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set
```

**Other Information:**

**Comment by dwieeb** [comment]
Thanks @cwoolum, looks like this is leftover from the Angular CLI 1 -> 6 beta upgrade.

**Comment by cwoolum** [comment]
This may be an issue with the Angular CLI. I have added a bug there to get more information #10455

**Comment by dwieeb** [comment]
I think it's just an option that was removed. The output path (`www/`, for us) is no longer removed, so the option is meaningless.

**Comment by cwoolum** [comment]
Aaah, okay. Thanks!
