### ISSUE TITLE
Giving error while working with service worker

### ISSUE THREAD

**Issue by dishankchaudhari** [ionic-team/ionic-cli#3126]
**Description:**

hello,While i working with service worker its giving an following error after running  this "ng add  @angular/pwa --project *project-name*" command .

ERROR:
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at AddCommand._loadWorkspace (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:271:29)
    at AddCommand.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:48:18)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:3:12)
    at AddCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:47:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/command-runner.js:87:23)

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

**Comment by dwieeb** [comment]
@dishankchaudhari Your app is old. Make a new one with the new Angular 6 project structure or look into `ng update`.
