### ISSUE TITLE
error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by RaschidGithub** [ionic-team/ionic-cli#3166]
**Description:**

Some ionic commands return `error:0906D06C:PEM routines:PEM_read_bio:no start line`. I've had this problem when trying `ionic start myApp blank/sidemenu/tabs` and `ionic cordova resources`.

**Steps to Reproduce:**

1. Type in terminal `ionic cordova resources android`
or 
2. Try to start a new blank template project: `ionic start testProject blank`

**Output:**

#### `ionic start testProject blank`: ####

```
[DEBUG] Reason for not using local CLI: BASE_DIRECTORY_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'C:\\Users\\Raschid\\Git\\Cordova', local: false, binPath:
        'C:\\Users\\Raschid\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\Raschid\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Daemon found (pid: 15196)
√ Creating directory .\testProject - done!
× Downloading and extracting blank starter - failed!
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:86:19)
    at Object.exports.connect (_tls_wrap.js:1049:48)
    at Agent.createConnection (https.js:111:22)
    at Agent.createSocket (_http_agent.js:227:26)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:258:16)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at Request.request (C:\Users\Raschid\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.j
s:622:31)
    at Request.end (C:\Users\Raschid\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:76
4:8)
[DEBUG] Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
            at Object.createSecureContext (_tls_common.js:86:19)
            at Object.exports.connect (_tls_wrap.js:1049:48)
            at Agent.createConnection (https.js:111:22)
            at Agent.createSocket (_http_agent.js:227:26)
            at Agent.addRequest (_http_agent.js:185:10)
            at new ClientRequest (_http_client.js:258:16)
            at Object.request (http.js:38:10)
            at Object.request (https.js:239:15)
            at Request.request
        (C:\Users\Raschid\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:622:31)
            at Request.end
        (C:\Users\Raschid\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:764:8)
```

#### `ionic cordova resources android`: ####

```
[DEBUG] Reason for not using local CLI: LOCAL_CLI_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'C:\\Users\\Raschid\\Git\\Cordova\\AbogaDom', local: false, binPath:
        'C:\\Users\\Raschid\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\Raschid\\AppData\\Roaming\\npm\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Daemon found (pid: 15196)
[DEBUG] resourceJsonStructure=3
[DEBUG] platforms=android
[DEBUG] buildPlatforms=android
[DEBUG] getProjectPlatforms completed: android
[DEBUG] imgResources=18
[DEBUG] createImgDestinationDirectories completed: 2
[DEBUG] getSourceImages completed: (.\resources\icon.png, .\resources\splash.png)
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
× Uploading source images to prepare for transformations - failed!
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:86:19)
    at Object.exports.connect (_tls_wrap.js:1049:48)
    at Agent.createConnection (https.js:111:22)
    at Agent.createSocket (_http_agent.js:227:26)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:258:16)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at Request.request (C:\Users\Raschid\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.j
s:622:31)
    at Request.end (C:\Users\Raschid\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:76
4:8)
[DEBUG] Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
            at Object.createSecureContext (_tls_common.js:86:19)
            at Object.exports.connect (_tls_wrap.js:1049:48)
            at Agent.createConnection (https.js:111:22)
            at Agent.createSocket (_http_agent.js:227:26)
            at Agent.addRequest (_http_agent.js:185:10)
            at new ClientRequest (_http_client.js:258:16)
            at Object.request (http.js:38:10)
            at Object.request (https.js:239:15)
            at Request.request
        (C:\Users\Raschid\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:622:31)
            at Request.end
        (C:\Users\Raschid\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:764:8)
```

**My `ionic info`:**

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (C:\Users\Raschid\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v8.11.1
    npm  : 5.6.0
    OS   : Windows 10

Misc:

    backend : pro
```

**Other Information:**
I could create my project successfully when downgraded ionic to 3.10

**Comment by dwieeb** [comment]
This looks like a proxy issue. See the [CLI documentation](https://ionicframework.com/docs/cli/configuring.html#using-a-proxy) for configuration details.

**Comment by RaschidGithub** [comment]
Tnx @dwieeb . I'm seeing the documentation, but what shall I do then? I mean, what's the proxy url I should use for CLI commands? I don't recall having set up a proxy, should I have done it? or am I missing something else?

**Comment by RaschidGithub** [comment]
**$ ionic config get -g:**

```
{ state:
   { doctor: { ignored: [] },
     lastCommand: '2018-05-13T20:14:29.712Z',
     lastNoResponseToUpdate: '2018-05-11T20:46:16.772Z' },
  created: '2017-11-24T05:31:47.898Z',
  daemon: { updates: true },
  devapp: { knownInterfaces: [] },
  addresses: {},
  git: { setup: true },
  user: { id: 1154069, email: 'lachachi@gmail.com' },
  tokens: { appUser: '*****', telemetry: '*****', user: '*****' },
  backend: 'pro',
  telemetry: true,
  yarn: false,
  version: '3.20.0',
  ssl:
   { certfile: 'C:\\Users\\Raschid\\Git\\NodeJS\\proxy\\server.key' } }
```

**Comment by dwieeb** [comment]
Ahh, okay, so I'm seeing some SSL configuration here:
```
  ssl:
   { certfile: 'C:\\Users\\Raschid\\Git\\NodeJS\\proxy\\server.key' } }
```

Is that something you added?

**Comment by RaschidGithub** [comment]
Mmm I guess so... It's a path from an old project. Actually I don't even know what that does but I just changed that line in the `config.json` file to

```
ssl: {}
```

and now it looks like the problem was solved. Command `ionic start test blank` worked again! Tnx @dwieeb
