### ISSUE TITLE
Cli 4 - "ionic cordova build android" not working

### ISSUE THREAD

**Issue by sdey0081** [ionic-team/ionic-cli#3189]
**Description:**

 *ionic serve* works well, but *ionic cordova build android* throws an error

**Steps to Reproduce:**

`$ ionic cordova build android`

**Output:**

[ERROR] An error occurred while running an Ionic CLI hook defined in

        ionic.config.json.
        Hook: build:before
        File: F:\bluestacks-pwa\node_modules\@ionic\cli-hooks\add-cordova-engine.js

        Error: ENOENT: no such file or directory, open
        'F:\bluestacks-pwa\.angular-cli.json'

**My `ionic info`:**

```
$ ionic info
cli packages: (C:\Users\Admin\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-alpha.0405736c
   ionic (Ionic CLI) : 4.0.0-alpha.0405736c

global packages:

   cordova (Cordova CLI) : not installed

local packages:

   @angular/cli      : 6.0.1
   @ionic/core       : 4.0.0-alpha.7
   Cordova Platforms : android 7.0.0
   Ionic Framework   : @ionic/angular 4.0.0-alpha.7

System:

   NodeJS : v8.11.1
   npm    : 5.6.0
   OS     : Windows 10
```

**Other Information:**

**Comment by dwieeb** [comment]
@sdey0081 I would remove the hooks from `ionic.config.json` and `npm uninstall @ionic/cli-hooks`, then update to the latest RC CLI with `npm i -g ionic@rc`.

**Comment by sdey0081** [comment]
```
...
   create resources\ios\splash\Default@2x~universal~anyany.png
   create resources\ios\splash\Default~iphone.png
√ Copying integrations files to project - done!
> npm i --save -E @ionic/cli-hooks
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4
(node_modules\fsevents):
+ @ionic/cli-hooks@1.0.0-rc.1
added 1 package in 9.118s
```

**Comment by dwieeb** [comment]
@sdey0081 Do you have the CLI installed locally somehow? If you have the latest RC, it will not add that package.

**Comment by sdey0081** [comment]
that worked, thanks

**Comment by SanjanaTailor** [comment]
@sdey0081  : Thank you after struggling with this error, I am able to fix it 👍

**Comment by tkraj143** [comment]
i have face some buid errors..

ERROR NullInjectorError: StaticInjectorError(AppModule)[IonRouterOutlet -> ChildrenOutletContexts]: 
  StaticInjectorError(Platform: core)[IonRouterOutlet -> ChildrenOutletContexts]: 
    NullInjectorError: No provider for ChildrenOutletContexts!
    at NullInjector.get (http://localhost:8100/vendor.js:35988:27)
    at resolveToken (http://localhost:8100/vendor.js:37774:24)
    at tryResolveToken (http://localhost:8100/vendor.js:37700:16)
    at StaticInjector.get (http://localhost:8100/vendor.js:37563:20)
    at resolveToken (http://localhost:8100/vendor.js:37774:24)
    at tryResolveToken (http://localhost:8100/vendor.js:37700:16)
    at StaticInjector.get (http://localhost:8100/vendor.js:37563:20)
    at resolveNgModuleDep (http://localhost:8100/vendor.js:61613:29)
    at NgModuleRef_.get (http://localhost:8100/vendor.js:62701:16)
    at resolveDep (http://localhost:8100/vendor.js:63231:45)
View_AppComponent_0 @ AppComponent.html:2
AppComponent.html:2 ERROR CONTEXT DebugContext_
View_AppComponent_0 @ AppComponent.html:2
main.ts:12 NullInjectorError: StaticInjectorError(AppModule)[IonRouterOutlet -> ChildrenOutletContexts]: 
  StaticInjectorError(Platform: core)[IonRouterOutlet -> ChildrenOutletContexts]: 
    NullInjectorError: No provider for ChildrenOutletContexts!
    at NullInjector.get (http://localhost:8100/vendor.js:35988:27)
    at resolveToken (http://localhost:8100/vendor.js:37774:24)
    at tryResolveToken (http://localhost:8100/vendor.js:37700:16)
    at StaticInjector.get (http://localhost:8100/vendor.js:37563:20)
    at resolveToken (http://localhost:8100/vendor.js:37774:24)
    at tryResolveToken (http://localhost:8100/vendor.js:37700:16)
    at StaticInjector.get (http://localhost:8100/vendor.js:37563:20)
    at resolveNgModuleDep (http://localhost:8100/vendor.js:61613:29)
    at NgModuleRef_.get (http://localhost:8100/vendor.js:62701:16)
    at resolveDep (http://localhost:8100/vendor.js:63231:45)
core.js:9110 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'environment' of null
TypeError: Cannot read property 'environment' of null
    at Function.push../node_modules/@ionic-native/google-maps/index.js.Environment.setEnv (index.js:592)
    at app.component.ts:24
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Object.onInvoke (core.js:34201)
    at ZoneDelegate.invoke (zone-evergreen.js:358)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:855
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at resolvePromise (zone-evergreen.js:797)
    at zone-evergreen.js:862
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
defaultErrorLogger @ core.js:9110
client:52 [WDS] Live Reloading enabled.

i can't trace issue.. please help ,
