### ISSUE TITLE
Getting ZlibError for cordova / cordova plugin integration

### ISSUE THREAD

**Issue by dearfog** [ionic-team/ionic-cli#3278]
**Description:**

I love ionic and i am working on an application as i update ionic cli i am facing this error **everytime** as i create new project or add plugin to existing project

> ZlibError: zlib: unexpected end of file
    at Zlib.(anonymous function).onerror (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:131:21)

I have ionic 4.0.0-rc.6
```
nasiruddin@nasiruddin-PC:/$ ionic -v
4.0.0-rc.6

```

**Steps to Reproduce:**

 - Update  Angular Cli to 6

```

nasiruddin@nasiruddin-PC:/$ ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.1
Node: 10.1.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.1
@angular-devkit/core         0.6.1
@angular-devkit/schematics   0.6.1
@schematics/angular          0.6.1
@schematics/update           0.6.1
rxjs                         6.1.0
typescript                   2.7.2
    
```
**My `ionic info`:**

```
nasiruddin@nasiruddin-PC:/$ ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.
cli packages: (/usr/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

System:

   NodeJS : v10.1.0
   npm    : 6.1.0
   OS     : Linux 4.13

```

**Output:**

 

```
nasiruddin@nasiruddin-PC:/$ ionic start test123

What type of project would you like to create?

We recommend ionic-angular. To learn more about project types, see the CLI documentation[1]. To bypass this prompt next 
time, supply the --type option.

[1]: https://ionicframework.com/docs/cli/starters.html

? Project type: ionic-angular

Let's pick the perfect starter template! 💪

Starter templates are ready-to-go Ionic apps that come packed with everything you need to build your app. To bypass this 
prompt next time, supply template, the second argument to ionic start.

? Starter template: tabs
✔ Preparing directory ./test123 - done!
✔ Downloading and extracting tabs starter - done!
? Would you like to integrate your new app with Cordova to target native iOS and Android? Yes
> ionic integrations enable cordova --quiet
⠧ Downloading integration cordova (76.26%) 
events.js:167
      throw er; // Unhandled 'error' event
      ^

ZlibError: zlib: unexpected end of file
    at Zlib.(anonymous function).onerror (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:131:21)
    at Unzip.write (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:255:31)
    at Unzip.flush (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:222:10)
    at Unzip.end (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:229:10)
    at Unpack.end (/usr/lib/node_modules/ionic/node_modules/tar/lib/parse.js:415:21)
    at IncomingMessage.onend (_stream_readable.js:631:10)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Unpack.onerror (_stream_readable.js:693:12)
    at Unpack.emit (events.js:182:13)
    at Unpack.abort (/usr/lib/node_modules/ionic/node_modules/tar/lib/parse.js:266:10)
    at Unzip.(anonymous function).on.er (/usr/lib/node_modules/ionic/node_modules/tar/lib/parse.js:293:16)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/usr/lib/node_modules/ionic/node_modules/minipass/index.js:309:30)
    at Zlib.(anonymous function).onerror (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:132:12)
    at Unzip.write (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:255:31)
    at Unzip.flush (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:222:10)
    at Unzip.end (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:229:10)
```
 -  Then i created a blank project and tried to add plugin so it started to download **Codova** again error occurred 

```
nasiruddin@nasiruddin-PC:~/projectOne$ ionic cordova plugin add cordova-plugin-fcm
> ionic integrations enable cordova
⠹ Downloading integration cordova (88.95%) 
events.js:167
      throw er; // Unhandled 'error' event
      ^

ZlibError: zlib: unexpected end of file
    at Zlib.(anonymous function).onerror (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:131:21)
    at Unzip.write (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:255:31)
    at Unzip.flush (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:222:10)
    at Unzip.end (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:229:10)
    at Unpack.end (/usr/lib/node_modules/ionic/node_modules/tar/lib/parse.js:415:21)
    at IncomingMessage.onend (_stream_readable.js:631:10)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Unpack.onerror (_stream_readable.js:693:12)
    at Unpack.emit (events.js:182:13)
    at Unpack.abort (/usr/lib/node_modules/ionic/node_modules/tar/lib/parse.js:266:10)
    at Unzip.(anonymous function).on.er (/usr/lib/node_modules/ionic/node_modules/tar/lib/parse.js:293:16)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/usr/lib/node_modules/ionic/node_modules/minipass/index.js:309:30)
    at Zlib.(anonymous function).onerror (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:132:12)
    at Unzip.write (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:255:31)
    at Unzip.flush (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:222:10)
    at Unzip.end (/usr/lib/node_modules/ionic/node_modules/minizlib/index.js:229:10)

```

**Other Information:**

**Package.json** of an existing project in which i want to add plugin .

```
{
  "name": "projectOne",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@ionic-native/camera": "4.3.3",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/pro": "1.0.20",
    "@ionic/storage": "2.1.3",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "config": {
    "ionic_copy": "./config/config.js"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.9",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project"
}

```

Please let me know if anything i am missing coz i have search SO and did lots of google then i am posting it bug. This is my first issue posting so beg beg my pardon. Happy Coding!!

**Comment by dwieeb** [comment]
@dearfog I would try either updating Node 10 to the latest release or switching to the latest Node 8 LTS.

**Comment by dwieeb** [comment]
@dearfog Can you answer no to the Cordova prompt? You can always add it later. I want to see if the issue is with that particular archive.

Here are the tar archives FYI:
Cordova integration: https://d2ql0qc7j8u4b2.cloudfront.net/integration-cordova.tar.gz
Starter: https://d2ql0qc7j8u4b2.cloudfront.net/ionic-angular-official-tabs.tar.gz

If you can download those and run `tar -zvxf` on each, that would be awesome!
