### ISSUE TITLE
SCSS paths do not resolve when creating production build

### ISSUE THREAD

**Issue by coreymcmahon** [ionic-team/ionic-cli#3351]
**Description:**

During AoT compilation, our stylesheets cannot be resolved unless we explicitly make them relative paths, e.g:

```typescript
/** before; doesn't work... */
@Component({
  selector: 'page-dashboard',
  templateUrl: 'dashboard.html',
  styleUrls: ['/dashboard.scss']
})
export class DashboardPage implements OnInit {/** etc... */}

/** after; DOES work... */
@Component({
  selector: 'page-dashboard',
  templateUrl: 'dashboard.html',
  styleUrls: ['./dashboard.scss']
})
export class DashboardPage implements OnInit {/** etc... */}
```

Note `./dashboard.scss` instead of `/dashboard.scss`.

Development builds are fine, it's just when we try and create a production build when get a `Couldn't resolve resource <scss file> relative to <component path>` error (see below for full stack trace).

**Steps to Reproduce:**

Run:

```
ionic cordova build ios --release --prod
```

... or:

```
ionic cordova build android --release --prod
```

**Output:**

```
> ionic cordova resources ios --force
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations - done!
✔ Generating platform resources: 32 / 32 complete - done!
✔ Modifying config.xml to add new image resources - done!
Running app-scripts build: --prod --platform ios --target cordova
[17:48:09]  build prod started ... 
[17:48:09]  clean started ... 
[17:48:09]  clean finished in 4 ms 
[17:48:09]  copy started ... 
[17:48:10]  deeplinks started ... 
[17:48:10]  deeplinks finished in 512 ms 
[17:48:10]  ngc started ... 
[17:48:19]  typescript error 
            Couldn't resolve resource /dashboard.scss relative to 
            /Users/coreymcmahon/Sites/foodkit/consumer-app/src/pages/dashboard/dashboard.ts 

Error: The Angular AoT build failed. See the issues above
    at /Users/coreymcmahon/Sites/foodkit/consumer-app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/Users/coreymcmahon/Sites/foodkit/consumer-app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/coreymcmahon/Sites/foodkit/consumer-app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/coreymcmahon/Sites/foodkit/consumer-app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
[17:48:19]  copy finished in 9.54 s 
```

**My `ionic info`:**

```
$ ionic info

cli packages: (/Users/coreymcmahon/Sites/foodkit/consumer-app/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v6.11.2
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/coreymcmahon/Library/Android/sdk

Misc:

    backend : legacy

```

**Other Information:**

This isn't a super critical issue, as we just need to change the SCSS references in each of our components before creating a production build, but obviously this shouldn't be happening.

**Comment by dwieeb** [comment]
@coreymcmahon I don't think `/dashboard.scss` would ever be valid. It would need to be `dashboard.scss` or `./dashboard.scss` to refer to a file named `dashboard.scss` in the same directory. That's just how paths work. The fact it works for dev builds is strange to me.

This is what the Angular CLI says when I try:

```
$ npx ng build --prod

Date: 2018-07-09T18:12:27.972Z
Hash: 263f6f15cf16bcf599b6
Time: 4512ms
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.ab1e19d9ca35121441e2.css (styles) 1.84 kB [initial] [rendered]
chunk {2} polyfills.207dcc605630215505f5.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} main.f58b96bf9bf614ca37d4.js (main) 128 bytes [initial] [rendered]

ERROR in : Couldn't resolve resource /home.page.scss relative to /my/project/src/app/pages/home/home.page.ts
```

I'm not an Angular expert, however. If you open an issue on the Angular CLI repo asking why there's a disparity between dev/prod builds while resolving resource paths, it may be more fruitful.

**Comment by coreymcmahon** [comment]
Ok, thanks for the feedback.

I'll do as suggested.
