### ISSUE TITLE
Project created with `ionic start` has no `www` commited to Git when never built

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#3488]
If you just create a new project, add the platforms etc. but don't actually built it, then check the project out on another computer you won't have a `www` folder which causes `cordova` to not recognize the project as it is looking for `www`:

```
λ cordova platform rm ios
(node:15648) UnhandledPromiseRejectionWarning: CordovaError: Current working directory is not a Cordova-based project.
    at Object.cdProjectRoot (C:\nvm\v8.11.3\node_modules\cordova\node_modules\cordova-lib\src\cordova\util.js:170:15)
    at C:\nvm\v8.11.3\node_modules\cordova\node_modules\cordova-lib\src\cordova\platform\index.js:55:40
    at _fulfilled (C:\nvm\v8.11.3\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\nvm\v8.11.3\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\nvm\v8.11.3\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\nvm\v8.11.3\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:810:14
    at flush (C:\nvm\v8.11.3\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
(node:15648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Creating the empty `www` directory solves that problem.

Solution: `.gitkeep` in `www`.

**Comment by janpio** [comment]
Meh, `www` is even in `.gitignore`.
