### ISSUE TITLE
Got error listen EADDRINUSE :::35729

### ISSUE THREAD

**Issue by CheetahDev** [ionic-team/ionic-cli#3496]
**Description:**
Since Ionic CLI v4, I get EADDRINUSE error on v1 project after having stopped the server at least once.

**Steps to Reproduce:**
* Make sure to have ionic@4.0.5
* `ionic start test sidemenu --type=ionic1`
* `cd test`
* `npm install @ionic/v1-toolkit@1.0.4`
* `ionic serve --verbose`
* Stop the server
* `ionic serve --verbose`
* Stop the server
* `ionic serve --verbose`

**Output:**
```
[v1] ... Uhoh. Got error listen EADDRINUSE :::35729 ...
[v1] Error: listen EADDRINUSE :::35729
[v1]     at Object._errnoException (util.js:1022:11)
[v1]     at _exceptionWithHostPort (util.js:1044:20)
[v1]     at Server.setupListenHandle [as _listen2] (net.js:1351:14)
[v1]     at listenInCluster (net.js:1392:12)
[v1]     at Server.listen (net.js:1476:7)
[v1]     at Server.listen (C:\dev\projects\mobile\Projects\test_new_cli_v1\node_modules\tiny-lr\src\server.js:264:19)
[v1]     at Object.<anonymous> (C:\dev\projects\mobile\Projects\test_new_cli_v1\node_modules\@ionic\v1-toolkit\dist\lib\dev-server.js:70:18)
[v1]     at Generator.next (<anonymous>)
[v1]     at fulfilled (C:\dev\projects\mobile\Projects\test_new_cli_v1\node_modules\tslib\tslib.js:104:62)
[v1]     at <anonymous>
[v1] You already have a server listening on 35729
[v1] You should stop it and try again.
[v1] Wed, 08 Aug 2018 09:24:12 GMT express:router:route new '/__ionic/dev-server.js'
[v1] Wed, 08 Aug 2018 09:24:12 GMT express:router:layer new '/__ionic/dev-server.js'
[v1] Wed, 08 Aug 2018 09:24:12 GMT express:router:route get '/__ionic/dev-server.js'
[v1] Wed, 08 Aug 2018 09:24:12 GMT express:router:layer new '/'
[v1] { Error: listen EADDRINUSE :::53703
[v1]     at Object._errnoException (util.js:1022:11)
[v1]     at _exceptionWithHostPort (util.js:1044:20)
[v1]     at Server.setupListenHandle [as _listen2] (net.js:1351:14)
[v1]     at listenInCluster (net.js:1392:12)
[v1]     at Server.listen (net.js:1476:7)
[v1]     at new WebSocketServer (C:\dev\projects\mobile\Projects\test_new_cli_v1\node_modules\ws\lib\websocket-server.js:68:20)
[v1]     at Object.<anonymous> (C:\dev\projects\mobile\Projects\test_new_cli_v1\node_modules\@ionic\v1-toolkit\dist\lib\dev-server.js:107:21)
[v1]     at Generator.next (<anonymous>)
[v1]     at fulfilled (C:\dev\projects\mobile\Projects\test_new_cli_v1\node_modules\tslib\tslib.js:104:62)
[v1]     at <anonymous>
[v1]   code: 'EADDRINUSE',
[v1]   errno: 'EADDRINUSE',
[v1]   syscall: 'listen',
[v1]   address: '::',
[v1]   port: 53703 }
```

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI) : 4.0.5 (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   NodeJS : v8.9.4 (C:\dev\tools\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 7

Environment:

   ANDROID_HOME : not set
```

**Other Information:**
Workaround: kill node.exe process

PS: (very) old version of Ionic CLI used to have a smart approach. Server was started on :8100 (or something like that) and if that port was used the CLI automaticly switched to :8101 etc. This allowed us to have multiple app running at the same time (without having to specify the port or address via options). Is there any reason why this behaviour has been changed for a long time?

**Comment by dwieeb** [comment]
@CheetahDev The behavior hasn't been changed, it looks like a bug was introduced. I'm seeing this on my Windows machine.

**Comment by CheetahDev** [comment]
The behaviour I was refering to (incremental port number) was present in early (2015-2016) versions of the CLI.
