### ISSUE TITLE
CLI v4 ionic generate page not working

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic-cli#3507]
**Description:**
When trying to auto-generate pages, the CLI returns errors.

I've used `ionic generate --help` to see, how a page can be auto-generated.

It lists the following command for the page "contact": `ionic generate page contact`

**Steps to Reproduce:**

1. Checkout `ionic-conference-app` at branch `core-update`
2. Run `ionic generate page contact`
3. See error below

**Output:**

```
ionic generate page pages/test --verbose                                                                                                                                                                ✔  3957  11:37:57
  ionic:cli-utils Terminal info: { tty: true, ci: false } +0ms
  ionic:cli-utils CLI global options: { _: [ 'generate', 'page', 'pages/test' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +2ms
  ionic:cli-utils:lib:project Project type from config: ionic/angular 4 (angular) +0ms
  ionic:cli-utils Project name: undefined +127ms
  ionic:cli Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/carstenbaumhoegger/Docker/tabya/ionic-conference-app', version: '4.0.6' } +0ms
> ng generate page pages/test
Schematic "page" not found in collection "@schematics/angular".
Error: Schematic "page" not found in collection "@schematics/angular".
    at SchematicEngine.createSchematic (/Users/carstenbaumhoegger/Docker/tabya/ionic-conference-app/node_modules/@angular-devkit/schematics/src/engine/engine.js:224:23)
    at CollectionImpl.createSchematic (/Users/carstenbaumhoegger/Docker/tabya/ionic-conference-app/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at Object.getSchematic (/Users/carstenbaumhoegger/Docker/tabya/ionic-conference-app/node_modules/@angular/cli/utilities/schematics.js:43:23)
    at GenerateCommand.getOptions (/Users/carstenbaumhoegger/Docker/tabya/ionic-conference-app/node_modules/@angular/cli/models/schematic-command.js:216:40)
    at GenerateCommand.<anonymous> (/Users/carstenbaumhoegger/Docker/tabya/ionic-conference-app/node_modules/@angular/cli/commands/generate.js:45:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/carstenbaumhoegger/Docker/tabya/ionic-conference-app/node_modules/@angular/cli/commands/generate.js:11:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
  ionic:cli-utils:lib:project:angular:generate Error
  ionic:cli-utils:lib:project:angular:generate     at new BaseError (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-framework/errors.js:15:23)
  ionic:cli-utils:lib:project:angular:generate     at new BaseException (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/errors.js:6:9)
  ionic:cli-utils:lib:project:angular:generate     at new FatalException (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/errors.js:13:9)
  ionic:cli-utils:lib:project:angular:generate     at Shell.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/shell.js:76:31)
  ionic:cli-utils:lib:project:angular:generate     at Generator.throw (<anonymous>)
  ionic:cli-utils:lib:project:angular:generate     at rejected (/usr/local/lib/node_modules/ionic/node_modules/tslib/tslib.js:105:69) +0ms
[ERROR] Could not generate page.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 1 queued functions +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +29ms
```

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0

System:

   NodeJS : v10.8.0 (/usr/local/bin/node)
   npm    : 6.3.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Comment by dwieeb** [comment]
Apologies, the conference app has sometimes fallen behind during this beta. I just committed the fix: https://github.com/ionic-team/ionic-conference-app/commit/0650686b7462c1e229a024d1ab52963a0b0df53a

**Comment by carstenbaumhoegger** [comment]
great, thanks for the fast fix!
