### ISSUE TITLE
cannot build ionic project (android)

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [ionic-team/ionic-cli#3723]
**Description:**

I'm trying to build my ionic project, but it fails. I'm facing same error while I try to run ionic project.
(Build platform: android)

**Solutions I have already tried with:**
1. Using `nvm` and tried with both npm version: 10.13.0 and 8.9.3.
2. Uninstalled ionic and reinstalled.
3. Uninstalled cordova and reinstalled and also tried with lower version (6.5.0).
4. Updated `ionic-app-scripts` to latest version.
5. Removed and installed `npm-gym` ,`npm-sass`, and `windows-build-tools`.

**Output:**

```
d:\PsResources\DroidWorkspace\Pay\Pay>ionic cordova build android --verbose
  ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'build', 'android' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +8ms
  ionic Context: { binPath: 'C:\\Users\\Suroor\\AppData\\Roaming\\nvm\\v10.13.0\\node_modules\\ionic\\bin\\ionic', libPath: 'C:\\Users\\Suroor\\AppData\\Roaming\\nvm\\v10.13.0\\node_modules\\ionic', execPath: 'd:\\PsResources\\DroidWorkspace\\Pay\\Pay', version: '4.3.0' } +0ms
  ionic:lib:integrations:cordova:config Using config.xml: d:\PsResources\DroidWorkspace\Pay\Pay\config.xml +0ms
  ionic:lib:hooks Looking for ionic:build:before npm script. +0ms
  ionic:lib:hooks Invoking ionic:build:before npm script. +1ms
> npm run ionic:build:before

> Pay@0.0.1 ionic:build:before d:\PsResources\DroidWorkspace\Pay\Pay
> node ./src/bin/script.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'd:\PsResources\DroidWorkspace\Pay\Pay\src\bin\script.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Pay@0.0.1 ionic:build:before: `node ./src/bin/script.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ZiPay@0.0.1 ionic:build:before script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Suroor\AppData\Roaming\npm-cache\_logs\2018-11-01T09_06_51_370Z-debug.log
[ERROR] An error occurred while running subprocess npm.

        npm run ionic:build:before exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 1 functions +1ms
  ionic:cli-framework:utils:process error while killing process tree for 9440: { Error: Command failed: taskkill /pid 9440 /T /F
  ionic:cli-framework:utils:process ERROR: The process "9440" not found.
  ionic:cli-framework:utils:process
  ionic:cli-framework:utils:process     at ChildProcess.exithandler (child_process.js:289:12)
  ionic:cli-framework:utils:process     at ChildProcess.emit (events.js:182:13)
  ionic:cli-framework:utils:process     at maybeClose (internal/child_process.js:962:16)
  ionic:cli-framework:utils:process     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  ionic:cli-framework:utils:process   killed: false,
  ionic:cli-framework:utils:process   code: 128,
  ionic:cli-framework:utils:process   signal: null,
  ionic:cli-framework:utils:process   cmd: 'taskkill /pid 9440 /T /F' } +314ms
  ionic:cli-framework:utils:process onBeforeExit handler: error from function: { Error: Command failed: taskkill /pid 9440 /T /F
  ionic:cli-framework:utils:process ERROR: The process "9440" not found.
  ionic:cli-framework:utils:process
  ionic:cli-framework:utils:process     at ChildProcess.exithandler (child_process.js:289:12)
  ionic:cli-framework:utils:process     at ChildProcess.emit (events.js:182:13)
  ionic:cli-framework:utils:process     at maybeClose (internal/child_process.js:962:16)
  ionic:cli-framework:utils:process     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  ionic:cli-framework:utils:process   killed: false,
  ionic:cli-framework:utils:process   code: 128,
  ionic:cli-framework:utils:process   signal: null,
  ionic:cli-framework:utils:process   cmd: 'taskkill /pid 9440 /T /F' } +7ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +6ms
```

**My `ionic info`:**

```
<Ionic:

   ionic (Ionic CLI)  : 4.3.0 (C:\Users\Suroor\AppData\Roaming\nvm\v10.13.0\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.1.2, browser 4.1.0, ios 4.3.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 5 other plugins)

System:

 (D:\Software\~ProgrammingTools\SDK)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 7>
```

**Other Information:**

**Comment by dwieeb** [comment]
You have a script named `ionic:build:before` that is running a script that isn't there.

```
> npm run ionic:build:before

> Pay@0.0.1 ionic:build:before d:\PsResources\DroidWorkspace\Pay\Pay
> node ./src/bin/script.js
```

The CLI runs `ionic:build:before` and `ionic:build:after` as hooks.
