### ISSUE TITLE
error occur after upgrading to 4.3.0

### ISSUE THREAD

**Issue by ashish-eqn** [ionic-team/ionic-cli#3726]
when i updated ionic cli by cmd 
```
npm i -g ionic
```
and then trying to use ionic cli cmds, it throw following errors

```
net.js:704
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:704:11)
    at process.<anonymous> (C:\Users\%USER%\AppData\Roaming\npm\node_modules\ionic\bin\ionic:9:63)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
```

**Comment by dwieeb** [comment]
@ashish-eqn Could you change line 9 of `C:\Users\%USER%\AppData\Roaming\npm\node_modules\ionic\bin\ionic` to this:

```
process.on('unhandledRejection', function(r) { process.stderr.write(String(r)); process.exit(1); });
```

And then re-run a command.

There shouldn't be unhandled promise rejections, but I may have missed something.

**Comment by ashish-eqn** [comment]
I'm closing this issue because it has been solved after reinstalling ionic cli again
