### ISSUE TITLE
Ionic CLI 4.4 doesn't detect cordova, "cordova plugin add" doesn't work

### ISSUE THREAD

**Issue by 4gekkman** [ionic-team/ionic-cli#3758]
**Description:**
I'd installed Cordova 8.1.2 and Ionic CLI 4.4.0, tried to add the "cordova-sqlite-storage" plugin, got errors.
"ionic info" said that cordova hadn't installed. But it was.
Then I downgraded to Ionic CLI 4.3 and everything got worked. 

**Steps to Reproduce:**
npm i -g ionic cordova
cd _project_folder_
ionic init
ionic cordova plugin add cordova-sqlite-storage

**Output:**
```
  ionic:lib Terminal info: { tty: true, ci: false, windows: true } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'plugin', 'add', 'cordova-sqlite-storage' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +6ms
  ionic:lib:project Project type from config: custom (custom) +0ms
  ionic:lib:project Project details: { configPath: '/manveloff/hl_cleaning/stateless/frontend-app-client/data/ionic.config.json', errors: [], context: 'app', type: 'custom' } +0ms
  ionic Context: { binPath: '/usr/lib/node_modules/ionic/bin/ionic', libPath: '/usr/lib/node_modules/ionic', execPath: '/manveloff/hl_cleaning/stateless/frontend-app-client/data', version: '4.4.0' } +0ms
  ionic:lib:integrations:cordova:config Using config.xml: /manveloff/hl_cleaning/stateless/frontend-app-client/data/config.xml +0ms
> cordova plugin add cordova-sqlite-storage --verbose --save
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Object.<anonymous> (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:36:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
[ERROR] An error occurred while running subprocess cordova.

        cordova plugin add cordova-sqlite-storage --verbose --save exited with exit
        code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 1 functions +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +11ms
```

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI) : 4.4.0 (/usr/lib/node_modules/ionic)

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.11.4 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 3.13
```

**Other Information:**

**Comment by dwieeb** [comment]
@4gekkman Haven't been able to reproduce this yet. The error is coming from Cordova, can you just try the following in your terminal?

> cordova plugin add cordova-sqlite-storage --verbose --save
