### ISSUE TITLE
Cannot install due to 401 Unauthorized error(s)

### ISSUE THREAD

**Issue by zarko-tg** [ionic-team/ionic-cli#3764]
Some weird problem today and only on one of my Macs 10.14.1 (on the same network).

~$ npm i -g ionic
npm ERR! code E401
npm ERR! 401 Unauthorized: @ionic/cli-framework@1.5.0

Installation fails whether it's the latest version (4.5.0) or the previous (4.4.0). Tried with both NodeJS 10.13.0 and the new one 10.14.0, same problem.

I tried cleaning the NPM cache, uninstalling/installing ionic, system restart, but still no luck.

Installation of any other global modules works just fine.

Full NPM log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/zarko/.nvm/versions/node/v10.13.0/bin/node',
1 verbose cli   '/Users/zarko/.nvm/versions/node/v10.13.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose npm-session 470dffc35b5b24cb
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/ionic 146ms (from cache)
8 silly pacote tag manifest for ionic@latest fetched in 183ms
9 timing stage:loadCurrentTree Completed in 347ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule ionic@4.5.0 checking installable status
17 http fetch GET 401 https://registry.npmjs.org/@ionic%2fcli-framework 47ms
18 silly fetchPackageMetaData error for @ionic/cli-framework@1.5.0 401 Unauthorized: @ionic/cli-framework@1.5.0
19 http fetch GET 401 https://registry.npmjs.org/@ionic%2futils-fs 56ms
20 silly fetchPackageMetaData error for @ionic/utils-fs@0.0.5 401 Unauthorized: @ionic/utils-fs@0.0.5
21 http fetch GET 401 https://registry.npmjs.org/@ionic%2fdiscover 61ms
22 silly fetchPackageMetaData error for @ionic/discover@1.0.8 401 Unauthorized: @ionic/discover@1.0.8
23 http fetch GET 304 https://registry.npmjs.org/chalk 101ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/log-update 56ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/os-name 44ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/lodash 100ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/diff 105ms (from cache)
28 http fetch GET 304 https://registry.npmjs.org/leek 103ms (from cache)
29 http fetch GET 304 https://registry.npmjs.org/opn 52ms (from cache)
30 silly pacote range manifest for log-update@^2.3.0 fetched in 63ms
31 silly resolveWithNewModule log-update@2.3.0 checking installable status
32 silly pacote range manifest for chalk@^2.3.0 fetched in 110ms
33 silly resolveWithNewModule chalk@2.4.1 checking installable status
34 silly pacote range manifest for os-name@^3.0.0 fetched in 52ms
35 silly resolveWithNewModule os-name@3.0.0 checking installable status
36 http fetch GET 304 https://registry.npmjs.org/debug 113ms (from cache)
37 silly pacote range manifest for lodash@^4.17.5 fetched in 109ms
38 silly resolveWithNewModule lodash@4.17.11 checking installable status
39 http fetch GET 304 https://registry.npmjs.org/elementtree 114ms (from cache)
40 silly pacote range manifest for diff@^3.4.0 fetched in 120ms
41 silly resolveWithNewModule diff@3.5.0 checking installable status
42 silly pacote version manifest for leek@0.0.24 fetched in 119ms
43 silly resolveWithNewModule leek@0.0.24 checking installable status
44 silly pacote range manifest for opn@^5.2.0 fetched in 69ms
45 silly resolveWithNewModule opn@5.4.0 checking installable status
46 silly pacote range manifest for debug@^4.0.0 fetched in 130ms
47 silly resolveWithNewModule debug@4.1.0 checking installable status
48 silly pacote range manifest for elementtree@^0.1.7 fetched in 134ms
49 silly resolveWithNewModule elementtree@0.1.7 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/semver 70ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/split2 69ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/ssh-config 72ms (from cache)
53 silly pacote range manifest for split2@^3.0.0 fetched in 75ms
54 silly resolveWithNewModule split2@3.0.0 checking installable status
55 silly pacote range manifest for semver@^5.5.0 fetched in 76ms
56 silly resolveWithNewModule semver@5.6.0 checking installable status
57 http fetch GET 304 https://registry.npmjs.org/through2 63ms (from cache)
58 http fetch GET 304 https://registry.npmjs.org/tslib 60ms (from cache)
59 silly pacote range manifest for ssh-config@^1.1.1 fetched in 79ms
60 silly resolveWithNewModule ssh-config@1.1.3 checking installable status
61 http fetch GET 304 https://registry.npmjs.org/tar 69ms (from cache)
62 http fetch GET 304 https://registry.npmjs.org/superagent 82ms (from cache)
63 silly pacote range manifest for through2@^3.0.0 fetched in 74ms
64 silly resolveWithNewModule through2@3.0.0 checking installable status
65 silly pacote range manifest for tslib@^1.9.0 fetched in 70ms
66 silly resolveWithNewModule tslib@1.9.3 checking installable status
67 silly pacote range manifest for tar@^4.3.0 fetched in 78ms
68 silly resolveWithNewModule tar@4.4.8 checking installable status
69 http fetch GET 304 https://registry.npmjs.org/update-notifier 64ms (from cache)
70 silly pacote range manifest for superagent@^3.8.2 fetched in 91ms
71 silly resolveWithNewModule superagent@3.8.3 checking installable status
72 silly pacote range manifest for update-notifier@^2.3.0 fetched in 67ms
73 silly resolveWithNewModule update-notifier@2.5.0 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/superagent-proxy 90ms (from cache)
75 silly pacote range manifest for superagent-proxy@^2.0.0 fetched in 91ms
76 silly resolveWithNewModule superagent-proxy@2.0.0 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/uuid 29ms (from cache)
78 silly pacote range manifest for uuid@^3.2.1 fetched in 32ms
79 silly resolveWithNewModule uuid@3.3.2 checking installable status
80 http fetch GET 401 https://registry.npmjs.org/@ionic%2futils-network 257ms
81 silly fetchPackageMetaData error for @ionic/utils-network@0.0.4 401 Unauthorized: @ionic/utils-network@0.0.4
82 timing stage:rollbackFailedOptional Completed in 1ms
83 timing stage:runTopLevelLifecycles Completed in 629ms
84 verbose stack Error: 401 Unauthorized: @ionic/cli-framework@1.5.0
84 verbose stack     at fetch.then.res (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
84 verbose stack     at tryCatcher (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
84 verbose stack     at Promise._settlePromiseFromHandler (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
84 verbose stack     at Promise._settlePromise (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
84 verbose stack     at Promise._settlePromise0 (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
84 verbose stack     at Promise._settlePromises (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
84 verbose stack     at Async._drainQueue (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
84 verbose stack     at Async._drainQueues (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
84 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/zarko/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
84 verbose stack     at runCallback (timers.js:705:18)
84 verbose stack     at tryOnImmediate (timers.js:676:5)
84 verbose stack     at processImmediate (timers.js:658:5)
85 verbose cwd /Users/zarko
86 verbose Darwin 18.2.0
87 verbose argv "/Users/zarko/.nvm/versions/node/v10.13.0/bin/node" "/Users/zarko/.nvm/versions/node/v10.13.0/bin/npm" "i" "-g" "ionic"
88 verbose node v10.13.0
89 verbose npm  v6.4.1
90 error code E401
91 error 401 Unauthorized: @ionic/cli-framework@1.5.0
92 verbose exit [ 1, true ]
```

**Comment by bhavincb** [comment]
+1

**Comment by zarko-tg** [comment]
The following is likely related / what caused it:
https://blog.npmjs.org/post/180599338975/401-scoped-packages

**Comment by zarko-tg** [comment]
Problem gone as of today.
