### ISSUE TITLE
Cannot test the app in mobile

### ISSUE THREAD

**Issue by harshitha2016** [ionic-team/ionic-cli#3804]
[ERROR] Cannot load .\config.xml

        Error: Cannot parse config.xml file: Error: No whitespace between attributes
        Line: 24
        Column: 31
        Char: s
            at error (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:666:10)
            at strictFail (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:692:7)
            at SAXParser.write
        (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:1395:13)
            at XMLParser.feed
        (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\node_modules\elementtree\lib\parsers\sax.js:48:15)
            at ElementTree.parse
        (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\node_modules\elementtree\lib\elementtree.js:271:10)
            at Object.parse
        (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\node_modules\elementtree\lib\elementtree.js:584:8)
            at ConfigXml.<anonymous>
        (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\lib\integrations\cordova\config.js:47:32)
            at Generator.next (<anonymous>)
            at fulfilled (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:104:62)
            at ConfigXml.<anonymous>
        (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\lib\integrations\cordova\config.js:51:23)
            at Generator.next (<anonymous>)
            at fulfilled (C:\Users\HARSHITHA\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:104:62)

Every time the same error is seen

**Comment by dwieeb** [comment]
You have an error in your XML file. It is telling you what and where the problem is. It must be fixed manually.
