### ISSUE TITLE
ZlibError on ionic start

### ISSUE THREAD

**Issue by morpig** [ionic-team/ionic-cli#3816]
**Description:**

Not able to create any ionic projects from the CLI.

**Steps to Reproduce:**

Run the following command:
```ionic start myApp tabs --type=angular --verbose```

**Output:**

```
Ditos-MBP:sourcetree morpig$ ionic start myApp tabs --type=angular --verbose
  ionic:bootstrap local CLI 4.7.1 found at /Users/morpig/Documents/sourcetree/node_modules/ionic/package.json +0ms
  ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'start', 'myApp', 'tabs' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, type: 'angular', project: null, '--': [] } +2ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/morpig/Documents/sourcetree', version: '4.7.1' } +0ms
? ./myApp exists. Overwrite? Yes
  ionic:lib:telemetry Sending telemetry for command: 'ionic start' [ 'myApp',
  ionic:lib:telemetry   'tabs',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--type=angular',
  ionic:lib:telemetry   '--project-id=myApp' ] +0ms
✔ Preparing directory ./myApp - done!
  ionic:commands:start Tar extraction created for /Users/morpig/Documents/sourcetree/myApp +0ms
  superagent GET https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-tabs.tar.gz +0ms
(node:10269) ExperimentalWarning: The http2 module is an experimental API.
⠹ Downloading and extracting tabs starter 
⠸ Downloading and extracting tabs starter (100.00%) 
events.js:193
      throw er; // Unhandled 'error' event
      ^

ZlibError: zlib: Cannot read property 'length' of null
    at Unzip.Zlib.(anonymous function) (/usr/local/lib/node_modules/ionic/node_modules/minizlib/index.js:126:21)
    at Unzip.write (/usr/local/lib/node_modules/ionic/node_modules/minizlib/index.js:247:21)
    at Unzip.flush (/usr/local/lib/node_modules/ionic/node_modules/minizlib/index.js:206:10)
    at Unzip.end (/usr/local/lib/node_modules/ionic/node_modules/minizlib/index.js:213:10)
    at Unpack.end (/usr/local/lib/node_modules/ionic/node_modules/tar/lib/parse.js:416:21)
    at IncomingMessage.onend (_stream_readable.js:598:10)
    at Object.onceWrapper (events.js:322:30)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
```

**My `ionic info`:**

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.7.1

System:

   NodeJS : v9.0.0
   npm    : 6.4.1
   OS     : macOS Mojave

```

**Other Information:**

**Comment by dwieeb** [comment]
@morpig Use the latest Node LTS.

**Comment by jerrymani33** [comment]
I am also facing the same issue.
Ionic:

   ionic (Ionic CLI) : 4.8.0

System:

   NodeJS : v9.2.0
   npm    : 6.6.0
   OS     : Windows 10

**Comment by dwieeb** [comment]
@jerrymani33 Use the latest NodeJS LTS.
