### ISSUE TITLE
ionic cordova resources bug

### ISSUE THREAD

**Issue by fertandil87** [ionic-team/ionic-cli#3831]
**Description:**
the command cant finish, is not a problem of the images, i am trying with the original PNGs
I didn't change anything, yesterday it was working and today not.

Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/fer/Android/Sdk)
   NodeJS            : v11.0.0 (/usr/local/bin/node)
   npm               : 6.7.0
   OS                : Linux 4.15

ionic cordova resources --icon --force

✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✔ Uploading source images to prepare for transformations: 1 / 1 complete - done!
⠸ Generating platform resources: 3 / 6 complete 
/usr/local/lib/node_modules/ionic/node_modules/superagent/lib/node/index.js:859
      throw Error("end() has already been called, so it's too late to start piping");
      ^

Error: end() has already been called, so it's too late to start piping
    at Response.response.pipe (/usr/local/lib/node_modules/ionic/node_modules/superagent/lib/node/index.js:859:13)
    at Request.req.type.send.on.res (/usr/local/lib/node_modules/ionic/lib/integrations/cordova/resources.js:166:25)
    at Request.emit (events.js:182:13)
    at Request._emitResponse (/usr/local/lib/node_modules/ionic/node_modules/superagent/lib/node/index.js:862:8)
    at ClientRequest.req.once.res (/usr/local/lib/node_modules/ionic/node_modules/superagent/lib/node/index.js:412:10)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:449:20)

**Comment by bnxio** [comment]
It looks like the service is currently down (4 hours now), got this nice obvious hint at one point. Just need to wait for it to come back up.

```
12:34:06 HTTP Error 503: POST https://res.ionic.io/api/v1/upload
12:34:06 
12:34:06 <!DOCTYPE html>
12:34:06 	<html>
12:34:06 	  <head>
12:34:06 		<meta name="viewport" content="width=device-width, initial-scale=1">
12:34:06 		<meta charset="utf-8">
12:34:06 		<title>Application Error</title>
12:34:06 		<style media="screen">
12:34:06 		  html,body,iframe {
12:34:06 			margin: 0;
12:34:06 			padding: 0;
12:34:06 		  }
12:34:06 		  html,body {
12:34:06 			height: 100%;
12:34:06 			overflow: hidden;
12:34:06 		  }
12:34:06 		  iframe {
12:34:06 			width: 100%;
12:34:06 			height: 100%;
12:34:06 			border: 0;
12:34:06 		  }
12:34:06 		</style>
12:34:06 	  </head>
12:34:06 	  <body>
12:34:06 		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
12:34:06 	  </body>
12:34:06 	</html>
12:34:06 Build step 'Execute shell' marked build as failure
```

**Comment by fertandil87** [comment]
ok thank you
