### ISSUE TITLE
Ionic 3 build fails to start with ionic cli 4.12.0

### ISSUE THREAD

**Issue by Hlaphoneo** [ionic-team/ionic-cli#3968]
**Description:**
I have ionic 3 project with ionic-app-scripts : 3.2.3.

* Ionic serve and ionic cordova build run both works on ionic cli 3 
* ionic serve works and ionic cordova build run fails on ionic cli 4.12.0 with the following output.

**Output:**
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-mto@2.1.0 ionic:build: `node --max-old-space-size=4096 node_modules/.bin/ionic-app-scripts build --prod --verbose "--target" "cordova" "--platform" "android"`
npm ERR! Exit status 1npm ERR!
npm ERR! Failed at the my-mto@2.1.0 ionic:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     C:\Users\Neo\AppData\Roaming\npm-cache\_logs\2019-05-07T08_16_07_320Z-debug.log
[ERROR] An error occurred while running subprocess npm.

        npm run ionic:build -- --target cordova --platform android exited with exit code        1.

        Re-running this command with the --verbose flag may provide more information.
```

**My `ionic info`:**

```
[WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\Neo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : not available
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 4.0.1, (and 17 other plugins)

System:

 (C:\Program Files (x86)\Android\android-sdk)
   NodeJS            : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.1.0
   OS                : Windows 10
```

**Comment by dwieeb** [comment]
Your `ionic:build` npm script is configured to run `node --max-old-space-size=4096 node_modules/.bin/ionic-app-scripts ...`, and that's not correct for Windows. If you inspect the file at `node_modules/.bin/ionic-app-scripts`, you'll notice it's a shell script, but you're trying to use that file with `node`. 

The reason you're getting the issue with CLI 4 is because `ionic:build` is used to _override_ the default build command (see [the docs](https://ionicframework.com/docs/cli/configuration#overriding-the-build)). 

Solutions:
* If you don't need to use the `ionic:build` script, consider deleting it or changing the name in your `package.json`.
* If you intended to use a custom build for your app, and want to keep that script as-is, you'll need to change it for Windows. Instead of:

    ```
    node --max-old-space-size=4096 node_modules/.bin/ionic-app-scripts ...
    ```
   Do this:
    ```
    node --max-old-space-size=4096 node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js ...
    ```
