### ISSUE TITLE
native-run not compatible with android platform-tools 29

### ISSUE THREAD

**Issue by gaurav-chandra** [ionic-team/ionic-cli#4011]
**Description:**

After updating android platform tools to version 29, native-run crashes with exit code 1.

**Steps to Reproduce:**

1) using platform tools v28.0.2 = ```$ ionic cordova run android``` the app is successfully installed on device

2) update platform tools to latest v29

3) using latest platform tools = ```$ ionic cordova run android``` native-run stops with exit code 1

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 5.0.1 (C:\Users\Gaurav's PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 30 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (C:\AndroidSDK)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Other Information:**

**Comment by gaurav-chandra** [comment]
more logs:

``` 
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk
Error: Command failed: C:\AndroidSDK\platform-tools/adb -s FA6AX0302190 shell getprop

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

```

**Comment by ME-QEOS** [comment]
If other people are stuck with this issue: a method to downgrade the platform-tools can be found on the Flutter repo.

--> https://github.com/flutter/flutter/issues/33938#issuecomment-499255056

**Comment by PhoneHan** [comment]
i have the same issue also ..

**Comment by jsoques** [comment]
I'm also experiencing the same issue.

**Comment by mightytyphoon** [comment]
Hi, yes the fix link provided by @ME-QEOS works

https://github.com/flutter/flutter/issues/33938#issuecomment-499250288

It's a temp-fix though.

**Comment by dwieeb** [comment]
I'm on Android platform-tools 29.0.0 and haven't seen this issue.

@gaurav-chandra What is the output of `native-run android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --verbose` ? Verbose logging should reveal what's going on.

**Comment by NurGuz23** [comment]
Same error here, any idea?

**Comment by gaurav-chandra** [comment]
I had to downgrade to 28.0.2.

**Comment by gaurav-chandra** [comment]
@dwieeb i have downgraded to 28.0.2 so I cannot show a verbose log.

**Comment by NurGuz23** [comment]
If I downgraded to 28.0.2, when use --device, not recognize
