### ISSUE TITLE
Error: getaddrinfo ENOTFOUND localhost

### ISSUE THREAD

**Issue by ejerskov** [ionic-team/ionic-cli#4092]
When running `ionic serve --lab` I suddenly get this error:

**Output:**
```
[INFO] Waiting for connectivity with ng...
> ionic-lab http://localhost:8100 --host localhost --port 8200 --project-type angular --app-name foodioApp --app-version 0.0.1
[lab] events.js:174
[lab]       throw er; // Unhandled 'error' event
[lab]       ^
[lab] Error: getaddrinfo ENOTFOUND localhost
[lab]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[lab] Emitted 'error' event at:
[lab]     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1455:12)
[lab]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:17)

[ERROR] ionic-lab has unexpectedly closed (exit code 1).
        
        The Ionic CLI will exit. Please check any output above for error details.

```

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 6 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : ios-sim/9.0.0-dev.1 darwin-x64 node-v10.15.1
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

**Other Information:**
I have checked my etc/hosts file and this is in the top (with other stuff below):
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1 			localhost
fe80::1%lo0     localhost
```

**Comment by dwieeb** [comment]
Are you able to access `http://localhost:8100` in your browser?

**Comment by ejerskov** [comment]
No, but I just tried `ionic serve` and that worked fine on http://localhost:8100

**Comment by dwieeb** [comment]
Would the other stuff below mess up your hosts file? Can you try it with just the vanilla hosts file? There are lots of resources online you can try to fix this:

- https://github.com/ionic-team/ionic-cli/issues/3474
- https://github.com/angular/angular-cli/issues/2227
- https://stackoverflow.com/questions/35757799/webpack-dev-server-cant-find-localhost

**Comment by ejerskov** [comment]
Yes, I just tried with only this in the host file and restarted my mac:
```
##
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting. Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0     localhost
```

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.
