### ISSUE TITLE
DeviceLocked error in ionic5

### ISSUE THREAD

**Issue by asterism612** [ionic-team/ionic-cli#4106]
[native-run] Error: DeviceLocked
[native-run]     at LockdownProtocolReader.parseBody (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/protocol/lockdown.js:35:19)
[native-run]     at LockdownProtocolReader.onData (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/protocol/protocol.js:52:40)
[native-run]     at Socket.emit (events.js:189:13)
[native-run]     at addChunk (_stream_readable.js:284:12)
[native-run]     at readableAddChunk (_stream_readable.js:265:11)
[native-run]     at Socket.Readable.push (_stream_readable.js:220:10)
[native-run]     at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
[ERROR] An error occurred while running subprocess native-run.

why?

**Comment by inameandy** [comment]
Same issue, any solution?
