### ISSUE TITLE
ionic start failed. 

### ISSUE THREAD

**Issue by nigh7m4r3** [ionic-team/ionic-cli#4116]
**Description:**
ionic start is failing to fetch starter package. The url is working if I paste it in the browser.

**Steps to Reproduce:**
`ionic start myApp tabs --verbose`

**Output:**
```ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'start', 'myApp', 'tabs' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +4ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/chayon/IonicProjects', version: '4.10.3' } +0ms
? ./myApp exists. Overwrite? Yes
  ionic:lib:telemetry Sending telemetry for command: 'ionic start' [ 'myApp',
  ionic:lib:telemetry   'tabs',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--project-id=myApp' ] +0ms
✔ Preparing directory ./myApp - done!
  ionic:commands:start Tar extraction created for /Users/chayon/IonicProjects/myApp +0ms
  superagent-proxy Request#proxy('http://a.4cdn.org') +0ms
  superagent-proxy patched superagent Request "url" property for changes +1ms
  proxy-agent creating new ProxyAgent instance: 'http://a.4cdn.org' +0ms
  https-proxy-agent creating new HttpsProxyAgent instance: Url { protocol: 'http:', slashes: true, auth: null, host: 'a.4cdn.org', port: null, hostname: 'a.4cdn.org', hash: null, search: null, query: null, pathname: '/', path: '/', href: 'http://a.4cdn.org/' } +0ms
  superagent GET https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-tabs.tar.gz +0ms
⠸ Downloading and extracting tabs starter
  https-proxy-agent got proxy server response: 'HTTP/1.1 400 Bad Request' +120ms
⠼ Downloading and extracting tabs starter (100.00%)
Error: Encountered bad status code (400) for https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-tabs.tar.gz

This could mean the server is experiencing difficulties right now--please try again later.
    at Request.req.on.res (/usr/local/lib/node_modules/ionic/lib/utils/http.js:68:28)
    at Request.emit (events.js:182:13)
    at Request._emitResponse (/usr/local/lib/node_modules/ionic/node_modules/superagent/lib/node/index.js:862:8)
    at ClientRequest.req.once.res (/usr/local/lib/node_modules/ionic/node_modules/superagent/lib/node/index.js:412:10)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at HTTPParser.parserOnIncomingClient (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:441:20)
    at Socket.emit (events.js:182:13)
  ionic Error: Encountered bad status code (400) for https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-tabs.tar.gz
  ionic This could mean the server is experiencing difficulties right now--please try again later.
  ionic     at Request.req.on.res (/usr/local/lib/node_modules/ionic/lib/utils/http.js:68:28)
  ionic     at Request.emit (events.js:182:13)
  ionic     at Request._emitResponse (/usr/local/lib/node_modules/ionic/node_modules/superagent/lib/node/index.js:862:8)
  ionic     at ClientRequest.req.once.res (/usr/local/lib/node_modules/ionic/node_modules/superagent/lib/node/index.js:412:10)
  ionic     at Object.onceWrapper (events.js:273:13)
  ionic     at ClientRequest.emit (events.js:187:15)
  ionic     at HTTPParser.parserOnIncomingClient (_http_client.js:555:21)
  ionic     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
  ionic     at Socket.socketOnData (_http_client.js:441:20)
```

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI) : 4.10.3

System:

   NodeJS : v10.11.0
   npm    : 6.8.0
   OS     : macOS Mojave
```

**Comment by dwieeb** [comment]
@nigh7m4r3 Did you intend to use `http://a.4cdn.org` as a proxy? See the CLI proxy documentation: https://ionicframework.com/docs/cli/using-a-proxy

**Comment by nigh7m4r3** [comment]
Thank you. It's resolved now.
