### ISSUE TITLE
error on ionic start

### ISSUE THREAD

**Issue by BernardA** [ionic-team/ionic-cli#4202]
**Description:**

I had [an issue](https://github.com/ionic-team/ionic-cli/issues/4201#issuecomment-549969836) with accessing `ionic start.

Once that resolved I run:
`ionic start ionic-app`

That created the `ionic-app` directory and populated it with some files - not sure how complete - but threw the error below in terminal. 

      npm ERR! code ELIFECYCLE
    npm ERR! syscall spawn sh
    npm ERR! file sh
    npm ERR! path sh
    npm ERR! errno ENOENT
    npm ERR! core-js@2.6.10 postinstall: `node postinstall || echo "ignore"`
    npm ERR! spawn sh ENOENT
    npm ERR! 
    npm ERR! Failed at the core-js@2.6.10 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/bernardo/.npm/_logs/2019-11-05T22_18_39_446Z-debug.log
      [ERROR] An error occurred while running subprocess npm.
        
        npm i exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
     events.js:174
      throw er; // Unhandled 'error' event
    Error: spawn pgrep ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Steps to Reproduce:**
Run:
`ionic start ionic-app`
choose `React`
choose the starter template `Tabs`

**Output:**

**My `ionic info`:**

```
 Ionic:

   Ionic CLI       : 5.4.5 (/usr/local/Cellar/node/11.7.0/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/local/Cellar/node/11.7.0/bin/node)
   npm    : 6.12.1
   OS     : macOS Catalina
```

**Other Information:**

**Comment by BernardA** [comment]
This is working now. It might have been an issue with migrating from `bash` to `zsh` .
