### ISSUE TITLE
Error 403 when running ionic start, and when updating the CLI

### ISSUE THREAD

**Issue by jjasspper** [ionic-team/ionic-cli#4321]
**Description:**
When initialising a project, I am getting the following error:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/22288515/74649449-dd141a00-517f-11ea-9b1e-d77582c0b187.png">

When updating the Ionic CLI, I am getting the following error:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/22288515/74649359-a63e0400-517f-11ea-93e9-d5eb635c8c36.png">

**Steps to Reproduce:**
`ionic start app sidemenu` -> select angular -> use capacitor -> error 403
`npm i -g @ionic/cli` -> error 403

**Output:**

Ionic start:
```bash
3533 verbose stack Error: 403 Forbidden - GET https://registry.npmjs.org/buffer-xor
3533 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
3533 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
3534 verbose statusCode 403
3535 verbose pkgid buffer-xor@^1.0.3
3536 verbose cwd /Users/jaspervanhienen/Workspace/Projecten/Studie/MBD1/pokedex
3537 verbose Darwin 19.3.0
3538 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
3539 verbose node v10.15.3
3540 verbose npm  v6.13.7
3541 error code E403
3542 error 403 403 Forbidden - GET https://registry.npmjs.org/buffer-xor
3543 error 403 In most cases, you or one of your dependencies are requesting
3543 error 403 a package version that is forbidden by your security policy.
3543 error 403
3543 error 403 It was specified as a dependency of 'browserify-aes'
3544 verbose exit [ 1, true ]
```

Ionic update:
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   '@ionic/cli' ]
2 info using npm@6.13.7
3 info using node@v10.15.3
4 verbose npm-session 24c3bf3977bf332e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 403 https://registry.npmjs.org/@ionic%2fcli 98ms
8 silly fetchPackageMetaData error for @ionic/cli@latest 403 Forbidden - GET https://registry.npmjs.org/@ionic%2fcli
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 138ms
11 verbose stack Error: 403 Forbidden - GET https://registry.npmjs.org/@ionic%2fcli
11 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose statusCode 403
13 verbose pkgid @ionic/cli@latest
14 verbose cwd /Users/jaspervanhienen/Workspace/Projecten/Studie/MBD1
15 verbose Darwin 19.3.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "@ionic/cli"
17 verbose node v10.15.3
18 verbose npm  v6.13.7
19 error code E403
20 error 403 403 Forbidden - GET https://registry.npmjs.org/@ionic%2fcli
21 error 403 In most cases, you or one of your dependencies are requesting
21 error 403 a package version that is forbidden by your security policy.
22 verbose exit [ 1, true ]
```

**My `ionic info`:**
```
Ionic:

   Ionic CLI : 6.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3
   npm    : 6.13.7
   OS     : macOS Catalina
```

**Comment by kensodemann** [comment]
This appears to be an issue with NPM, I received the same thing earlier getting something from NPM, tried it again, and it worked. They may be having some issues right now.

**Comment by AlexTemina-Sopra** [comment]
Same here when installing it.
