### ISSUE TITLE
ionic build --prod fails: New SubproccessError

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic-cli#4386]
**Description:**
I'm trying to build my app with the following command:
`ionic build --prod`
and I noticed my build always fail at the same time, so I tried to build with the --verbose flag and saw this:

```
+ ionic build --prod --verbose
2020-04-13T06:44:07.679Z ionic:utils-terminal Environment variables for CI detected: BUILD_ID, BUILD_NUMBER
2020-04-13T06:44:07.960Z ionic:lib Terminal info: { ci: true, shell: '/bin/bash', tty: false, windows: false }
2020-04-13T06:44:07.961Z ionic:lib CLI global options: { _: [ 'build' ], help: null, h: null, verbose: true, quiet: null, interactive: false, color: true, confirm: null, json: null, prod: true, project: null, '--': [] }
2020-04-13T06:44:08.777Z ionic:lib:project Project type from config: @ionic/angular (angular)
2020-04-13T06:44:08.778Z ionic:lib:project Project details: { configPath: '/var/lib/jenkins/workspace/app/ionic.config.json', errors: [], context: 'app', type: 'angular' }
2020-04-13T06:44:08.798Z ionic Context: { binPath: '/usr/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/lib/node_modules/@ionic/cli', execPath: '/var/lib/jenkins/workspace/app', version: '6.5.0' }
2020-04-13T06:44:08.928Z ionic:lib:build build options: { '--': [],
  engine: 'browser',
  platform: undefined,
  project: 'app',
  verbose: true,
  configuration: 'production',
  sourcemaps: undefined,
  cordovaAssets: true,
  watch: undefined,
  type: 'angular' }
2020-04-13T06:44:08.945Z ionic:lib:hooks Looking for ionic:build:before npm script.
2020-04-13T06:44:08.946Z ionic:lib:build Looking for ionic:build npm script.
> ng run app:build:production --verbose
2020-04-13T06:44:13.199Z ng:analytics getGlobalAnalytics
2020-04-13T06:44:13.201Z ng:analytics Client Analytics config found: null
2020-04-13T06:44:13.201Z ng:analytics Analytics settings not found. Ignoring all analytics.
2020-04-13T06:44:13.202Z ng:analytics getSharedAnalytics
Mon, 13 Apr 2020 06:45:47 GMT snapdragon:compiler initializing /var/lib/jenkins/workspace/app/node_modules/snapdragon/lib/compiler.js
Mon, 13 Apr 2020 06:45:47 GMT snapdragon:parser initializing /var/lib/jenkins/workspace/app/node_modules/snapdragon/lib/parser.js
Mon, 13 Apr 2020 06:45:47 GMT snapdragon:compiler initializing /var/lib/jenkins/workspace/app/node_modules/snapdragon/lib/compiler.js
Mon, 13 Apr 2020 06:45:47 GMT snapdragon:parser initializing /var/lib/jenkins/workspace/app/node_modules/snapdragon/lib/parser.js
Error

at new SubprocessError (/usr/lib/node_modules/@ionic/cli/node_modules/@ionic/utils-subprocess/dist/index.js:40:23)
at ChildProcess.p.on (/usr/lib/node_modules/@ionic/cli/node_modules/@ionic/utils-subprocess/dist/index.js:124:27)
at ChildProcess.emit (events.js:198:13)
at maybeClose (internal/child_process.js:982:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2020-04-13T06:45:58.912Z ionic Error
    at new SubprocessError (/usr/lib/node_modules/@ionic/cli/node_modules/@ionic/utils-subprocess/dist/index.js:40:23)
    at ChildProcess.p.on (/usr/lib/node_modules/@ionic/cli/node_modules/@ionic/utils-subprocess/dist/index.js:124:27)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Steps to Reproduce:**
Trying to build my app for --prod in a linux machine with 4GB RAM

**Output:**
CLI Error:

posted above

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.5.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.1
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 9.1.1
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.0
   @capacitor/core : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.19.0 (/usr/bin/node)
   npm    : 6.13.4
   OS     : Linux 3.10

```

**Comment by dwieeb** [comment]
The error is coming from the Angular CLI. Run `./node_modules/.bin/ng run app:build:production --verbose` to confirm.

**Comment by theunreal** [comment]
> ./node_modules/.bin/ng run app:build:production --verbose

Actually this command works when running directly, does Ionic set a timeout for time command ?
And is it possible to run it with higher memory?

**Comment by dwieeb** [comment]
FWIW this issue was reported before, but not resolved: https://github.com/ionic-team/ionic-cli/issues/3390

I noticed that @marcelgoya was also using Linux. There may be a bug with one of Angular CLI's dependencies on Linux relating to process management. The issue may be amplified by the Ionic CLI also running on a box with limited resources. Can you temporarily increase the RAM and see if it works? I'm not certain it's a memory issue (those tend to have scarier errors, see [this article](https://medium.com/@vuongtran/how-to-solve-process-out-of-memory-in-node-js-5f0de8f8464c)), but it would be good to check.

**Comment by theunreal** [comment]
> FWIW this issue was reported before, but not resolved: #3390
> 
> I noticed that @marcelgoya was also using Linux. There may be a bug with one of Angular CLI's dependencies on Linux relating to process management. The issue may be amplified by the Ionic CLI also running on a box with limited resources. Can you temporarily increase the RAM and see if it works? I'm not certain it's a memory issue (those tend to have scarier errors, see [this article](https://medium.com/@vuongtran/how-to-solve-process-out-of-memory-in-node-js-5f0de8f8464c)), but it would be good to check.

I'm running it on my 4GB RAM VPS and currently have no way to give it more RAM, it is using the default.

I'm not sure how to attach `node --max-old-space-size=1024` to change the memory allocation to the` ionic build --prod` command - any idea?

**Comment by dwieeb** [comment]
As with other node programs, you can run it by using `node` and pointing to the entry script. Running `which ionic` will print where the entry script is. Then run `node --max-old-space-size=1024 <path/to/ionic> <args>` instead of `ionic <args`.

**Comment by PabloSSena** [comment]
Hello, did you find a solution?
