### ISSUE TITLE
Unable to start a new project

### ISSUE THREAD

**Issue by ahunter135** [ionic-team/ionic-cli#4454]
**Description:**

when I try to create a new project, I get a tar error when it downloads and extracts.

**Steps to Reproduce:**

ionic start app sidemenu

**Output:**

? Framework: Angular
✔ Preparing directory ./iga - done!
⠴ Downloading and extracting sidemenu starter (100.00%) 
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/warn-mixin.js:19:40)
    at Unpack.warn (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/unpack.js:188:18)
    at Unpack.<anonymous> (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:82:14)
    at Unpack.emit (events.js:322:22)
    at Unpack.[emit] (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:286:12)
    at Unpack.[maybeEnd] (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:402:17)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:434:21)
    at Unpack.write (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:365:25)
    at Unpack.end (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:479:14)
    at IncomingMessage.onend (_stream_readable.js:660:10)
Emitted 'error' event on Unpack instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at Unpack.onerror (_stream_readable.js:729:7)
    at Unpack.emit (events.js:310:20)
    at Unpack.warn (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/warn-mixin.js:19:12)
    at Unpack.warn (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/unpack.js:188:18)
    [... lines matching original stack trace ...]
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:434:21) {
  recoverable: false,
  cwd: '/Users/austinhunter/iga',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'

**My `ionic info`:**

```
Ionic:

   Ionic CLI : 6.9.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Other Information:**

**Comment by altaisukh** [comment]
Same error with Ionic CLI: 6.10.0

**Comment by firoz2580** [comment]
I'm also facing same issue.

Ionic:
   Ionic CLI : 6.10.1

Utility:
   cordova-res : 0.15.1
   native-run  : 1.0.0

System:
   NodeJS : v12.18.1
   npm    : 6.14.5
   OS     : Windows 10

**Comment by firoz2580** [comment]
The issue doesn't seems to be with ionic/cli.

I think I may have messed with OS settings.
I fixed it by creating a new local user account on windows 10.

Logged in to Windows with the new account and tried to create a new project with v6.10.1.

It worked, no issue.

**Comment by yexiaodong** [comment]
Same error with Ionic CLI: 6.10.1

**Comment by jayordway** [comment]
I am seeing this issue as well.

**Comment by fbutter** [comment]
Same error with

Ionic CLI: 6.10.1
npm 6.14.5
node v14.5.0
OS: Win 10

**Comment by albertgaya** [comment]
> **Description:**
> 
> when I try to create a new project, I get a tar error when it downloads and extracts.
> 
> **Steps to Reproduce:**
> 
> ionic start app sidemenu
> 
> **Output:**
> 
> ? Framework: Angular
> ✔ Preparing directory ./iga - done!
> ⠴ Downloading and extracting sidemenu starter (100.00%)
> events.js:287
> throw er; // Unhandled 'error' event
> ^
> 
> Error: TAR_BAD_ARCHIVE: Unrecognized archive format
> at Unpack.warn (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/warn-mixin.js:19:40)
> at Unpack.warn (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/unpack.js:188:18)
> at Unpack. (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:82:14)
> at Unpack.emit (events.js:322:22)
> at Unpack.[emit] (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:286:12)
> at Unpack.[maybeEnd] (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:402:17)
> at Unpack.[consumeChunk] (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:434:21)
> at Unpack.write (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:365:25)
> at Unpack.end (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:479:14)
> at IncomingMessage.onend (_stream_readable.js:660:10)
> Emitted 'error' event on Unpack instance at:
> at errorOrDestroy (internal/streams/destroy.js:108:12)
> at Unpack.onerror (_stream_readable.js:729:7)
> at Unpack.emit (events.js:310:20)
> at Unpack.warn (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/warn-mixin.js:19:12)
> at Unpack.warn (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/unpack.js:188:18)
> [... lines matching original stack trace ...]
> at Unpack.[consumeChunk] (/usr/local/lib/node_modules/@ionic/cli/node_modules/tar/lib/parse.js:434:21) {
> recoverable: false,
> cwd: '/Users/austinhunter/iga',
> code: 'TAR_BAD_ARCHIVE',
> tarCode: 'TAR_BAD_ARCHIVE'
> 
> **My `ionic info`:**
> 
> ```
> Ionic:
> 
>    Ionic CLI : 6.9.2
> 
> Utility:
> 
>    cordova-res : not installed
>    native-run  : not installed
> 
> System:
> 
>    NodeJS : v12.16.3
>    npm    : 6.14.4
>    OS     : macOS Catalina
> ```
> 
> **Other Information:**

Can you send log with --verbose?

**Comment by vpankov** [comment]
Got same error. 
In my case, with --verbose flag it's showing some 400 error in connection to some proxy api.instagram.com
It seems that archive link is fine, but it crashing because he can't download it throat this proxy. 
Is it normal behaviour or something wrong from my side, because it seems strange, how instagram related with ionic?

UPD: Yes, it seems that it some local issue, because I don't see any proxies in logs from other device.

Ionic:

   Ionic CLI                     : 6.11.7 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina

![image](https://user-images.githubusercontent.com/10135175/101985004-23e67980-3c96-11eb-99d0-1312d734e43c.png)

**Comment by gilbertsmink** [comment]
Found a solution that worked for me:

https://forum.ionicframework.com/t/cannot-complete-ionic-start-command/183584/3

Check if you set a proxy with

ionic config get proxy -g
So, disable it:

ionic config unset proxy -g
