### ISSUE TITLE
cordova-res --skip-config --copy issue on Windows PC with Android Capacitor project

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-cli#4468]
Hi,

I have run this CLI on my Android only Capacitor project. But it tries to add iOS platform and gives below error. I don't need iOS platform right now since I work on Windows 10 PC.

_**cordova-res --skip-config --copy**_

```
Generated 18 resources for Android
Copied 27 resource items to Android
WARN:   Source icon "resources/icon.png" contains alpha channel, generated icons for iOS will not.

        Apple recommends avoiding transparency. See the App Icon Human Interface Guidelines[1] for details. Any transparency in your icon will be filled in with 
white.

        [1]: https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

Generated 47 resources for iOS
Copied 21 resource items to iOS
WARN:   Error with source file resources/icon.png: Error
    at new BaseError (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\error.js:7:22)
    at new ValidationError (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\error.js:31:9)
    at validateRasterResource (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\resources.js:39:15)
    at Object.validateResource (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\resources.js:159:11)
    at async readSourceImage (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\image.js:36:22)
    at async Object.resolveSourceImage (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\image.js:19:20)
    at async generateSimpleResources (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\platform.js:81:20)
    at async Object.run (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\platform.js:29:28)
    at async AsyncFunction.CordovaRes [as run] (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\index.js:35:36)
    at async AsyncFunction.runCommandLine (C:\Users\Sampath\AppData\Roaming\npm\node_modules\cordova-res\dist\index.js:92:28) {
  details: [Object],
  name: 'ValidationError',
  code: 'BAD_SOURCE'
}
ERROR:  Missing valid source image for Windows icons (sources: resources/windows/icon.png, resources/windows/icon.jpg, resources/windows/icon.jpeg, resources/icon.png, resources/icon.jpg, resources/icon.jpeg)
```

 **ionic info**

```
Ionic:

   Ionic CLI                     : 6.9.2 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.5
   @angular/cli                  : 9.1.5
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res                          : 0.14.0
   native-run (update available: 0.3.0) : 0.2.5

System:

   NodeJS : v12.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.1
   OS     : Windows 10
```

**Comment by dwieeb** [comment]
Use `cordova-res android --skip-config --copy` if you only want Android. This is expected behavior.
