### ISSUE TITLE
Issue when execute "cordova plugin add @ionic-enterprise/auth" on node 14.4.0

### ISSUE THREAD

**Issue by smilejos** [ionic-team/ionic-cli#4473]
**Description:**
`Cannot find plugin.xml for plugin "auth". Please try adding it again.`
Receive above error message when execute below command on node 14.4.0 npm 6.14.5
```
ionic cordova plugin add @ionic-enterprise/auth --variable AUTH_URL_SCHEME='stest'
```

**Steps to Reproduce:**

- use node 14.4.0
- create a new project
- add this plugin

```
ionic start
ionic cordova platform add ios
ionic cordova plugin add @ionic-enterprise/auth --variable AUTH_URL_SCHEME='stest'
```

**Output:**

```
ionic cordova plugin add @ionic-enterprise/auth --variable AUTH_URL_SCHEME='stest' --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'plugin', 'add', '@ionic-enterprise/auth' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, variable: 'AUTH_URL_SCHEME=stest', project: null, '--': [] } +4ms
  ionic:lib:project Project type from config: @ionic/angular (angular) +0ms
  ionic:lib:project Project details: { configPath: '/Users/mobile-mbp-ty02/Documents/Jos/mobile/test02/ionic.config.json', errors: [], context: 'app', type: 'angular' } +0ms
  ionic Context: { binPath: '/Users/mobile-mbp-ty02/.nvm/versions/node/v14.4.0/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/Users/mobile-mbp-ty02/.nvm/versions/node/v14.4.0/lib/node_modules/@ionic/cli', execPath: '/Users/mobile-mbp-ty02/Documents/Jos/mobile/test02', version: '6.10.0' } +0ms
  ionic:lib:integrations:cordova:config Loading Cordova Config (config.xml: '/Users/mobile-mbp-ty02/Documents/Jos/mobile/test02/config.xml', package.json: '/Users/mobile-mbp-ty02/Documents/Jos/mobile/test02/package.json') +0ms
> cordova plugin add @ionic-enterprise/auth --verbose --variable AUTH_URL_SCHEME=stest
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova plugin' [
  ionic:lib:telemetry   'add',
  ionic:lib:telemetry   '@ionic-enterprise/auth',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--variable=AUTH_URL_SCHEME=stest'
  ionic:lib:telemetry ] +0ms
No scripts found for hook "before_plugin_add".
No version specified for @ionic-enterprise/auth, retrieving version from package.json
Calling plugman.fetch on plugin "@ionic-enterprise/auth@^3.0.0"
Copying plugin "/Users/mobile-mbp-ty02/Documents/Jos/mobile/test02/node_modules/@ionic-enterprise/auth" => "/Users/mobile-mbp-ty02/Documents/Jos/mobile/test02/plugins/@ionic-enterprise/auth"
Calling plugman.install on plugin "/Users/mobile-mbp-ty02/Documents/Jos/mobile/test02/plugins/@ionic-enterprise/auth" for platform "ios
Cannot find plugin.xml for plugin "auth". Please try adding it again.
CordovaError: Cannot find plugin.xml for plugin "auth". Please try adding it again.
    at new PluginInfo (/Users/mobile-mbp-ty02/.nvm/versions/node/v14.4.0/lib/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfo.js:422:15)
    at PluginInfoProvider.get (/Users/mobile-mbp-ty02/.nvm/versions/node/v14.4.0/lib/node_modules/cordova/node_modules/cordova-common/src/PluginInfo/PluginInfoProvider.js:35:32)
    at /Users/mobile-mbp-ty02/.nvm/versions/node/v14.4.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:150:51
[ERROR] An error occurred while running subprocess cordova.

        cordova plugin add @ionic-enterprise/auth --verbose --variable AUTH_URL_SCHEME=s... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +80ms
```

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/Users/mobile-mbp-ty02/.nvm/versions/node/v14.4.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/mobile-mbp-ty02/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v14.4.0 (/Users/mobile-mbp-ty02/.nvm/versions/node/v14.4.0/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Other Information:**

Same Macbook use node 12.18.0 & npm 6.14.4 is working
```
Ionic:

   Ionic CLI                     : 6.10.0 (/Users/mobile-mbp-ty02/.nvm/versions/node/v12.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.15.0) : 0.14.0
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/mobile-mbp-ty02/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.0 (/Users/mobile-mbp-ty02/.nvm/versions/node/v12.18.0/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by imhoffd** [comment]
If you're a customer, you can [submit tickets](https://ionicframework.com/support/request) to us directly and speak with our support team. 

That being said, I think the solution is to use our version of Cordova, which resolves scoped packages.

```
npm uninstall -g cordova
npm install -g @ionic-enterprise/cordova
```
