### ISSUE TITLE
Error validating package name. Must look like: `com.company.Name`. Currently is: `Prototype1`

### ISSUE THREAD

**Issue by liquidcms** [ionic-team/ionic-cli#4487]
**Description:**
Following error when trying to build:
Error validating package name. Must look like: `com.company.Name`. Currently is: `Prototype1`

**Steps to Reproduce:**
ionic start myApp 
cd myApp
ionic server -> works fine
ionic cordova build android -> fails with this error:

Error validating package name. Must look like: `com.company.Name`. Currently is: `Prototype1`

comfig.xml widget id is set as per default and doing a search through the project i can't find Prototype1 anywhere. 

I have run this on a couple projects I am working on and they all give this error. I tried on an old Ionic 4 app and it spits our numerous errors; sadly that is another issue  but i guess ionic global install is going to be a major pita.

**Output:**
E:\www\myApp>ionic cordova build android --verbose
  ionic:lib Terminal info: { ci: false, shell: 'C:\\Windows\\system32\\cmd.exe', tty: true, windows: true } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'build', 'android' ], help: null, h: null, verbose: true, quiet: null,
 interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +7ms
  ionic:lib:project Project type from config: @ionic/angular (angular) +0ms
  ionic:lib:project Project details: { configPath: 'E:\\www\\AndTest\\ionic.config.json', errors: [], context: 'app', ty
pe: 'angular' } +3ms
  ionic Context: { binPath: 'C:\\Users\\Peter\\AppData\\Roaming\\npm\\node_modules\\@ionic\\cli\\bin\\ionic', libPath: '
C:\\Users\\Peter\\AppData\\Roaming\\npm\\node_modules\\@ionic\\cli', execPath: 'E:\\www\\AndTest', version: '6.10.1' } +
0ms
  ionic:lib:integrations:cordova:config Loading Cordova Config (config.xml: 'E:\\www\\AndTest\\config.xml', package.json
: 'E:\\www\\AndTest\\package.json') +0ms
  ionic:lib:integrations:cordova:config Invalid package.json for Cordova. Missing or invalid Cordova entries in 'E:\\www
\\AndTest\\package.json' +27ms
> cordova.cmd platform add android --save
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Error validating package name. Must look like: `com.company.Name`. Currently is: `Prototype1`
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd platform add android --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +2ms
  ionic:utils-process error while killing process tree for 133168: Error: Command failed: taskkill /pid 133168 /T /F
  ionic:utils-process ERROR: The process "133168" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:303:12)
  ionic:utils-process     at ChildProcess.emit (events.js:315:20)
  ionic:utils-process     at maybeClose (internal/child_process.js:1021:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 133168 /T /F'
  ionic:utils-process } +220ms
  ionic:utils-process onBeforeExit handler: error from function: Error: Command failed: taskkill /pid 133168 /T /F
  ionic:utils-process ERROR: The process "133168" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:303:12)
  ionic:utils-process     at ChildProcess.emit (events.js:315:20)
  ionic:utils-process     at maybeClose (internal/child_process.js:1021:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 133168 /T /F'
  ionic:utils-process } +24ms
  ionic:utils-process processExit: exiting (exit code: 1) +29ms

E:\www\myApp>

**My `ionic info`:**
E:\www\myApp>ionic info

Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\Peter\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.2.8

System:

   Android SDK Tools : 26.1.1 (c:\android-sdk)
   NodeJS            : v12.18.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.5
   OS                : Windows 7

**Other Information:**
I have used Ionic 4 a fair bit but this is my first attempt with Ionic 5.

**Comment by liquidcms** [comment]
Figured it out. Somehow i had a www, node_modules, platforms, etc installed in the parent folder of my apps; and sure enough that www folder had a config.xml with Prototype1 set as some ID value. Removing these folders and cordova build at least gets past that point now... but still fails: something about sharp module not self installing - but that's a different issue.
