### ISSUE TITLE
[error] Error: Call retries were exceeded     at ChildProcessWorker.initialize 

### ISSUE THREAD

**Issue by muhammedMoussa** [ionic-team/ionic-cli#4490]
**Description:**

I'm trying to build the app it took long too much time, then got the error.
app upgraded from angular 8 to 10

`old: package.json`
```
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-oauth2-oidc": "^8.0.4",
    "core-js": "^2.5.4",
    "devextreme": "19.2.3",
    "devextreme-angular": "19.2.3",
    "node-sass": "^4.13.0",
    "node-schedule": "^1.3.2",
    "rxjs": "~6.5.1",
    "subsink": "^1.0.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@ionic/app-scripts": "^3.2.4",
    "@ionic/lab": "2.0.13",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
```

`updated: package.json`
```
"dependencies": {
    "@angular/animations": "~10.0.3",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~10.0.3",
    "@angular/compiler": "~10.0.3",
    "@angular/core": "~10.0.3",
    "@angular/forms": "~10.0.3",
    "@angular/platform-browser": "~10.0.3",
    "@angular/platform-browser-dynamic": "~10.0.3",
    "@angular/router": "~10.0.3",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.2.3",
    "@ionic/angular-toolkit": "^2.2.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^8.4.0",
    "@ngrx/store": "^8.4.0",
    "@ngrx/store-devtools": "^8.4.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-auth-oidc-client": "^10.0.10",
    "angular-oauth2-oidc": "^8.0.4",
    "cordova-android": "8.1.0",
    "devextreme": "20.1.6",
    "devextreme-angular": "20.1.6",
    "devextreme-schematics": "^1.0.11",
    "node-schedule": "^1.3.2",
    "oidc-client": "^1.9.1",
    "rxjs": "~6.6.0",
    "subsink": "^1.0.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.3",
    "@angular/cli": "~10.0.2",
    "@angular/compiler-cli": "~10.0.3",
    "@angular/language-service": "~10.0.3",
    "@ionic/app-scripts": "^3.2.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^4.0.0",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.2",
    "cordova-plugin-whitelist": "1.3.3",
    "devextreme-cli": "latest",
    "devextreme-themebuilder": "latest",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.9.6"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
```

**Steps to Reproduce:**
```
ionic cordova build android
```

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\m.mousa\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.1000.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 10.0.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows Server 2016
```

**Error**
```
Compiling devextreme-angular/ui/vector-map : es2015 as esm2015
Compiling devextreme-angular : es2015 as esm2015
Generating ES5 bundles for differential loading...
An unhandled exception occurred: Call retries were exceeded
See "C:\Users\m.mousa\AppData\Local\Temp\ng-Hx7Tc8\angular-errors.log" for further details.
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 127.

        Re-running this command with the --verbose flag may provide more information.

```
*Log*

```
[error] Error: Call retries were exceeded
    at ChildProcessWorker.initialize (D:\***\node_modules\jest-worker\build\workers\ChildProcessWorker.js:191:21)
    at ChildProcessWorker._onExit (D:\***\node_modules\jest-worker\build\workers\ChildProcessWorker.js:268:12)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)


```

**Comment by LudovicPecquot** [comment]
same issue here
note: a 'npm run build' runs fine..

**Comment by muhammedMoussa** [comment]
> same issue here
> note: a 'npm run build' runs fine..

I need an APK, did `npm run build` generate APK?

**Comment by petrot** [comment]
Same error on my little project.
Increase the memory limit helped me:
`node --max-old-space-size=8192`

**Comment by ghost** [comment]
I have the same issue after installing DexExtreme in my project. Going to try rolling back to a previous known working version (from a separate application) and see what happens.
