### ISSUE TITLE
FATAL EXCEPTION: main in admob free rewarded video ad load

### ISSUE THREAD

**Issue by preetamjakhmola** [ionic-team/ionic-cli#4685]
**Description:**
I have implemented rewarded video ad in my pedometer application. everything is running perfect.
I build and run application and it gave error in 
import android.support.annotation.NonNull;
I changed it to 
import androidx.annotation.NonNull;
in Admob.java file

Now its running fine and I also changed $ADMOB_APP_ID with my ADMOB Id.

Now I created and installed application in device. application is running perfect but when i request for my test rewarded ad. I just crashes the application and show me error message given below.

**Output:**
Process: com.pedoapp.app, PID: 5250
    java.lang.NoSuchMethodError: No static method getRewardedVideoAdInstance(Landroid/content/Context;)Lcom/google/android/gms/ads/reward/RewardedVideoAd; in class Lcom/google/android/gms/ads/MobileAds; or its super classes (declaration of 'com.google.android.gms.ads.MobileAds' appears in /data/app/com.pedoapp.app-gkBORzazp4GMI6-TqQlubA==/base.apk)
        at name.ratson.cordova.admob.rewardvideo.RewardVideoExecutor$1.run(RewardVideoExecutor.java:47)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 It worked before once but next time I reinstall application it stopped working.

**Comment by jcesarmobile** [comment]
This is not related to ionic, please, report on the plugin repository
