### ISSUE TITLE
npm i --package-lock-only executed on @ionic/cli@6.16.2 but not @ionic/cli@6.16.1

### ISSUE THREAD

**Issue by mraible** [ionic-team/ionic-cli#4710]
**Description:**

I help maintain the [JHipster Module for Ionic](https://github.com/oktadev/generator-jhipster-ionic). Our CI tests started failing recently because running `ionic start` causes `npm i --package-lock-only` to be invoked. This doesn't happen with @ionic/cli@6.16.1. 

**Steps to Reproduce:**

```
git clone https://github.com/oktadev/generator-jhipster-ionic.git
cd generator-jhipster-ionic
npm i
npm i -g @ionic/cli@6.16.2
npm test
```

**Output:**

```
> generator-jhipster-ionic@7.0.0 test /Users/mraible/dev/generator-jhipster-ionic
> mocha --timeout 10000 test/*



  JHipster generator jhipster-generator-ionic
    Test Generating Ionic App with JWT
--no-confirm: Integrate your new app with Capacitor to target native iOS and Android? No

Updating lockfile.
> npm i --package-lock-only
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @ng-bootstrap/ng-bootstrap@9.1.0 requires a peer of @angular/localize@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.6.0 requires a peer of jasmine-core@>=3.7.1 but none is installed. You must install peer dependencies yourself.
npm WARN html-loader@2.1.2 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.

added 2407 packages and audited 2409 packages in 54.617s
found 9 vulnerabilities (2 low, 1 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Join the Ionic Community! 💙

Connect with millions of developers on the Ionic Forum and get access to live events, news updates, and more.

--no-confirm: Create free Ionic account? No

Starter Welcome:
Welcome to the Ionic JHipster Starter!

For more details, please see the project's README:
https://github.com/oktadeveloper/ionic-jhipster-starter/blob/main/README.md

Your Ionic app is ready! Follow these next steps:

- Go to your new project: cd ./ionic4j-jwt
- Run ionic serve within the app directory to see your app in the browser
- Run ionic capacitor add to add a native iOS or Android project using Capacitor
- Generate your app icon and splash screens using cordova-res --skip-config --copy
- Explore the Ionic docs for components, tutorials, and more: https://ion.link/docs
- Building an enterprise app? Ionic has Enterprise Support and Features: https://ion.link/enterprise-edition
      1) "before each" hook for "generates a ionic4j-jwt/package.json file"

  JHipster generator jhipster-generator-ionic
    Test Generating Ionic App with OAuth
--no-confirm: Integrate your new app with Capacitor to target native iOS and Android? No

Updating lockfile.
> npm i --package-lock-only
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @ng-bootstrap/ng-bootstrap@9.1.0 requires a peer of @angular/localize@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.6.0 requires a peer of jasmine-core@>=3.7.1 but none is installed. You must install peer dependencies yourself.
npm WARN html-loader@2.1.2 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.

added 2407 packages and audited 2409 packages in 54.219s
found 9 vulnerabilities (2 low, 1 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Join the Ionic Community! 💙

Connect with millions of developers on the Ionic Forum and get access to live events, news updates, and more.

--no-confirm: Create free Ionic account? No

Starter Welcome:
Welcome to the Ionic JHipster Starter!

For more details, please see the project's README:
https://github.com/oktadeveloper/ionic-jhipster-starter/blob/main/README.md

Your Ionic app is ready! Follow these next steps:

- Go to your new project: cd ./ionic4j-oauth2
- Run ionic serve within the app directory to see your app in the browser
- Run ionic capacitor add to add a native iOS or Android project using Capacitor
- Generate your app icon and splash screens using cordova-res --skip-config --copy
- Explore the Ionic docs for components, tutorials, and more: https://ion.link/docs
- Building an enterprise app? Ionic has Enterprise Support and Features: https://ion.link/enterprise-edition
      2) "before each" hook for "deletes files that only apply to JWT"


  0 passing (2m)
  2 failing

  1) JHipster generator jhipster-generator-ionic
       Test Generating Ionic App with JWT
         "before each" hook for "generates a ionic4j-jwt/package.json file":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster-ionic/test/test-app.js)
      at listOnTimeout (internal/timers.js:555:17)
      at processTimers (internal/timers.js:498:7)

  2) JHipster generator jhipster-generator-ionic
       Test Generating Ionic App with OAuth
         "before each" hook for "deletes files that only apply to JWT":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster-ionic/test/test-oauth.js)
      at listOnTimeout (internal/timers.js:555:17)
      at processTimers (internal/timers.js:498:7)



CREATE src/app/auth/auth-config.service.ts (840 bytes)
CREATE npm-shrinkwrap.json (200 bytes)
CREATE src/app/auth/auth-guard.service.ts (657 bytes)
CREATE src/app/auth/auth-http.service.ts (825 bytes)
CREATE src/app/auth/auth.module.ts (1266 bytes)
CREATE src/app/auth/ng-http.service.ts (1347 bytes)
CREATE src/app/auth/user-info.model.ts (188 bytes)
CREATE src/app/auth/auth-callback/auth-callback.module.ts (574 bytes)
CREATE src/app/auth/auth-callback/auth-callback.page.ts (1032 bytes)
CREATE src/app/auth/end-session/end-session.module.ts (564 bytes)
CREATE src/app/auth/end-session/end-session.page.ts (462 bytes)
CREATE src/app/auth/factories/auth.factory.ts (1258 bytes)
CREATE src/app/auth/factories/browser.factory.ts (290 bytes)
CREATE src/app/auth/factories/http.factory.ts (379 bytes)
CREATE src/app/auth/factories/index.ts (134 bytes)
CREATE src/app/auth/factories/storage.factory.ts (318 bytes)
CREATE src/app/login/login.module.ts (538 bytes)
CREATE src/app/login/login.page.html (187 bytes)
CREATE src/app/login/login.page.scss (0 bytes)
CREATE src/app/login/login.page.spec.ts (950 bytes)
CREATE src/app/login/login.page.ts (1031 bytes)
CREATE src/app/tab1/tab1.page.html (2298 bytes)
CREATE src/app/tab1/tab1.page.spec.ts (942 bytes)
CREATE src/app/tab1/tab1.page.ts (1467 bytes)
UPDATE src/app/app.module.ts (1858 bytes)
UPDATE tsconfig.app.json (472 bytes)
UPDATE src/app/app-routing.module.ts (660 bytes)
UPDATE src/app/app.component.spec.ts (1322 bytes)
UPDATE src/app/app.component.ts (624 bytes)
UPDATE src/environments/environment.ts (1013 bytes)
npm ERR! Test failed.  See above for more details.
Execution time: 2 min. 2 s.
```

If I use v6.16.1, it does not happen.

```
npm i -g @ionic/cli@6.16.1
npm test
```

**Output:**

```
> generator-jhipster-ionic@7.0.0 test /Users/mraible/dev/generator-jhipster-ionic
> mocha --timeout 10000 test/*



  JHipster generator jhipster-generator-ionic
    Test Generating Ionic App with JWT
--no-confirm: Integrate your new app with Capacitor to target native iOS and Android? No


Join the Ionic Community! 💙

Connect with millions of developers on the Ionic Forum and get access to live events, news updates, and more.

--no-confirm: Create free Ionic account? No

Starter Welcome:
Welcome to the Ionic JHipster Starter!

For more details, please see the project's README:
https://github.com/oktadeveloper/ionic-jhipster-starter/blob/main/README.md

Your Ionic app is ready! Follow these next steps:

- Go to your new project: cd ./ionic4j-jwt
- Run ionic serve within the app directory to see your app in the browser
- Run ionic capacitor add to add a native iOS or Android project using Capacitor
- Generate your app icon and splash screens using cordova-res --skip-config --copy
- Explore the Ionic docs for components, tutorials, and more: https://ion.link/docs
- Building an enterprise app? Ionic has Enterprise Support and Features: https://ion.link/enterprise-edition
      ✓ generates a ionic4j-jwt/package.json file
--no-confirm: Integrate your new app with Capacitor to target native iOS and Android? No


Join the Ionic Community! 💙

Connect with millions of developers on the Ionic Forum and get access to live events, news updates, and more.

--no-confirm: Create free Ionic account? No

Starter Welcome:
Welcome to the Ionic JHipster Starter!

For more details, please see the project's README:
https://github.com/oktadeveloper/ionic-jhipster-starter/blob/main/README.md

Your Ionic app is ready! Follow these next steps:

- Go to your new project: cd ./ionic4j-jwt
- Run ionic serve within the app directory to see your app in the browser
- Run ionic capacitor add to add a native iOS or Android project using Capacitor
- Generate your app icon and splash screens using cordova-res --skip-config --copy
- Explore the Ionic docs for components, tutorials, and more: https://ion.link/docs
- Building an enterprise app? Ionic has Enterprise Support and Features: https://ion.link/enterprise-edition
      ✓ does not delete app/services/auth/auth-jwt.service.ts

  JHipster generator jhipster-generator-ionic
    Test Generating Ionic App with OAuth
--no-confirm: Integrate your new app with Capacitor to target native iOS and Android? No


Join the Ionic Community! 💙

Connect with millions of developers on the Ionic Forum and get access to live events, news updates, and more.

--no-confirm: Create free Ionic account? No

Starter Welcome:
Welcome to the Ionic JHipster Starter!

For more details, please see the project's README:
https://github.com/oktadeveloper/ionic-jhipster-starter/blob/main/README.md

Your Ionic app is ready! Follow these next steps:

- Go to your new project: cd ./ionic4j-oauth2
- Run ionic serve within the app directory to see your app in the browser
- Run ionic capacitor add to add a native iOS or Android project using Capacitor
- Generate your app icon and splash screens using cordova-res --skip-config --copy
- Explore the Ionic docs for components, tutorials, and more: https://ion.link/docs
- Building an enterprise app? Ionic has Enterprise Support and Features: https://ion.link/enterprise-edition
CREATE src/app/auth/auth-config.service.ts (840 bytes)
CREATE npm-shrinkwrap.json (200 bytes)
CREATE src/app/auth/auth-guard.service.ts (657 bytes)
CREATE src/app/auth/auth-http.service.ts (825 bytes)
CREATE src/app/auth/auth.module.ts (1266 bytes)
CREATE src/app/auth/ng-http.service.ts (1347 bytes)
CREATE src/app/auth/user-info.model.ts (188 bytes)
CREATE src/app/auth/auth-callback/auth-callback.module.ts (574 bytes)
CREATE src/app/auth/auth-callback/auth-callback.page.ts (1032 bytes)
CREATE src/app/auth/end-session/end-session.module.ts (564 bytes)
CREATE src/app/auth/end-session/end-session.page.ts (462 bytes)
CREATE src/app/auth/factories/auth.factory.ts (1258 bytes)
CREATE src/app/auth/factories/browser.factory.ts (290 bytes)
CREATE src/app/auth/factories/http.factory.ts (379 bytes)
CREATE src/app/auth/factories/index.ts (134 bytes)
CREATE src/app/auth/factories/storage.factory.ts (318 bytes)
CREATE src/app/login/login.module.ts (538 bytes)
CREATE src/app/login/login.page.html (187 bytes)
CREATE src/app/login/login.page.scss (0 bytes)
CREATE src/app/login/login.page.spec.ts (950 bytes)
CREATE src/app/login/login.page.ts (1031 bytes)
CREATE src/app/tab1/tab1.page.html (2298 bytes)
CREATE src/app/tab1/tab1.page.spec.ts (942 bytes)
CREATE src/app/tab1/tab1.page.ts (1467 bytes)
UPDATE src/app/app.module.ts (1858 bytes)
UPDATE tsconfig.app.json (472 bytes)
UPDATE src/app/app-routing.module.ts (660 bytes)
UPDATE src/app/app.component.spec.ts (1322 bytes)
UPDATE src/app/app.component.ts (624 bytes)
UPDATE src/environments/environment.ts (1013 bytes)
      ✓ deletes files that only apply to JWT
--no-confirm: Integrate your new app with Capacitor to target native iOS and Android? No


Join the Ionic Community! 💙

Connect with millions of developers on the Ionic Forum and get access to live events, news updates, and more.

--no-confirm: Create free Ionic account? No

Starter Welcome:
Welcome to the Ionic JHipster Starter!

For more details, please see the project's README:
https://github.com/oktadeveloper/ionic-jhipster-starter/blob/main/README.md

Your Ionic app is ready! Follow these next steps:

- Go to your new project: cd ./ionic4j-oauth2
- Run ionic serve within the app directory to see your app in the browser
- Run ionic capacitor add to add a native iOS or Android project using Capacitor
- Generate your app icon and splash screens using cordova-res --skip-config --copy
- Explore the Ionic docs for components, tutorials, and more: https://ion.link/docs
- Building an enterprise app? Ionic has Enterprise Support and Features: https://ion.link/enterprise-edition
CREATE src/app/auth/auth-config.service.ts (840 bytes)
CREATE npm-shrinkwrap.json (200 bytes)
CREATE src/app/auth/auth-guard.service.ts (657 bytes)
CREATE src/app/auth/auth-http.service.ts (825 bytes)
CREATE src/app/auth/auth.module.ts (1266 bytes)
CREATE src/app/auth/ng-http.service.ts (1347 bytes)
CREATE src/app/auth/user-info.model.ts (188 bytes)
CREATE src/app/auth/auth-callback/auth-callback.module.ts (574 bytes)
CREATE src/app/auth/auth-callback/auth-callback.page.ts (1032 bytes)
CREATE src/app/auth/end-session/end-session.module.ts (564 bytes)
CREATE src/app/auth/end-session/end-session.page.ts (462 bytes)
CREATE src/app/auth/factories/auth.factory.ts (1258 bytes)
CREATE src/app/auth/factories/browser.factory.ts (290 bytes)
CREATE src/app/auth/factories/http.factory.ts (379 bytes)
CREATE src/app/auth/factories/index.ts (134 bytes)
CREATE src/app/auth/factories/storage.factory.ts (318 bytes)
CREATE src/app/login/login.module.ts (538 bytes)
CREATE src/app/login/login.page.html (187 bytes)
CREATE src/app/login/login.page.scss (0 bytes)
CREATE src/app/login/login.page.spec.ts (950 bytes)
CREATE src/app/login/login.page.ts (1031 bytes)
CREATE src/app/tab1/tab1.page.html (2298 bytes)
CREATE src/app/tab1/tab1.page.spec.ts (942 bytes)
CREATE src/app/tab1/tab1.page.ts (1467 bytes)
UPDATE src/app/app.module.ts (1858 bytes)
UPDATE tsconfig.app.json (472 bytes)
UPDATE src/app/app-routing.module.ts (660 bytes)
UPDATE src/app/app.component.spec.ts (1322 bytes)
UPDATE src/app/app.component.ts (624 bytes)
UPDATE src/environments/environment.ts (1013 bytes)
      ✓ adds @oktadev/schematics and keeps cordova-plugin-camera


  4 passing (14s)

Execution time: 16 s.
```

**Comment by smzelek** [comment]
@mraible Hi Matt,

Thank you for the bug report. We are looking into this issue, and I will post another reply here with more information.

In the meantime, could you tell me if I'm understanding your use case? It looks like your unit tests involve invoking `ionic start` with the `--no-deps` flag, and they are now failing due to the timeout being used up by the `npm i --package-lock-only`. This was a recent change intended to ensure the generated `package.json` from `ionic start` is in sync with the `package-lock.json`.

**Comment by mraible** [comment]
@smzelek Yes, you have summarized my use case correctly.

**Comment by giocalitri** [comment]
@mraible We just reverted the change in `6.16.3`: let us know if it is back to the same behavior as before

**Comment by mraible** [comment]
@giocalitri I just tried it locally and it does indeed fix the problem. Thank you! 🙏
