### ISSUE TITLE
bug: ionic cordova build android failed with "Project target does not exist"

### ISSUE THREAD

**Issue by anatoly-spb** [ionic-team/ionic-cli#4850]
**Description:**

>ionic cordova build android 

failed with:
```
> ng.cmd run app:ionic-cordova-build --platform=android
An unhandled exception occurred: Project target does not exist.
See "C:\Users\anato\AppData\Local\Temp\ng-PnAW1P\angular-errors.log" for further details.
[�[40mERROR�[49m] An error occurred while running subprocess ng.
        
        ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 127.
        
        Re-running this command with the --verbose flag may provide more information.
```

**Steps to Reproduce:**

```
ionic start ionic-cordova-angular tabs --cordova --type=angular
cd ionic-cordova-angular
ionic cordova resources --force
ionic cordova platform add android
ionic cordova build android
```

**Output:**

Here is a content of C:\Users\anato\AppData\Local\Temp\ng-PnAW1P\angular-errors.log:

```
[error] Error: Project target does not exist.
    at findProjectTarget (F:\ionic\ionic-cordova-angular\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:49:15)
    at Object.getBuilderName (F:\ionic\ionic-cordova-angular\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:62:46)
    at WorkspaceNodeModulesArchitectHost.getBuilderNameForTarget (F:\ionic\ionic-cordova-angular\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:101:35)
    at RunCommand.runSingleTarget (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\models\architect-command.js:242:55)
    at RunCommand.runArchitectTarget (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\models\architect-command.js:295:35)
    at RunCommand.run (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\commands\run-impl.js:15:25)
    at RunCommand.validateAndRun (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\models\command.js:136:33)
    at async runCommand (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\models\command-runner.js:224:24)
    at async default_1 (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\lib\cli\index.js:70:31)
```

**My `ionic info`:**

```
Ionic:

Ionic CLI : 6.19.1 (C:\Tools\nvm\v16.15.0\node_modules@ionic\cli)
Ionic Framework : @ionic/angular 6.1.5
@angular-devkit/build-angular : 13.2.6
@angular-devkit/schematics : 13.2.6
@angular/cli : 13.2.6
@ionic/angular-toolkit : 6.1.0

Cordova:

Cordova CLI : 11.0.0
Cordova Platforms : android 10.1.2
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 3 other plugins)

Utility:

cordova-res : 0.15.4
native-run : 1.5.0

System:

Android SDK Tools : 26.1.1 (D:\Android\sdk)
NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
npm : 8.5.5
OS : Windows 10
```

**Other Information:**

https://github.com/ionic-team/ionic-framework/issues/25288
https://github.com/ionic-team/ionic-framework/issues/24940

**Workaround:**

As workaround we can use:

>npx ng add @ionic/cordova-builders

After adding @ionic/cordova-builders build successfully finished

It seems to me `ionic start` must be patched to accomplish the action described above

**Comment by marcosfm17** [comment]
cordova platform rm android
cordova platform add android

**Comment by anatoly-spb** [comment]
> cordova platform rm android cordova platform add android

Are you sure that is helpful? 

Look at these:
```
ionic start ionic-cordova-angular tabs --cordova --type=angular
cd ionic-cordova-angular
ionic cordova resources --force
ionic cordova platform add android
ionic cordova build android
```

Here is a clear environment. So why do we need remove unexisted platform?

**Comment by marcosfm17** [comment]
I have a project that is for several clients changing the images/icons/name of the app.
So every time I update a client I floor the images and run "ionic cordova resources android" and then "ionic cordova build android".
This had been working fine until a week ago when it stopped compiling because it was deprecated.
The solution I could find so far is every time I want to build for a different client I have to run "cordova platform rm android" then "cordova platform add android" (both without ionic) and then I can just build without error "ionic cordova build android ". If I run ionic cordova build android" it is not compiling me afterwards.
For now it is the way I found to keep it compiling. I hope it helps you. Always remember to make a backup before executing the commands ;)
Hug
