### ISSUE TITLE
glob pattern string required - version 2.0.0-beta.17

### ISSUE THREAD

**Issue by mchapman** [ionic-team/ionic-cli#739]
✗ Caught exception:
 TypeError: glob pattern string required
    at new Minimatch (/home/mark/Projects/meds/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/glob/node_modules/minimatch/minimatch.js:108:11)
    at setopts (/home/mark/Projects/meds/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/glob/common.js:112:20)
    at new Glob (/home/mark/Projects/meds/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/glob/glob.js:117:3)
    at FSWatcher.processEvent (/home/mark/Projects/meds/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/index.js:92:35)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSWatcher.<anonymous> (/home/mark/Projects/meds/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/index.js:172:38)
    at FSWatcher._emit (/home/mark/Projects/meds/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/index.js:212:5)
    at FSWatcher._remove (/home/mark/Projects/meds/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/index.js:525:50)
    at /home/mark/Projects/meds/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/index.js:451:20
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by tlancina** [comment]
What does your ionic.config.js look like?

**Comment by mchapman** [comment]
module.exports = {
  proxies: null,

  paths: {
    html : {
      src: ['app/**/*.html'],
      dest: "www/build"
    },
    sass: {
      src: ['app/theme/app.+(ios|md).scss'],
      dest: 'www/build/css',
      include: [
        'node_modules/ionic-framework',
        'node_modules/ionicons/dist/scss'
      ]
    },
    fonts: {
      src: ['node_modules/ionic-framework/fonts/**/*.+(ttf|woff|woff2)'],
      dest: "www/build/fonts"
    },
    watch: {
      sass: ['app/**/*.scss'],
      html: ['app/**/*.html'],
      livereload: [
        'www/build/**/*.html',
        'www/build/**/*.js',
        'www/build/**/*.css'
      ]
    }
  },

  autoPrefixerOptions: {
    browsers: [
      'last 2 versions',
      'iOS >= 7',
      'Android >= 4',
      'Explorer >= 10',
      'ExplorerMobile >= 11'
    ],
    cascade: false
  },

  // hooks execute before or after all project-related Ionic commands
  // (so not for start, docs, but serve, run, etc.) and take in the arguments
  // passed to the command as a parameter
  //
  // The format is 'before' or 'after' + commandName (uppercased)
  // ex: beforeServe, afterRun, beforePrepare, etc.
  hooks: {
    beforeServe: function (argv) {
      //console.log('beforeServe');
    }
  }
};

**Comment by tlancina** [comment]
Thanks, everything seems to be in order there.

It looks like: https://github.com/floatdrop/gulp-watch/issues/187, but I'm still unsure where or when it's happening.  Does that error throw when you have edited or deleted a specific file? It's hard to track it down just from that error alone.

**Comment by mchapman** [comment]
It was when I deleted a file, but not sure I can reproduce.  Sorry.

**Comment by erg1** [comment]
I had this happen when I deleted a page from the starter whose Sass file was referenced by the App Shared Imports in app/theme/app.core.scss.  It looks it was likely triggered by the Sass builder encountering a missing path, but I can't recall exactly what steps I took to get the error.

**Comment by derivdiggs** [comment]
I have this error in beta.10. Probably because I moved around a component between a few folders/directories. How do I fix it?

**Comment by erg1** [comment]
Take a look at **app/theme/app.core.scss**.  For me it was trying to import a  may be trying to import an SCSS file I had removed.
