### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined    at Request._callback (C:\Users\chan\AppData\Roaming\npm\node_modules\ionic\n de_modules\ionic-app-lib\lib\utils.js:133:37)

### ISSUE THREAD

**Issue by MatNM** [ionic-team/ionic-cli#915]
C:\wamp\www\web>ionic start myTutorial tutorial --ts
Creating Ionic app in folder C:\wamp\www\web\myTutorial based on tutorial projec
t
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tutorial/archive/master.z
ip
Caught exception:
 TypeError: Cannot read property 'bold' of undefined
    at Request._callback (C:\Users\chan\AppData\Roaming\npm\node_modules\ionic\n
ode_modules\ionic-app-lib\lib\utils.js:133:37)
    at Request.self.callback (C:\Users\chan\AppData\Roaming\npm\node_modules\ion
ic\node_modules\request\request.js:373:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\chan\AppData\Roaming\npm\node_modules\ionic
\node_modules\request\request.js:1318:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\chan\AppData\Roaming\npm\node_modul
es\ionic\node_modules\request\request.js:1266:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by tlancina** [comment]
Thanks for the issue, this should be resolved in https://github.com/driftyco/ionic-app-lib/commit/25fdea7440924bdc0d35586b56317caf6999cf98 and be out in the next beta release.
