### ISSUE TITLE
ionic serve segfaulted

### ISSUE THREAD

**Issue by wli** [ionic-team/ionic-cli#966]
```
Caught exception:
 Error: watch /Users/wli/projects/boost/app/www/build/css ENOENT
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at Gaze._watchDir (/Users/wli/.nvm/versions/node/v5.8.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /Users/wli/.nvm/versions/node/v5.8.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/Users/wli/.nvm/versions/node/v5.8.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/wli/.nvm/versions/node/v5.8.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /Users/wli/.nvm/versions/node/v5.8.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/wli/.nvm/versions/node/v5.8.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/wli/.nvm/versions/node/v5.8.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

File changed: www/build/fonts/noto-sans-regular.ttf
File changed: www/build/fonts/roboto-bold.ttf
File changed: www/build/fonts/roboto-bold.woff
File changed: www/build/fonts/roboto-light.ttf
File changed: www/build/fonts/roboto-light.woff
File changed: www/build/fonts/roboto-medium.ttf
File changed: www/build/fonts/roboto-medium.woff
File changed: www/build/fonts/roboto-regular.ttf
File changed: www/build/fonts/roboto-regular.woff
JS changed:   www/build/js/app.bundle.js
JS changed:   www/build/js/app.bundle.js.map
./bin/dev: line 7: 60979 Segmentation fault: 11  ionic serve -a
```

**Comment by jgw96** [comment]
Hello @wli ! Thanks for opening an issue with us! Would you mind running `ionic info` from within your project and posting the output here?

**Comment by wli** [comment]
@jgw96 

```
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v5.8.0
```

**Comment by jgw96** [comment]
Thanks! And which command were you running when this error occured, `ionic serve` ?

**Comment by wli** [comment]
`ionic serve -a`

**Comment by wli** [comment]
Just encountered this again. This time it happened in the `ionic serve -a` command, but I was simultaneously running `ionic run android --device`.

**Comment by georgedim** [comment]
I am getting the same error also with ionic 1. The result of ionic info is : 

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.9.1
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.3 Build version 8E162
